### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by xraywinedrinker** [bropat/eufy-security-ws#1]
**Describe the bug**  
I am unable to install on my rpi4 buster and receive the following error. I tried with and without sudo. Here is the error I received running npm 7.12.1.

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/pi/node_modules/eufy-security-ws/dist/bin/server.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/pi/node_modules/eufy-security-ws/dist/bin/server.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by bropat** [comment]
Hi @xraywinedrinker,
an error occurred during the publishing process. Have now unpublished the package version 0.1.0. In 24h I can publish the corrected package version 0.1.0 again.

**Comment by bropat** [comment]
@xraywinedrinker 

Issue should be solved with version 0.1.1
