### ISSUE TITLE
[Bug]: No stations and no devices on shared home

### ISSUE THREAD

**Issue by mbrunn** [bropat/eufy-security-ws#105]
### Version

0.9.1

### Node version

14.18.1

### Operating System type

Docker

### Operating system version

Ubuntu 20.04.3

### Describe the bug

After a recent update of the eufy app I can no longer find an stations or devices.
The culprit seems to be, that the api retrives stations and devices for a home, that does not exist.

I attached a screenshot of the configuration in the app and the logs for the docker container that runs the image.

### To reproduce

1. Update Eufy App and share home with other users.
2. Start docker container with a user and password that has access to the shared home.
3. Be sad, because it tries to fetch devices for a home that does not exist. 

### Screenshots & Logfiles

[logs.txt](https://github.com/bropat/eufy-security-ws/files/8638933/logs.txt)
![docker_logs](https://user-images.githubusercontent.com/83284692/167105191-38a2f938-2d66-44b6-bed3-24fac8a899ae.jpg)
### Eufy App config
![homeconfig_1](https://user-images.githubusercontent.com/83284692/167104913-a104bb80-d84e-4410-b052-666c8f10b380.png)
![homeconfig_2](https://user-images.githubusercontent.com/83284692/167104917-dc14414b-9545-4df9-8e20-2c8f7633ab6f.jpg)

**Comment by bropat** [comment]
Have you set the `country` parameter correctly? It must be set the same as in the Eufy app, otherwise no devices will be found.

[docs](https://bropat.github.io/eufy-security-ws/#/docker)

**Comment by mbrunn** [comment]
Thanks for your help. Indeed, the country parameter was not set correctly.
