### ISSUE TITLE
[Bug]: After updating to 0.9.1 no camera.doorbell available in Home Assistant with 2K video doorbell

### ISSUE THREAD

**Issue by YarneThatsMe** [bropat/eufy-security-ws#109]
### Version

0.9.1

### Node version

-

### Operating System type

Docker

### Operating system version

UNRAID

### Describe the bug

After updating to 0.9.1 there is no entity in Home Assistant which displays the latest recording of the 2K video doorbell whereas the previous version did give that posibility.

I only see the entities: Switches, select, sensors and binary. (So no camera anymore)

### To reproduce

1. Go to 'Home Assistant'
2. Click on 'Integrations'
3. Scroll down to 'Eufy Security'

**Comment by bropat** [comment]
Look [here](https://github.com/fuatakgun/eufy_security/issues/321).

**Comment by kusmierz** [comment]
Solved in https://github.com/mvanderheijden/eufy_security/commit/19695e6a1588bae99b013e68ac73c651f8bbd19a, any chance to update the docker image?

**Comment by bropat** [comment]
> Solved in [mvanderheijden/eufy_security@19695e6](https://github.com/mvanderheijden/eufy_security/commit/19695e6a1588bae99b013e68ac73c651f8bbd19a), any chance to update the docker image?

Wrong repo...
