### ISSUE TITLE
Mount Source Path: Read only file system

### ISSUE THREAD

**Issue by ahamster13** [bropat/eufy-security-ws#11]
Ok, so i have tried this with 2 different sd cards and fresh HA install.
I still get the same issue and wondering if there is something wrong with the code or files? Or docker?

I have tried uninstalling Node.js and chnaging from Latest LTS Version: 14.17.3 to Latest Current Version: 16.5.0

If i try to rerun docker:
➜ eufy-security-ws git:(master) docker run -it -e USERNAME=ssa90899@eoopy.com -e PASSWORD=******* -v "$(pwd)"/data:/data -p 3000:3000 bropat/eufy-security-ws :latest

I get this:
docker: Error response from daemon: error while creating mount source path '/root/eufy-security-ws/data': mkdir /root/eufy-security-ws: read-only file system.

I found this command docker ps --quiet --all | xargs docker inspect --format '{{ .Id }}: ReadonlyRootfs={{ .HostConfig.ReadonlyRootfs }}'

All files show within eufy-security-ws show this: 6d762b1ada03519e679445833c0801e806dbe1b729c5173dbee8392031feadaa: ReadonlyRootfs=false
Indicating there are False which means the container’s root filesystem is writeable
https://docs.datadoghq.com/security_platform/default_rules/cis-docker-1.2.0-5.12/

**Comment by bropat** [comment]
@ahamster13  Did you solve it?
