### ISSUE TITLE
[Bug]: Binary sensors for Eufy Floodlight 2k (model T8422) not updating

### ISSUE THREAD

**Issue by broomeydj** [bropat/eufy-security-ws#114]
### Version

0.9.1

### Node version

14.17

### Operating System type

Linux

### Operating system version

Home Assistant OS

### Describe the bug

the new Eufy Floodlight 2k (fixed camera, not pan/tilt) does not update binary sensors.
Model number is T8422 (here is a link to the camera https://us.eufylife.com/products/t8424?ref=navimenu_4_img

switches work ok, just binary sensors not updating.
checking logs I do not see any references to the deviceID of the camera when I know the state changes.
Push notifications are enabled

### To reproduce

Push notifications turned on
make camera detect motion
eufy app reports motion via push notification
no logs in eufy-ws referencing the device
logbook and history in home assistant do not show any information for camera binary sensor state changes

**Comment by booz1974** [comment]
I have the same issue with the T8442, status changes are not updated in HA since ver. 0.9.1.
when i put back 0.8.4 from backup status changes are visible again

**Comment by blfriedman** [comment]
I also have this issue with the T8200X wired video doorbell

I am using:
Home Assistant Supervised version: core-2022.6.7 and
Eufy Security Add-On version: 0.9.2.

**Comment by eufysecurity** [comment]
I'm having the same issue with my T8420X floodlight camera. Nothing comes into the logs but the camera image. There isn't a set_event_for_entity for the floodlight.

**Comment by tvanbave** [comment]
Having same issue here with T8424 and T8114-Z. Sensors all show false and never change states. I have a T8400 that is updating binary sensors reliably. I do not see anything related to Eufy in the Home Assistant log.

**Comment by tvanbave** [comment]
Not sure if this is related to this issue but I did find a Eufy error in the log:

This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/coordinator.py:394
Integration: Eufy Security (documentation, issues)
First occurred: 6:38:48 PM (166 occurrences)
Last logged: 9:07:16 PM

eufy_security - Event received but device is missing, maybe not connected
