### ISSUE TITLE
[Feature request]: Support snooze

### ISSUE THREAD

**Issue by amosyuen** [bropat/eufy-security-ws#116]
### Describe the solution you'd like

In the app you can snooze a camera for some time. The camera keeps recording but doesn't send notifications during that time. This is useful to reduce notifications but keep recording events.

I would like to be able to see the current snooze duration as well as set the snooze duration using the API.

**Comment by amosyuen** [comment]
Dependent on https://github.com/bropat/eufy-security-client/issues/176 being done first

**Comment by amosyuen** [comment]
Hi @bropat, the snooze function works well, however, I noticed that there doesn't seem to be a way to get the snooze start time. When I call get_properties the properties related to snooze I get are
```js
properties: {
    ...
    snooze: true,
    snoozeTime: 3600
}
```

Without the start time, the client can not figure out when the snooze should end. Could you also return the snooze start time?

**Comment by bropat** [comment]
@amosyuen 

In the next version, `snoozeStartTime` will also be available.

**Comment by amosyuen** [comment]
Great, thank you!

**Comment by chrisf4lc0n** [comment]
> Hi @bropat, the snooze function works well, however, I noticed that there doesn't seem to be a way to get the snooze start time. When I call get_properties the properties related to snooze I get are
> 
> ```js
> properties: {
>     ...,
>     snooze: true,
>     snoozeTime: 3600
> }
> ```
> 
> Without the start time, the client can not figure out when the snooze should end. Could you also return the snooze start time?

I am sorry, but I seem to have a blonde moment here. How do I implement that?
