### ISSUE TITLE
HACS Custom Repo Issue

### ISSUE THREAD

**Issue by martoq** [bropat/eufy-security-ws#12]
**Describe the bug**  
When attempting to add this repository to the custom HACS repositories an error is produced.

**To Reproduce**  
1. Open HACS
2. Add Custom Repository
3. Use link: https://github.com/bropat/eufy-security-ws
4. Set category to integration
5. Add repository

**Expected behavior**  
An Error is produced:
Repostitory structure for 0.3.2 is not compliant

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/11802571/126362161-55a535cb-675e-4640-89d9-e6c980bbd909.png)

**Versions:**  
 - Client version: 0.3.2
 - Node version: na
 - Operating system: HASSPIAN

**Additional context**  
na

**Comment by bropat** [comment]
It isn't a HACS Repo.
