### ISSUE TITLE
[Feature request]: Doorbell Dual Package Detection

### ISSUE THREAD

**Issue by ejpenney** [bropat/eufy-security-ws#120]
### Ask your question

Hi,

Doorbell Dual introduced package detection.  Does this library support signaling when packages are detected/removed?

**Comment by bropat** [comment]
Not at the moment.

**Comment by ejpenney** [comment]
Would you like me to submit an enhancement request, or is this question ticket sufficient?

**Comment by bropat** [comment]
No not necessary.

Yesterday I already integrated everything necessary in the driver (`eufy-security-client`). In the next release, I will also implement everything necessary here.
