### ISSUE TITLE
[Question]: Detected Person Name Not working?

### ISSUE THREAD

**Issue by ejpenney** [bropat/eufy-security-ws#121]
### Ask your question

Is there a known issue with getting the name of a person currently detected (EG at my doorbell)?  I'm using this component downstream and the string seems to always be set to "Unknown" even when the app has identified a person.

This is with the Doorbell Dual (Wired).

Also worth noting, I've noticed that users who have had the device shared with them cannot see detection names nor even manage that training, but I'm running my automation using the primary device owner.

**Comment by bropat** [comment]
Try out latest version (`0.9.4`).

**Comment by ejpenney** [comment]
Thanks! Looks like it's working with 0.9.4!
