### ISSUE TITLE
[Bug]: streaming stops after working the first time

### ISSUE THREAD

**Issue by leonardpitzu** [bropat/eufy-security-ws#122]
### Version

0.9.3

### Node version

n.a.

### Operating System type

Docker

### Operating system version

Home Assistant OS 8.4

### Describe the bug

upon a new/fresh start of HA streaming works as expected - click the camera and the streaming starts.
after refreshing the browser and/or reopening the app streaming does not work any more - clicking the camera thumbnail opens an empty window.

### To reproduce

1. restart HA
2. click the camera -> streaming starts
3. exist the app or reload the page in the browser
4. click the camera -> streaming is not starting

### Screenshots & Logfiles

<img width="1027" alt="Screenshot 2022-07-28 at 11 37 59" src="https://user-images.githubusercontent.com/4321813/181476623-97cf1db4-d739-4ff4-91d6-04ca73780144.png">
<img width="1102" alt="Screenshot 2022-07-28 at 11 36 54" src="https://user-images.githubusercontent.com/4321813/181476644-8922da4b-0202-451b-b949-c6f621d9df35.png">
<img width="330" alt="Screenshot 2022-07-28 at 11 48 43" src="https://user-images.githubusercontent.com/4321813/181476654-13151739-1484-41dc-bdde-82b84ca6eca9.png">

### Additional context

i landed here due to this: https://github.com/fuatakgun/eufy_security/issues/403

**Comment by bropat** [comment]
missing debug logs
