### ISSUE TITLE
[Bug]: locked and lockStatus

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-ws#123]
### Ask your question

hey bropat,

I have two use cases for two different locks and receiving contradicting results, please help me to understand to find out correct attribute between `locked` and `lockStatus`. So, checking below information, do you think T8510 is giving wrong information?

Model: T8510 - https://github.com/fuatakgun/eufy_security/issues/349#issuecomment-1199374452
In Locked State;
- locked: false
- lockStatus: true <-------------this was supposed to be `number`
In UnLocked State;
- locked: false <-------------- this does not change at all
- lockStatus: false <-------------this was supposed to be `number`

While T8520 seems to be giving correct output.
Model: T8520 - https://github.com/fuatakgun/eufy_security/issues/402#issuecomment-1198608651
In Locked State;
- locked: true
- lockStatus: 4
In UnLocked State;
- locked: false 
- lockStatus: 3

**Comment by fuatakgun** [comment]
All clients are using 0.9.3 and latest schema version

**Comment by bropat** [comment]
This is already fixed in the current develop branch of `eufy-security-client`.

**Comment by fuatakgun** [comment]
Cool, let's wait for next version then

**Comment by bropat** [comment]
Fixed in release 0.9.4

**Comment by fuatakgun** [comment]
Thanks for update on this.

What would be the final state? Are these events (or state attributes) be in line with each other or should i prefer one over another?

If i should rephrase, should i use locked event or lockStatus event to present it to final user?

**Comment by bropat** [comment]
> If i should rephrase, should i use locked event or lockStatus event to present it to final user?

lockStatus can represent more than locked, but unfortunately I have not yet been able to decipher all the values.

I would provide both ;)

**Comment by fuatakgun** [comment]
Thanks for great work
