### ISSUE TITLE
[Bug]: No Alarm events received after ver 0.9.2

### ISSUE THREAD

**Issue by hipsi** [bropat/eufy-security-ws#126]
### Version

0.9.3

### Node version

16.15.1

### Operating System type

Docker

### Operating system version

20.10.3

### Describe the bug

Since updating from version 0.9.2 there no longer seems to be alarm events for the homebase.

### To reproduce

When running in Docker GUI, viewing the console, only change of guard mode is now published.  I have tried triggering alarm events both with and without the entry delay and they don't appear, however I'm definitely still getting the notifications from the app.

For now I have reverted to version 0.9.2 so that I can retain the alarm events, as I'm using this with fuatakgun's Home Assistant integration.

**Comment by bropat** [comment]
@hipsi

Have you already tried version 0.9.4?

**Comment by Palmke** [comment]
More specifically, which events did you expect to get?
There have been some changes you may need to adopt.

**Comment by hipsi** [comment]
Yes I tried 0.9.4, that's where I first noticed the problem.  I then went back to 0.9.3 and found the same problem, however in 0.9.2 it's working as I expect it.

The events I'm looking to get are change of guard mode (for when I arm and disarm) and alarm.  Really they're the only things.  

Going one step further from that though, I'd like to be able to get an event for a reset of the alarm (for example if I'm away from home and the alarm goes off, I'd like to reset, or cancel, the alarm from the app, without changing the guard mode).

**Comment by Palmke** [comment]
Recently, these events were added:
`alarm arm delay event` - For when a guard mode is activated with an alarm and  leave delay, contains the delay.
`alarm armed event` - For when the alarm's leave delay has ended and the alarm is armed.
`alarm delay event` - For when the alarm delay has started, contains the delay.

**Comment by bropat** [comment]
@hipsi Is the answer from @Palmke sufficient?

**Comment by hipsi** [comment]
@bropat I suppose that's a separate issue to the reason for this bug topic, but no not really 100% by the sounds of it. Am I correct that at this point there isn't an event to specify that an alarm has been reset, without changing the guard mode?

**Comment by Palmke** [comment]
I think that is `alarm armed event`. There is no loss of event data from the p2p data, it's just interpreted differently.

**Comment by hipsi** [comment]
That goes straight over my head sorry @Palmke.  I'm just using this with the fuatakgun/eufy_security integration in home assistant and the code is a bit beyond me.  I've opened an issue in his github in the hope he makes sense of it.

**Comment by bropat** [comment]
I agree with @Palmke, that's why I'm closing this Issue.
