### ISSUE TITLE
[Question]: how to authenticate with 2FA

### ISSUE THREAD

**Issue by j-fuentes** [bropat/eufy-security-ws#129]
### Ask your question

Hello, I am trying to use this, but I use 2FA. The client npm library has support for that but I don't see how to insert the verify code.

**Comment by bropat** [comment]
https://bropat.github.io/eufy-security-ws/#/api_cmds?id=set-2fa-verify-code

**Comment by j-fuentes** [comment]
Oh, I see.

I was trying to set the verify code hardcoded in config because I didn't read docs :)

Thanks.

**Comment by j-fuentes** [comment]
In case anyone ends up here:

I started the interactive client from the docker container with `docker exec <container name> node ./dist/bin/client.ts`.

Once I was there I got the prompt `eufy-security>`. There I executed `driver.set_verify_code 000000`, with the verification code instead of the `000000`. That sent the event and I received the ok response.

**Comment by sanderhoeppermans** [comment]
> 

Hi j-fuentes, 

I was just wondering, where have you copied the following code?

interface {
    messageId: string;
    command: "driver.set_verify_code";
    verifyCode: string;
}

I saw that bropat gave this answer, but I can't find the location to copy this code and link the 2FA. 

Thanks!
