### ISSUE TITLE
[Question]: How to change the docker port

### ISSUE THREAD

**Issue by hobooflove** [bropat/eufy-security-ws#131]
### Ask your question

Using the following docker-compose 
`version: '3.3'
services:
    eufy-security-ws:
        environment:
            - USERNAME=myuser
            - 'PASSWORD=mypass'
        volumes:
            - '/data:/data'
        ports:
            - '3002:3002'
        image: 'bropat/eufy-security-ws:latest'
`
I am able to start the container, but it shows it listening on port 3000, not 3002. Is there another place I need to change the port?
` INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
`

**Comment by bropat** [comment]
Change ports to `3002:3000` and it should work.
