### ISSUE TITLE
[Bug]: Motion Detection for T8420x does not work

### ISSUE THREAD

**Issue by eufysecurity** [bropat/eufy-security-ws#133]
### Version

0.9.4

### Node version

14.18.0

### Operating System type

Linux

### Operating system version

Linux 5 VMware

### Describe the bug

Motion Sensor is not working for T8420x. It does not pick up any motion. Motion and Person Motion.

### To reproduce

1. Create Motion on the floodlight cam.
2. get a notification on phone app
3. eufy security ws does not detect any motion

**Comment by bropat** [comment]
Hi,
without debug logs i can't help you.
In addition, there is already the pre-release version 1.0.0-rc.1, where you can check whether the problem persists or has already been fixed.

**Comment by bropat** [comment]
@eufysecurity 

Any update?

**Comment by eufysecurity** [comment]
I think line 920 in eufy-security-client/src/http/type.ts needs to be changed from: export const DeviceMotionDetectionIndoorSoloFloodProperty: PropertyMetadataBoolean = {

To:
export const DeviceMotionDetectionProperty: PropertyMetadataBoolean = {
