### ISSUE TITLE
[Feature request]: Talkback support

### ISSUE THREAD

**Issue by oischinger** [bropat/eufy-security-ws#134]
### Describe the solution you'd like

Hey there and thanks for this great project!
I noticed that talkback is already available in the library and wondered if it'll also be integrated in eufy-security-ws at some point. Is that possible?

**Comment by bropat** [comment]
Hi @oischinger,

talkback support is currently available in release candidate version `1.0.0-rc.1`. Published a few days ago.

**Comment by oischinger** [comment]
nice. thanks a lot!
