### ISSUE TITLE
[Bug]: P2PClientProtocol.lookup(): station: T8410XX - All address lookup tentatives failed. 

### ISSUE THREAD

**Issue by Ra7t0r** [bropat/eufy-security-ws#135]
### Version

0.9.4

### Node version

Home Assistant OS 9.4

### Operating System type

Linux

### Operating system version

Home Assistant OS 9.4

### Describe the bug

Hello.
I recently add a new eufy indoor cam 2k pan & tilt on my current setup on HA.
but I’m unable to control the device.
I’m getting this error

`2022-09-15 10:45:37.778  ERROR P2PClientProtocol.lookup(): station: T841..D - All address lookup tentatives failed. 
2022-09-15 10:45:37.780  INFO  Timeout connecting to station T841..D `

can you please assist?

### To reproduce

Log output

**Comment by bropat** [comment]
Please try the release candidate (`1.0.0-rc.1`).

**Comment by Palmke** [comment]
I'm running `develop` and I am constantly getting disconnects from all of my T8410 PT cams.
I assume this is on eufy's end. Kinda thought it was in the `develop` version, but seeing this issue confirms it's not this client.
In the official eufy app I see the "network not available" message several times throughout the day. Pulling down to refresh removes it and updates the thumbnails.

According to my log, it seems to 'round robin'? I only get the events over a period for a single device. This afternoon (GMT +2) it was device A which is in my garage. 
Thought it might have been the weather slowly destroying the thing, but now (21:21 hrs), device A is connected just fine and I get disconnect events for device B that's mounted indoor lol.

Maybe eufy is tweaking the amount of polls etc. to cut costs as AWS traffic costs money.

**Comment by bropat** [comment]
@Ra7t0r Any feedback?

**Comment by Jamie932** [comment]
Just a note from myself @bropat, I had the same issue - release candidate 1.0.0-rc.1 connected instantly. Appreciated.

**Comment by JuhaFIN1** [comment]
> Please try the release candidate (`1.0.0-rc.1`).

Please tell me how i can try this RC? Link for this to repos? I cannot find it anywhere.

**Comment by wolfjank** [comment]
> > Please try the release candidate (`1.0.0-rc.1`).
> 
> Please tell me how i can try this RC? Link for this to repos? I cannot find it anywhere.

Got the same question, how is it possible to install this rc version? 

I have been searching for a while now and didn't find the answer :-/

**Comment by Jamie932** [comment]
> > > Please try the release candidate (`1.0.0-rc.1`).
> > 
> > 
> > Please tell me how i can try this RC? Link for this to repos? I cannot find it anywhere.
> 
> Got the same question, how is it possible to install this rc version?
> 
> I have been searching for a while now and didn't find the answer :-/

In my docker-config file,

image: bropat/eufy-security-ws:1.0.0-rc.1

**Comment by wolfjank** [comment]
thank you for creating a new tag. I still got problems - one device is not working:
![image](https://user-images.githubusercontent.com/75538187/199426957-e3759cf3-b498-4084-8473-0ce200e16c41.png)

Do i have to wait further?

**Comment by Palmke** [comment]
I still think this **has nothing to do with this project**. Unless this client is capable of disurpting the communication between a camera and eufy's servers, this is a separate problem.

I assume if you open the eufy Security app, you often see a "network not available" message at the top. Sometimes the T8410 even shows up as offline.
I'm 99% sure this problem occurs due to eufy's planned integration with the new Homebase 3. I've also seen reports from people who claim eufy is throttling the live playback.

**Comment by wolfjank** [comment]
> I still think this **has nothing to do with this project**. Unless this client is capable of disurpting the communication between a camera and eufy's servers, this is a separate problem.
> 
> I assume if you open the eufy Security app, you often see a "network not available" message at the top. Sometimes the T8410 even shows up as offline. I'm 99% sure this problem occurs due to eufy's planned integration with the new Homebase 3. I've also seen reports from people who claim eufy is throttling the live playback.

Well, thank you for the reply. But is there anything, that i can do now? My T8410 is still not connecting.. :-(

![Unbenannt](https://user-images.githubusercontent.com/75538187/201160751-04583a13-e0a9-4775-a23a-9ae504bb8680.PNG)

**Comment by Waterchasd** [comment]
I just installed the add-on, version 1.3.0. I got the same error messages. The add-on did not stay on. Please help.

**Comment by fuatakgun** [comment]
I suggest you all to try it with a different machine to eliminate local network and configuration issues.

**Comment by guny74** [comment]
I have the same error using docker + homebace3 , but it tries to connect to 2 external IP adresse 18.xxx and 13.xxx.
Tried to user parameter STATION_IP_ADDRESSES with internal ip adress of my homebase3, but it also tried to connect to the external adresses.
