### ISSUE TITLE
[Bug]: Indoor chime control not working when used from Home Assistant integration

### ISSUE THREAD

**Issue by dfleischhacker** [bropat/eufy-security-ws#136]
### Version

1.0.0-rc.1

### Node version

16.17.0

### Operating System type

Linux

### Operating system version

Docker on Ubuntu 20.04.4 LTS

### Describe the bug

Using eufy-security-ws from the Home Assistant integration (https://github.com/fuatakgun/eufy_security) with the Eufy Doorbell (T8222) and the Wi-Fi Doorbell Chime a switch for controlling the indoor chime is provided. However, this switch does not work as expected, i.e. it does not sync on changes done via the Eufy app nor does its use change the actual indoor chime state. This issue was originally reported as https://github.com/fuatakgun/eufy_security/issues/164 for the integration and as https://github.com/bropat/eufy-security-ws/issues/71 for eufy-security-ws which was closed due to missing debug logs.

I created the attached logs by running the docker container (v 1.0.0-rc.1) with debug logs enabled. I redacted some information that I considered sensitive from the logs. In case additional information is needed, I can work on providing it.

### To reproduce

1. Install eufy_security integration on Home assistant and set up to use separate eufy-security-ws docker instance.
2. Try switching Indoor Chime switch on / off

### Screenshots & Logfiles

[chime-issue-redacted.log](https://github.com/bropat/eufy-security-ws/files/9624147/chime-issue-redacted.log)

First log entry after using the problematic switch was at timestamp 2022-09-22 08:48:30.459, last log entry belonging to that sequence at 2022-09-22 08:49:00.345.

**Comment by bropat** [comment]
@dfleischhacker 

To fix this issue i need access to the device. Could you share the device with me?

* patrick.broetto+eu1@gmail.com

Let me know.

**Comment by bropat** [comment]
stale
