### ISSUE TITLE
[Bug]: Camera Trying to Reach Docker-Internal IP Instead of Host IP

### ISSUE THREAD

**Issue by unarj** [bropat/eufy-security-ws#143]
### Version

1.0.2

### Node version

n/a

### Operating System type

Docker

### Operating system version

Docker version 20.10.21, build baeda1f

### Describe the bug

local Eufy cameras are trying to report to the internal docker IP and not the host IP.  seeing lots of traffic trying to go out the WAN as the network is only routable on the docker host, not the default gateway.

not sure how long this has been an issue, at least in 1.0.1 also, just started logging bogons.  attached 2 typical log entries.

### To reproduce

run docker bropat/eufy-security-ws:latest
watch outgoing WAN for unroutable IPs

### Screenshots & Logfiles

Mon Nov  7 08:19:20 2022 kern.warn kernel: [364670.439376] DROP_MAL: IN=br-lan OUT=eth0.2 MAC=8c:59:73:fe:49:16:8c:85:80:31:c0:b5:08:00 SRC=192.168.x.x DST=172.18.x.x LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=34824 DF PROTO=UDP SPT=12601 DPT=55154 LEN=32
Mon Nov  7 08:19:21 2022 kern.warn kernel: [364670.490099] DROP_MAL: IN=br-lan OUT=eth0.2 MAC=8c:59:73:fe:49:16:8c:85:80:31:c0:b5:08:00 SRC=192.168.x.x DST=172.18.x.x LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=34875 DF PROTO=UDP SPT=28730 DPT=55153 LEN=32

**Comment by bropat** [comment]
Use latest version with network mode `host`.

**Comment by unarj** [comment]
thanks for taking the time to look at this.  I assume you're aware of the security implications of running dockers with host networking mode?  is there something specific to the Eufy ecosystem that requires this level of exposure?
