### ISSUE TITLE
[Bug]: Docker running with error Cannot read properties of undefined (reading 'user_id')

### ISSUE THREAD

**Issue by lolouk44** [bropat/eufy-security-ws#146]
### Version

1.0.2

### Node version

16.18.0

### Operating System type

Docker

### Operating system version

Ubuntu 18.04.6 LTS

### Describe the bug

looping error in container: `TypeError  Cannot read properties of undefined (reading 'user_id')`

### To reproduce

Start the container

### Screenshots & Logfiles

```
2022-11-09 18:36:15.273  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-09 18:36:15.460  ERROR Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:289 login
    node_modules/eufy-security-client/src/http/api.ts:289:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:662 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:662:9
• server.ts:496 start
    src/lib/server.ts:496:9
• server.ts:66 <anonymous>
    src/bin/server.ts:66:9
2022-11-09 18:36:53.329  ERROR Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:289 login
    node_modules/eufy-security-client/src/http/api.ts:289:66
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• eufysecurity.ts:662 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:662:9
• message_handler.ts:80 handle
    src/lib/driver/message_handler.ts:80:21
• server.ts:126 receiveMessage
    src/lib/server.ts:126:21
2022-11-09 18:37:05.970  INFO  Client disconnected with ip: 192.168.9.23 port: 40300 code: 1000 reason: Normal Closure 
```

**Comment by rosselliot** [comment]
Also having this issue. Was running perfectly for months, but then stopped working today.

**Comment by dffitch** [comment]
Same issue, tried several different credentials to log in.

**Comment by lolouk44** [comment]
This fixed it for me

https://github.com/bropat/eufy-security-client/issues/242#issuecomment-1309377631

**Comment by TaZZaT** [comment]
@lolouk44 The fix didn't work for me.  Can you share exactly what you updated?  Thanks

**Comment by rosselliot** [comment]
Fixed it for me as well. I'm running the docker image, and just added the environment variable "TRUSTED_DEVICE_NAME" to my docker run command, i.e: 

`docker run -e TRUSTED_DEVICE_NAME=anyRandomString`

**Comment by lolouk44** [comment]
> "trustedDeviceName?": "newclient",

You have a question Mark in your variable name

**Comment by jimbo2jones** [comment]
Information came just in time for me to fix as well - added TRUSTED_DEVICE_NAME environmental variable
