### ISSUE TITLE
[Question]: Has ringing event been fixed?

### ISSUE THREAD

**Issue by FsxShader2012** [bropat/eufy-security-ws#148]
### Ask your question

I've stumbled upon this issue [Issue #86 eufy-security-client.](https://github.com/bropat/eufy-security-client/issues/86)
Has this been fixed yet? I'm using a T8213 (Dual) and not a T8210 but it should be the same fix right?
Sorry if I'm blind and didn't find this mentioned in any changelogs.

**Comment by bropat** [comment]
Yes, is fixed. 
Please also check that you are always on the latest version before opening an issue.
