### ISSUE TITLE
[Bug]: States not updating

### ISSUE THREAD

**Issue by circletile** [bropat/eufy-security-ws#151]
### Version

1.1.0

### Node version

Unknown (using fuatakgun/eufy_security)

### Operating System type

Linux

### Operating system version

Debian 11

### Describe the bug

Device states not updating after latest Eufy Homebase2 update while using fuatakgun/eufy_security (ref. https://github.com/fuatakgun/eufy_security/issues/519). Raising issue here at request of @fuatakgun.

### To reproduce

1. Install fuatakgun/eufy_security v2.8.1 on Home Assistastant Supervised VM.
2. Add Hommevase2 v3.2.3.2h (subsys 1.3.0.9).
3. Current date >= 2022-11-12.
4. Notice that device states to not update even after plugs-out troubleshooting.
5. Discover repeat 'Client disconnected with ip: 172.30.32.1 port: 49176 code: 1006 reason: Abnormal Closure' messages in fuatakgun/eufy_security logs.

### Screenshots & Logfiles

2022-11-13 18:14:26.737 INFO Eufy Security server listening on host 0.0.0.0, port 3000
2022-11-13 18:14:37.157 INFO Push notification connection successfully established
2022-11-13 18:14:37.226 INFO Connected to station T8010P123456789A on host 192.168.254.20 and port 13592
2022-11-13 20:36:36.206 INFO Client disconnected with ip: 172.30.32.1 port: 49176 code: 1006 reason: Abnormal Closure
2022-11-13 20:36:36.207 INFO Client disconnected with ip: 172.30.32.1 port: 42530 code: 1006 reason: Abnormal Closure
2022-11-13 20:36:36.208 INFO Client disconnected with ip: 172.30.32.1 port: 54944 code: 1006 reason: Abnormal Closure
2022-11-13 20:37:28.992 INFO Client disconnected with ip: 172.30.32.1 port: 52670 code: 1006 reason: Abnormal Closure
2022-11-13 20:44:46.187 INFO Client disconnected with ip: 172.30.32.1 port: 39712 code: 1006 reason: Abnormal Closure

**Comment by Snowrisk** [comment]
Slightly other message in log, but the same error (at same config like above):

>   data: undefined
> }
> 2022-11-14 12:25:04.921  INFO  Client disconnected with ip: 172.30.32.1 port: 32814 code: 1000 reason: Normal Closure 
> 2022-11-14 12:26:25.130  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:26:37.753  INFO  Client disconnected with ip: 172.30.32.1 port: 48654 code: 1000 reason: Normal Closure 
> 2022-11-14 12:27:57.951  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:28:10.591  INFO  Client disconnected with ip: 172.30.32.1 port: 45128 code: 1000 reason: Normal Closure 
> 2022-11-14 12:29:30.774  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:29:43.424  INFO  Client disconnected with ip: 172.30.32.1 port: 51704 code: 1000 reason: Normal Closure 
> 2022-11-14 12:31:03.605  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:31:16.256  INFO  Client disconnected with ip: 172.30.32.1 port: 59256 code: 1000 reason: Normal Closure 
> 2022-11-14 12:32:36.447  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:32:49.097  INFO  Client disconnected with ip: 172.30.32.1 port: 37564 code: 1000 reason: Normal Closure 
> 2022-11-14 12:34:09.315  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:34:21.922  INFO  Client disconnected with ip: 172.30.32.1 port: 44494 code: 1000 reason: Normal Closure 
> 2022-11-14 12:35:42.092  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:35:54.745  INFO  Client disconnected with ip: 172.30.32.1 port: 35088 code: 1000 reason: Normal Closure 
> 2022-11-14 12:37:14.931  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:37:27.578  INFO  Client disconnected with ip: 172.30.32.1 port: 33526 code: 1000 reason: Normal Closure 
> 2022-11-14 12:38:47.771  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:39:00.413  INFO  Client disconnected with ip: 172.30.32.1 port: 42032 code: 1000 reason: Normal Closure 
> 2022-11-14 12:40:20.609  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:40:33.254  INFO  Client disconnected with ip: 172.30.32.1 port: 52200 code: 1000 reason: Normal Closure 
> 2022-11-14 12:41:53.438  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:42:06.087  INFO  Client disconnected with ip: 172.30.32.1 port: 60844 code: 1000 reason: Normal Closure 
> 2022-11-14 12:43:26.260  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:43:38.907  INFO  Client disconnected with ip: 172.30.32.1 port: 54092 code: 1000 reason: Normal Closure 
> 2022-11-14 12:44:59.106  ERROR Response data is missing 
> {
>   code: 0,
>   msg: 'Succeed.',
>   data: undefined
> }
> 2022-11-14 12:45:11.743  INFO  Client disconnected with ip: 172.30.32.1 port: 35970 code: 1000 reason: Normal Closure 
> 2022-11-14 12:46:31.952  ERROR Response data is missing

**Comment by bropat** [comment]
Look [here](https://github.com/bropat/eufy-security-client/issues/242#issuecomment-1309368303)

**Comment by circletile** [comment]
Thanks. Not sure why @fuatakgun asked me to file a bug here when they're already aware of #242.

**Comment by circletile** [comment]
Duplicate of [#242](https://github.com/bropat/eufy-security-client/issues/242) in bropat/eufy-security-client.
