### ISSUE TITLE
[Question]: Host/Port is wrong in Home Assistant Container

### ISSUE THREAD

**Issue by SermonB** [bropat/eufy-security-ws#155]
### Ask your question

I installed the docker and when I check the logs i see
`INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
INFO  Push notification connection successfully established 
INFO  Connected to station T8010P2321502A3C on host`

So in Home Assistant I installed the Eufy security but when I want to add it to integrations I receive error that host or port is wrong?

Any idea what I did wrong?

**Comment by bropat** [comment]
I do not use HomeAssistant and the integration, so please check the respective HomeAssistant forum or integration repository and ask there.
