### ISSUE TITLE
[Question]: Thumbnails gone with Home Assistant and "bropat/eufy-security-ws" docker: 1.1.0

### ISSUE THREAD

**Issue by Beer17HWAM** [bropat/eufy-security-ws#161]
### Ask your question

Eufy Doorbell T8210
Home assistant docker: 2012-12.1
"bropat/eufy-security-ws" docker: 1.1.0
eufy-security add-on: 2.9.0
So all newest versions.

I always had Thumbnails. Now it's all gone. I strongly suspect that this is a change made by eufy in response to these criticisms https://www.zdnet.com/home-and-office/smart-home/eufy-responds-to-security-concerns/

Is it??

Does the Thumbnail option ever return??

**Comment by kevinfowler** [comment]
I too am having this issue.  It looks like the pictureUrl that is send over is in a non-standard format and no longer a jpg.  For example below is an example I am getting back when motion is detected from my T8210 doorbell camera:

{
  type: 'event',
  event: {
    source: 'device',
    event: 'property changed',
    serialNumber: 'T8210P202016046C',
    name: 'pictureUrl',
    value: 'https://security-app.eufylife.com/v1/s/g/cwaPeMHkl'
  }
}

If you download that URL you will see it it not a valid JPG.  They used to be standard JPG files.

**Comment by Beer17HWAM** [comment]
https://www.theverge.com/2022/12/19/23517250/anker-eufy-security-camera-answer

**Comment by bropat** [comment]
Due to changes from Eufy it is currently not possible to get the thumbnails. More about this [here](https://github.com/bropat/eufy-security-client/issues/273).
