### ISSUE TITLE
[Question]: How to take the livestream video/audio data and turn it into a RTSP feed?

### ISSUE THREAD

**Issue by ema-dev** [bropat/eufy-security-ws#163]
### Ask your question

I have an app that is initiating the livestream and listening for the livestream video and audio data. It then creates a TCP server and feeds the incoming livestream video and audio data to ffmpeg to then be streamed over RTSP using rtsp-simple-server. I can get the video to work, but can't for the life of me get the audio to work. I've tried creating two TCP sources (one for video and one for audio) and providing the sources to ffmpeg and I've tried one TCP source with both video and audio.

Here are some sample ffmpeg commands I've tried:

Single source
ffmpeg -f -i tcp://localhost:3331 -vcodec copy -acodec copy -rtsp_transport tcp -fflags +genpts -f rtsp rtsp://localhost:8554/eufy/stream

Double source
ffmpeg -f H264 -i tcp://localhost:3331 -f AAC -i tcp://localhost:3330 -map 0:v -map 1:a -vcodec copy -acodec copy -rtsp_transport tcp -fflags +genpts -f rtsp rtsp://localhost:8554/eufy/stream

ffmpeg -i tcp://localhost:3331 -i tcp://localhost:3330 -map 0:v -map 1:a -c:v libx264 -c:a aac -f rtsp rtsp://localhost:8554/eufy/stream

Any help or insight would be appreciated.

@fuatakgun I looked at your project for some direction, maybe you could steer me in the right direction.

**Comment by fuatakgun** [comment]
I remember that @bropat had already implemented this in iobroker component of eufy security. You can see how he managed to use two different inputs and generate one output

**Comment by ema-dev** [comment]
@fuatakgun Thank you for the information!

**Comment by fuatakgun** [comment]
By the way, are you able to manage to get benefit of go2rtc based ffmpeg streaming and just using tcp server inside python? @ema-dev

**Comment by ema-dev** [comment]
@fuatakgun This particular project I'm working on is written in Go, not Python.
