### ISSUE TITLE
[Bug]: Docker Container Running on Unraid Disconnecting from Station

### ISSUE THREAD

**Issue by Setesh82** [bropat/eufy-security-ws#164]
### Version

1.2.0

### Node version

16.18.1

### Operating System type

Docker

### Operating system version

Unraid 6.11.5 

### Describe the bug

I have had eufy-security-ws running on my Unraid server for a few months. Recently I ran into the issue caused by not defining TRUSTED_DEVICE_NAME. After resolving that. It is now constantly disconnecting from the Station.

HomeBase 2
System Version: 3.2.5.1h
Subsystem Version: 1.3.0.9

### To reproduce

1. Start Docker Container

### Screenshots & Logfiles

�[90m2022-12-15 21:22:25.612 �[39m�[1m�[94mINFO�[39m�[22m Eufy Security server listening on host 0.0.0.0, port 3000
�[90m2022-12-15 21:22:36.075 �[39m�[1m�[94mINFO�[39m�[22m Push notification connection successfully established
�[90m2022-12-15 21:22:36.099 �[39m�[1m�[94mINFO�[39m�[22m Connected to station T8010N1321211FD3 on host 192.168.1.32 and port 19938
�[90m2022-12-15 21:23:39.578 �[39m�[1m�[94mINFO�[39m�[22m Disconnected from station T8010N1321211FD3
�[90m2022-12-15 21:23:44.638 �[39m�[1m�[94mINFO�[39m�[22m Connected to station T8010N1321211FD3 on host 192.168.1.32 and port 19274
�[90m2022-12-15 21:24:48.119 �[39m�[1m�[94mINFO�[39m�[22m Disconnected from station T8010N1321211FD3
�[90m2022-12-15 21:24:53.179 �[39m�[1m�[94mINFO�[39m�[22m Connected to station T8010N1321211FD3 on host 192.168.1.32 and port 21374
�[90m2022-12-15 21:25:56.667 �[39m�[1m�[94mINFO�[39m�[22m Disconnected from station T8010N1321211FD3
�[90m2022-12-15 21:26:01.727 �[39m�[1m�[94mINFO�[39m�[22m Connected to station T8010N1321211FD3 on host 192.168.1.32 and port 21734
�[90m2022-12-15 21:27:05.221 �[39m�[1m�[94mINFO�[39m�[22m Disconnected from station T8010N1321211FD3
�[90m2022-12-15 21:27:05.221 �[39m�[1m�[94mINFO�[39m�[22m Disconnected from station T8010N1321211FD3
�[90m2022-12-15 21:27:10.281 �[39m�[1m�[94mINFO�[39m�[22m Connected to station T8010N1321211FD3 on host 192.168.1.32 and port 12989

**Comment by ds-sebastian** [comment]
@Setesh82 were you able to resolve? I'm also having this issue on unRAID docker

**Comment by Setesh82** [comment]
No,  I have up for now.  Found that I could do what I needed with an Alexa routine.

**Comment by bropat** [comment]
Fixed in version `1.3.1`.
