### ISSUE TITLE
[Bug]:   code: 'ERR_NON_2XX_3XX_RESPONSE when starting Server

### ISSUE THREAD

**Issue by dffitch** [bropat/eufy-security-ws#168]
### Version

1.2.0

### Node version

v16.18.1

### Operating System type

Docker

### Operating system version

Alpine Linux v3.16

### Describe the bug

Server fails to start and produces following output:

2022-12-21 16:28:27.199  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-12-21 16:28:27.600  ERROR EufyError - Code: undefined Message: undefined (HTTP Code: 403) - requestUrl: https://security-app-eu.eufylife.com/v1/passport/profile 
2022-12-21 16:28:27.604  ERROR Generic Error: 
 EufyError  Code: undefined Message: undefined (HTTP Code: 403)
details:
{
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1671640107216,
    socket: 1671640107217,
    lookup: 1671640107294,
    connect: 1671640107366,
    secureConnect: 1671640107522,
    upload: 1671640107522,
    response: 1671640107594,
    end: 1671640107595,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 77,
      tcp: 72,
      tls: 156,
      request: 0,
      firstByte: 72,
      download: 1,
      total: 379
    }
  }
}
error stack:
• index.js:118 <anonymous>
    node_modules/got/dist/source/as-promise/index.js:118:42

• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

### To reproduce

Staring/restarting docker container produces above error

### Additional context

Seems to be same issue with ioBroker.eusec  [https://github.com/bropat/ioBroker.eusec/issues/311](url)

**Comment by gpbenton** [comment]
I am also seeing this problem, after getting it to work for the first time earlier in the week.  It started at 2022-12-21 03:33:10.092.

**Comment by benjR** [comment]
Same issue for me with latest docker version

**Comment by Thimo188** [comment]
Same issue here!

**Comment by t-huebner** [comment]
Same here!

**Comment by ngbl-clv19** [comment]
Same here.

**Comment by eevlogiev** [comment]
Eufy has restricted access to their APIs. 

> Today, users can still log in to our [eufy.com 3](http://eufy.com/?utm_source=web&utm_medium=web_community&utm_content=3568215&utm_campagin=official&utm_term=) Web portal to view live streams of their cameras. However, users can no longer view live streams (or share active links to these live streams with others) outside of eufy’s secure Web portal. Anyone wishing to view these links must first log in to the [eufy.com 3](http://eufy.com/?utm_source=web&utm_medium=web_community&utm_content=3568215&utm_campagin=official&utm_term=) Web portal.

Here you can find the official statement: https://community.security.eufy.com/t/to-our-eufy-security-customers-and-partners/3568215

**Comment by EWK1** [comment]
Oof, so it will never work again?

**Comment by eimarfandino** [comment]
oh sad news then from Eufy. I would like to control EUFY to arm it and disarm it based on sensors. I am fine if the stream doesnt work. Hopefully the developers find a solution for this issue

**Comment by mattpurnell** [comment]
Ok, there goes any doorlock integration with Home Assistant.

**Comment by GMTA** [comment]
People, please read into other outstanding issues and PRs such as:
https://github.com/bropat/eufy-security-client/pull/282

They are working to move towards the V2 API.

**Comment by EWK1** [comment]
> People, please read other outstanding issues and PRs such as: [bropat/eufy-security-client#282](https://github.com/bropat/eufy-security-client/pull/282)
> 
> They are working to move towards the V2 API.

Wil that solve this problem?

**Comment by Jo-Jo1987** [comment]
> > People, please read other outstanding issues and PRs such as: [bropat/eufy-security-client#282](https://github.com/bropat/eufy-security-client/pull/282)
> > They are working to move towards the V2 API.
> 
> Wil that solve this problem?

would be a nice christmas present

**Comment by t-huebner** [comment]
Works like a charm now  - thank you!!!

**Comment by dffitch** [comment]
Thank you @bropat normal service resumed!  Merry Christmas.

**Comment by EWK1** [comment]
> Thank you @bropat normal service resumed! Merry Christmas.

Not here, what did you do?

**Comment by dffitch** [comment]
@EWK1 deleted old docker container and pulled latest. Started container
Set schema to 15.  Bingo!

**Comment by EWK1** [comment]
The update was pushed! Thanks for fixing it!

**Comment by Jo-Jo1987** [comment]
I am in am loop with the captcha once again after removing the 2fa and adding it once more to Home Assistant.

I cannot test it, and i have asked fuatakgun why this is happening all the time after 2FA is also one of the mandatory settings.

In the integrations menu i get issues with the Captcha, and get in the same time a e-mail with the one-time key which i cannot confirm or use to complete the request. 

My phone app works like a charm, logged out and logged in. But still same issues persisting
