### ISSUE TITLE
[Question]: Memory usage more than doubled since 0.9.4

### ISSUE THREAD

**Issue by GMTA** [bropat/eufy-security-ws#170]
### Ask your question

Previously on 0.9.4, I updated to version 1.3.0 and noticed my Kubernetes cluster was killing the container because it exceed the memory limit of 64MiB I gave it. Upping it to 128MiB was not enough; it seems to peak at about 150MiB after booting for a minute of 2 before finally connecting. Running on ARM64.

Is this behavior to be expected?

**Comment by yavinmaster** [comment]
I don't know what it was on previous versions, but my Pi is showing 108.5M on 1.3.0.  To be honest, I'm just glad the new version fixed Eufy's security changes.

**Comment by GMTA** [comment]
> To be honest, I'm just glad the new version fixed Eufy's security changes.

Absolutely, same here. But as a developer I'd like to know when my software would explode in terms of memory usage ;-) I've just performed some additional testing and it seems like a memory limit of 256MiB was not enough, so I've now set it to 512MiB which seems to work consistently.

**Comment by hanseandersson** [comment]
how do i change the memory limit? My just get "killed" before it finished,,

**Comment by tmbs1988** [comment]
> how do i change the memory limit? My just get "killed" before it finished,,

+1

**Comment by GMTA** [comment]
> how do i change the memory limit?

I'm using K8s pod resource limits. Please open your own issue if you have further questions.

**Comment by bropat** [comment]
I have removed a resource intensive dependency in version `1.3.1`. Please test and let me know.

**Comment by GMTA** [comment]
@bropat Thanks - I've tried `1.3.3` with the old memory limit of 128MiB and it works!
