### ISSUE TITLE
[Bug]: Can not start Addon - Killed

### ISSUE THREAD

**Issue by BalanceBreaker** [bropat/eufy-security-ws#173]
### Version

1.3.0

### Node version

-

### Operating System type

Linux

### Operating system version

Home Assistant OS

### Describe the bug

The Addon wont start anymore on my Raspberry Pi 3 B+.
The console only prints „Killed“ as described here [eufy-security-issue#584](https://github.com/fuatakgun/eufy_security/issues/584)

Thanks for the help!

### To reproduce

Start Addon

**Comment by mihaimihai18** [comment]
I am having the same problem for the past 5 days since I tried to install it first. I removed the addon, clean the configuration file, restart the HA but no change after reinstalling.

**Comment by jwalberg** [comment]
I'm having the same issue.  Here is data from my logs:
I updated the addon to 2.10 and it quit working. I uninstalled everything and reinstalled to see if that fixed it.

Now, when I try to add the integration, it tells me "Host/Port is wrong." and the addon stops. 

The addon log says "INFO  Authentication properties changed, invalidate saved cloud token. Killed"

The HA log says
```
> * eufy_security Exception in login : [Errno 104] Connection reset by peer - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/config_flow.py", line 199, in _test_credentials await eufy_ws.connect() File "/config/custom_components/eufy_security/websocket.py", line 41, in connect self.ws: aiohttp.ClientWebSocketResponse = await self.session.ws_connect( File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect resp = await self.request( File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request await resp.start(conn) File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start message, payload = await protocol.read() # type: ignore[union-attr] File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read await self._waiter aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

**Comment by Waterchasd** [comment]
I got the same error message:

INFO Authentication properties changed, invalidate saved cloud token. Killed.

I understand I need this add-on, RTSP server add-on, and the integration.This add-on is the only thing I've installed so far. I figured if this add-on does not work, the integration won't work either.

**Comment by hanseandersson** [comment]
Same issue here getting this from log..

Failed to to call /addons/3a26b21d_eufy_security_addon/stats -
7:57:39 PM – (ERROR) Home Assistant Supervisor
Timeout on /addons/3a26b21d_eufy_security_addon/stats request
7:57:38 PM – (ERROR) Home Assistant Supervisor

**Comment by jerkelens** [comment]
+1 'killed', no chance of getting it to work

**Comment by jwalberg** [comment]
This is what I'm seeing in my supervisor logs today:
22-12-29 08:01:28 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 138, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 204, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/addons.py", line 280, in options
    body = await api_validate(addon_schema, request, origin=[ATTR_OPTIONS])
  File "/usr/src/supervisor/supervisor/api/utils.py", line 149, in api_validate
    data: dict[str, Any] = await request.json(loads=json_loads)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_request.py", line 670, in json
    body = await self.text()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_request.py", line 664, in text
    bytes_body = await self.read()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_request.py", line 649, in read
    chunk = await self._payload.readany()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 391, in readany
    raise self._exception
ConnectionResetError: Connection lost

**Comment by fuatakgun** [comment]
bropat is not active HA user, so sharing logs from HA doesn't help at all.

You just need to share your  logs from add-on itself.

**Comment by hanseandersson** [comment]
The only log that i get from the addon is
"Killed"

**Comment by jwalberg** [comment]
I fired up the docker container on my desktop and got this in the log:
2022-12-29 08:46:40 2022-12-29 14:46:40.327  **ERROR Response data is missing** 
2022-12-29 08:46:40 {
2022-12-29 08:46:40   code: 0,
2022-12-29 08:46:40   msg: 'Succeed.',
2022-12-29 08:46:40   **data: undefined**
2022-12-29 08:46:40 }

**Comment by fuatakgun** [comment]
Are you sure you are using 1.3.0 version?

**Comment by jwalberg** [comment]
This came from the docker pull command found here: https://hub.docker.com/r/bropat/eufy-security-ws

I ran it a few minutes ago.

**Comment by fuatakgun** [comment]
And you set the trusted device name?

**Comment by jwalberg** [comment]
I left it the default of eufyclient.

**Comment by fuatakgun** [comment]
Set it and try again

**Comment by jwalberg** [comment]
I set a trusted device in the app, then put that in as an environmental variable in docker and it's connected right now.

**Comment by fuatakgun** [comment]
I highly doubt that, it is about home assistant and how it is managing the add-ons.

Normally, when you remove the instance from your machine, authentication credentials are also removed automatically.

Everyone, having this issue under home assistant, should remove the add-on, restart machine to be on the safe side and re install the add-on

**Comment by jwalberg** [comment]
I don't have it running in Home Assistant successfully. I connected successfully in Docker, which is what I was trying to eliminate as an issue.

Which version of the addon do you recommend now?

**Comment by mihaimihai18** [comment]
I removed it twice, restarted the machine (Rasberry Pie 3), reinstalled and nothing has changed. I have Trusted Device Name set as DEVICENAME, use the standard port 3000 or a different one, no change.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Burnerface** [comment]
I'm french, sorry for my english, I have RPI3b+,
Same error for several days.
After hours of research, I may have found the solution :
I uninstalled the addon and the integration, restarted, reinstalled the addon 1.3.0, I replaced in the configuration FR by fr, added Eufy in TRUSTED_DEVICE_NAME.
Restarted the HOMEBASE2 by the EUFY application on my phone
Installed the BETA 5.2.2 integration and everything works again the port was detected automatically
All entities have magically reappeared

**Comment by Waterchasd** [comment]
> I highly doubt that, it is about home assistant and how it is managing the add-ons.
> 
> Normally, when you remove the instance from your machine, authentication credentials are also removed automatically.
> 
> Everyone, having this issue under home assistant, should remove the add-on, restart machine to be on the safe side and re install the add-on

I've tried that several times. The add-on version is 1.3.0. I also created an account for the add-on. I tried different trusted device names, Nothing helped with solving the issue.

**Comment by fuatakgun** [comment]
so, putting aside what you all have already tried, this is the problem;
- 1.3.0 version requires old authentication information to be wiped.
- when you remove the add-on and add it back to home assistant, supervisor should wipe this persistent information.
- for some reason, this persistent information is not removed and when you want to start the add-on with 1.3.0, you are receiving this warning and add-on stops.

So, I am not sure if @bropat can help you on this, seems to be specific to home assistant.
You can definitely change your password and try again, this might remove the old information.

**Comment by mihaimihai18** [comment]
After the addon is removed then installed again the username and password fields are cleared, they don't contains your previous username and passwords used. I don't see anything in Log tab but killed word. I tried with two different accounts, the problem still exists.

**Comment by acla6525** [comment]
I have just installed this add on in supervisor and am getting the same issue, not sure what to put as the "Trusted Device" looking under the trusted devices section of the Eufy app it just says "iPhoneXX,X (This device)"

logs show this:
2022-12-30 11:56:36.094  INFO  Authentication properties changed, invalidate saved cloud token.

**Comment by jwalberg** [comment]
> bropat is not active HA user, so sharing logs from HA doesn't help at all.
> 
> You just need to share your logs from add-on itself.

Is there another log somewhere that doesn't show up in HA?

**Comment by acla6525** [comment]
The only log I get is “killed” the above shows up in HA, I am not sure if it’s the trusted device field I’m getting wrong or what

**Comment by jerkelens** [comment]
> so, putting aside what you all have already tried, this is the problem;
> 
>     * 1.3.0 version requires old authentication information to be wiped.
> 
>     * when you remove the add-on and add it back to home assistant, supervisor should wipe this persistent information.
> 
>     * for some reason, this persistent information is not removed and when you want to start the add-on with 1.3.0, you are receiving this warning and add-on stops.
> 
> 
> So, I am not sure if @bropat can help you on this, seems to be specific to home assistant. You can definitely change your password and try again, this might remove the old information.

I tried this, for me it leads to:
2022-12-31 11:31:41.824  INFO  Authentication properties changed, invalidate saved cloud token. 
Killed

**Comment by mihaimihai18** [comment]
Tne problem is that from the very first moment (when I just installed it for the first time, so no previous username and password were used) it didn’t worked and there is no previous version available to downgrade and test. I am curious if there are users that have no problems with this addon.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by hanseandersson** [comment]
I just changed fömy home assistant from rpi3 to odroid n2+ and just recovered my backup and everything works.
So i guess the problem is with the rpi3

**Comment by jerkelens** [comment]
Has anyone seen any development on this issue other than here? It is still broken for me no matter what I try.

**Comment by fuatakgun** [comment]
I advise you all to install the docker instance into another machine to eliminate the issue with home assistant.

**Comment by gourdo1** [comment]
So I had the same issue of the add-on refusing to start after re-installing 1.3.0. Turns out this probably isn’t a Eufy addon issue, but a Supervisor problem. A quick Google search for generic addon startup problems suggested that a full hardware shutdown (not HA restart) will re-initialize the Supervisor and get the addon working again: [https://community.home-assistant.io/t/addons-not-starting/450322](https://community.home-assistant.io/t/addons-not-starting/450322)

 This worked for me with Eufy Security.

**Comment by vlumikero** [comment]
Has anyone managed to solve this problem?

**Comment by fuatakgun** [comment]
> Has anyone managed to solve this problem?

You checked the previous comment???

**Comment by Ascathon** [comment]
I did. That did not solve it for me.

**Comment by vlumikero** [comment]
> > Has anyone managed to solve this problem?
> 
> You checked the previous comment???

Yes, did not work for me.

**Comment by fuatakgun** [comment]
And did you try setting it up in a different machine?

**Comment by mihaimihai18** [comment]
I tried this workaround but it doesn’t worked.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jonatanbkarlsson** [comment]
Seems to be an issue related to hardware (capacity). Get's killed on my RPI 3 since i run out of ram and works perfectly on a docker instance on my Mac.

**Comment by jwalberg** [comment]
> Seems to be an issue related to hardware (capacity). Get's killed on my RPI 3 since i run out of ram and works perfectly on a docker instance on my Mac.

I updated to an oDroid and my problem went away. I agree this seems to be an issue with RPI 3.

**Comment by mihaimihai18** [comment]
Awesome, another poor coded software...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bartgabriels** [comment]
Is this going to get fixed? Can we downgrade to a previous version?

**Comment by trushank** [comment]
I was having the same issue. Logs just said "Killed".
This week magically everything started working fine.

**Comment by fuatakgun** [comment]
Anyone having this issue under home assistant, try this;
- stop add-on if it is already running
- ssh to machine (not home assistant docker)
- `cd /usr/share/hassio/addons/data`
- look for a folder with eufy in it (mine: 3a26b21d_eufy_security_addon)
- `sudo rm -r 3a26b21d_eufy_security_addon`
- put your root password here and press enter
- this will delete saved config of installed add-on
- uninstall and install it again inside home assistant

**Comment by vlumikero** [comment]
> Anyone having this issue under home assistant, try this;
> 
> * stop add-on if it is already running
> * ssh to machine (not home assistant docker)
> * `cd /usr/share/hassio/addons/data`
> * look for a folder with eufy in it (mine: 3a26b21d_eufy_security_addon)
> * `sudo rm -r 3a26b21d_eufy_security_addon`
> * put your root password here and press enter
> * this will delete saved config of installed add-on
> * uninstall and install it again inside home assistant

Thanks @fuatakgun. It seems there's some slight step missing. I've managed to log on to the maching as per the instructions  here: https://developers.home-assistant.io/docs/operating-system/debugging/#generating-ssh-keys

But the prompt shows "#" and I can only start some docker instances. How can I get to a normal command prompt and execute the commands you suggest?

**Comment by vlumikero** [comment]
OK, here's how I interpreted the instructions. The steps did not solve the issue: 

1. SSH to host, then bash into the container hassio_supervisor:
```

docker exec -it hassio_supervisor /bin/bash
```
2. Removed the folder /data/addons/data/3a26b21d_eufy_security_addon.

3. Uninstalled, reinstalled.

**Comment by mihaimihai18** [comment]
Do you have instructions also for Raspberry Pie 3?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vlumikero** [comment]
As far as I can tell, the memory consumption of the docker container is not extraordinarily high, so I really don't see why it's getting killed.

**Comment by vlumikero** [comment]
Here's what I could find in systemctl:

```
Jan 19 21:05:18 homeassistant addon_3a26b21d_eufy_security_addon[478]: 2023-01-19 21:05:18.745  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
Jan 19 21:05:19 homeassistant addon_3a26b21d_eufy_security_addon[478]: 2023-01-19 21:05:19.497  ERROR Response data is missing 
Jan 19 21:05:19 homeassistant addon_3a26b21d_eufy_security_addon[478]: {
Jan 19 21:05:19 homeassistant addon_3a26b21d_eufy_security_addon[478]:   code: 0,
Jan 19 21:05:19 homeassistant addon_3a26b21d_eufy_security_addon[478]:   msg: 'Succeed.',
Jan 19 21:05:19 homeassistant addon_3a26b21d_eufy_security_addon[478]:   data: undefined
Jan 19 21:05:19 homeassistant addon_3a26b21d_eufy_security_addon[478]: }

**Comment by trushank** [comment]
@vlumikero I agree. Seems like the add on is taking up too much resources and gets killed by supervisor
![Screenshot_20230202-211322_Home Assistant](https://user-images.githubusercontent.com/10994654/216519307-a7db6053-fd4a-467e-99c0-926cf510533e.jpg)

**Comment by KavajNaruj** [comment]
@fuatakgun Any idea how to get it work on Raspberry Pi 3? Why it is so resource hungry? Do I have any hope? :) Or should i to say bye to this integration?

**Comment by thegreatspiros** [comment]
Same I've had this issue since December on a Raspberry Pi 3.. very frustrating to have no resolution or answers. Guess we say goodbye :(

**Comment by bropat** [comment]
I have removed a resource intensive dependency in version 1.3.1. Please test and let me know.

@fuatakgun 
In order for the local auto-discovery (udp broadcasting) of the respective station to work, it is recommended to operate the Docker container with the network mode host, otherwise the local discovery will not work and the cloud discovery must be resorted to.
You must adapt the [config.json](https://github.com/fuatakgun/eufy_security_addon/blob/main/config.json) file accordingly (`host_network: true`).

**Comment by mihaimihai18** [comment]
I still see version 1.3.0 and no update available, how can I get the new one?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by bropat** [comment]
@fuatakgun need to update the version of the addon [here](https://github.com/fuatakgun/eufy_security_addon/blob/main/config.json) before you see the new version.

**Comment by bropat** [comment]
@fuatakgun I would also add the parameter `timeout` with the value `30`.

**Comment by mihaimihai18** [comment]
Ok, thanks a lot

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fuatakgun** [comment]
@bropat i am a bit worried with host network as it would limit port assignments for users. Apparently port 3000 is popular among some other add-ons.

What would be the drawback of not having host network?

**Comment by bropat** [comment]
@fuatakgun the local network discovery will not work as already described above.
Regarding port setting a new configuration variable has been added. See [here](https://bropat.github.io/eufy-security-ws/#/docker).

For the best experience, I recommend the host network.

**Comment by mcsdodo** [comment]
> @fuatakgun need to update the version of the addon [here](https://github.com/fuatakgun/eufy_security_addon/blob/main/config.json) before you see the new version.

I see that you've reverted back to 1.3.0 here https://github.com/fuatakgun/eufy_security_addon/commit/75ebaf30f8b8c0895b345bf771b9f8bc79cdcc64

Do I need to change something in my local installation to update to 1.3.1? (HA, Supervisor, RPI3)

**Comment by fuatakgun** [comment]
Please follow @bropat s release version, it is better if he manages this.

On the other hand, @bropat do you have any intention to have own version of integration for home assistant?

**Comment by bropat** [comment]
@fuatakgun 

>On the other hand, @bropat do you have any intention to have own version of integration for home assistant?

No, I do not intend to.
Do you plan to give up your integration?

**Comment by PhilippEngler** [comment]
Regarding the memory consumption what I can say for my addon:
With the 32-bit version for node, my addon needs about 130 MB, with 64-bit node version it will be about 800 MB. This additional memory usage I have seen around the commits on mid of December (I believe, in my case the development-branch commit from Dec 12, 2022 was ok, the commit on Dec 20, 2022 results in the higher memory consumption).
Sorry, but I have had not the time to do any further testing.

**Comment by bropat** [comment]
Use the [official add-on](https://github.com/bropat/hassio-eufy-security-ws) and if you still get the same error (`Can not start Addon - Killed`), open an issue [there](https://github.com/bropat/hassio-eufy-security-ws/issues).

**Comment by awwbaker** [comment]
Wont't start. I am not technical:

eufy-security-ws
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-05-13 16:52:07.921  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-05-13 16:52:18.217  INFO  Connected to station T8420N6021202007 on host 192.168.4.48 and port 13024 
2023-05-13 16:52:18.225  INFO  Connected to station T8420N6021202375 on host 192.168.4.46 and port 13024 
2023-05-13 16:52:18.347  INFO  Push notification connection successfully established 
2023-05-13 17:09:24.894  ERROR Message error 
 LivestreamAlreadyRunningError  Livestream for device T8420N6021202007 is already running
error stack:
• message_handler.ts:231 handle
    usr/src/app/node_modules/eufy-security-ws/src/lib/device/message_handler.ts:231:31
• task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
• server.ts:125 receiveMessage
    usr/src/app/node_modules/eufy-security-ws/src/lib/server.ts:125:21
2023-05-13 17:11:08.517  ERROR Message error 
 LivestreamNotRunningError  Livestream for device T8420N6021202007 could not be stopped, because it is not running
error stack:
• message_handler.ts:240 handle
    usr/src/app/node_modules/eufy-security-ws/src/lib/device/message_handler.ts:240:31
• task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
• server.ts:125 receiveMessage
    usr/src/app/node_modules/eufy-security-ws/src/lib/server.ts:125:21
2023-05-13 17:11:11.149  ERROR Message error 
 LivestreamNotRunningError  Livestream for device T8420N6021202007 could not be stopped, because it is not running
error stack:
• message_handler.ts:240 handle
    usr/src/app/node_modules/eufy-security-ws/src/lib/device/message_handler.ts:240:31
• task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
• server.ts:125 receiveMessage
    usr/src/app/node_modules/eufy-security-ws/src/lib/server.ts:125:21
2023-05-13 17:12:03.412  INFO  Client disconnected with ip: 127.0.0.1 port: 39586 code: 1006 reason: Abnormal Closure 
2023-05-13 17:17:13.278  WARN Station T8420N6021202007 - AES key could not be decrypted! The entire stream is discarded. - Error: 
 Error  Error during decryption (probably incorrect key). Original error: Error: error:0200009F:rsa routines::pkcs decoding error
error stack:
• NodeRSA.js:301 module.exports.NodeRSA.$$decryptKey
    usr/src/app/node_modules/node-rsa/src/NodeRSA.js:301:19
• NodeRSA.js:249 module.exports.NodeRSA.decrypt
    usr/src/app/node_modules/node-rsa/src/NodeRSA.js:249:21
• session.ts:1331 handleDataBinaryAndVideo
    usr/src/app/node_modules/eufy-security-client/src/p2p/session.ts:1331:63
• session.ts:1266 handleData
    usr/src/app/node_modules/eufy-security-client/src/p2p/session.ts:1266:18
• session.ts:1157 parseDataMessage
    usr/src/app/node_modules/eufy-security-client/src/p2p/session.ts:1157:26
• session.ts:990 handleMsg
    usr/src/app/node_modules/eufy-security-client/src/p2p/session.ts:990:26
• session.ts:132 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/p2p/session.ts:132:56
• node:events:513 emit
    node:events:513:28
• node:dgram:933 onMessage
    node:dgram:933:8

**Comment by awwbaker** [comment]
Debug On:
        param_id: 1233335684,
        station_sn: 'T8420N6021202375',
        param_type: 1135,
        param_value: '0',
        create_time: 1670178867,
        update_time: 1683955966,
        status: 1
      },
      {
        param_id: 0,
        station_sn: 'T8420N6021202375',
        param_type: 1140,
        param_value: '1',
        create_time: 1683678920,
        update_time: 0,
        status: 1
      }
    ],
    devices: [
      {
        device_id: 1115336243,
        is_init_complete: false,
        device_sn: 'T8420N6021202375',
        device_name: 'Porch',
        device_model: 'T8420X',
        time_zone: 'EST5EDT,M3.2.0,M11.1.0',
        device_type: 3,
        device_channel: 0,
        station_sn: 'T8420N6021202375',
        schedule: '',
        schedulex: '',
        wifi_mac: '8C8580D10AEE',
        main_sw_version: '2.0.8.3',
        main_hw_version: 'P1',
        sec_sw_version: '2.0.4.8',
        sec_hw_version: 'P1',
        sector_id: 0,
        event_num: 0,
        wifi_ssid: 'Magnolia',
        ip_addr: '192.168.4.46',
        volume: 'Anker_XfaW8ZmsZ',
        main_sw_time: 1676442918,
        bind_time: 1670178866,
        bt_mac: '8C8580D0ED84',
        cover_path: 'T8420N6021202375~/media/mmcblk0p1/Camera00/20230120093315n.jpg',
        cover_time: 1674225186,
        local_ip: '',
        language: 'en',
        sku_number: '',
        lot_number: '',
        cpuid: '',
        create_time: 1636188157,
        update_time: 1683956005,
        status: 1
      }
    ],
    sensor_info: null,
    is_init_complete: false,
    virtual_version: '',
    house_id: '93110b6d35035d42304bc7a63379d55bc850bd0408a1'
  }
}
2023-05-13 20:15:03.699  DEBUG [Station.update] Normalized Properties 
{
  stationSN: 'T8420N6021202007',
  properties: {
    name: 'Garage',
    model: 'T8420X',
    serialNumber: 'T8420N6021202007',
    type: 3,
    hardwareVersion: 'P1',
    softwareVersion: '2.0.8.3',
    lanIpAddress: '192.168.4.48',
    macAddress: '8C8580D01737',
    timeFormat: 0,
    alarm: false,
    alarmType: 0,
    guardMode: 1,
    currentMode: 1
  }
}
2023-05-13 20:15:03.701  DEBUG [Station.update] Normalized Properties 
{
  stationSN: 'T8420N6021202375',
  properties: {
    name: 'Porch',
    model: 'T8420X',
    serialNumber: 'T8420N6021202375',
    type: 3,
    hardwareVersion: 'P1',
    softwareVersion: '2.0.8.3',
    lanIpAddress: '192.168.4.46',
    macAddress: '8C8580D10AEE',
    timeFormat: 0,
    alarm: false,
    alarmType: 0,
    guardMode: 1,
    currentMode: 1
  }
}
