### ISSUE TITLE
[Question]: No history on driver.get_history_events

### ISSUE THREAD

**Issue by maddogrvo** [bropat/eufy-security-ws#177]
### Ask your question

I am unable to retrieve any history events (or video / alarm), i am not sure if i am doing something wrong or if it is not implemented for Homebase 3 yet, my goal was to be able to download videos from the Homebase so that i don`t need a RTSP feed?

Device: Homebase3
Using latest docker container eufy-security-ws

I tried sending with only command and messageId, i also tried with all data entered but still no luck.

Is there something i`m doing wrong?
Log:
`2022-12-31 17:10:13.875  DEBUG [HTTPApi.request] Request:
{
  method: 'post',
  endpoint: 'v2/event/app/get_all_history_record',
  token: 'REDACTED',
  data: {
    device_sn: '',
    end_time: 1672506613,
    exclude_guest: false,
    house_id: 'HOUSEID_ALL_DEVICE',
    id: 0,
    id_type: 1,
    is_favorite: false,
    num: 1000,
    pullup: true,
    shared: true,
    start_time: 1199466613,
    station_sn: '',
    storage: 0,
    transaction: '1672506613875'
  }
}
2022-12-31 17:10:14.056  DEBUG [HTTPApi.request] Response:
{
  token: 'REDACTED',
  request: {
    method: 'post',
    endpoint: 'v2/event/app/get_all_history_record',
    data: {
      device_sn: '',
      end_time: 1672506613,
      exclude_guest: false,
      house_id: 'HOUSEID_ALL_DEVICE',
      id: 0,
      id_type: 1,
      is_favorite: false,
      num: 1000,
      pullup: true,
      shared: true,
      start_time: 1199466613,
      station_sn: '',
      storage: 0,
      transaction: '1672506613875'
    }
  },
  response: {
    code: 0,
    msg: 'Geslaagd.',
    data: '5SmOC1cZRAznkT7FUmTf/A==',
    outline: null
  }
}
2022-12-31 17:10:14.057  DEBUG [HTTPApi._getEvents] getHistoryEvents - Response:
{
  code: 0,
  msg: 'Geslaagd.',
  data: '5SmOC1cZRAznkT7FUmTf/A==',
  outline: null
}`

**Comment by fuatakgun** [comment]
can you check if there are any video events for this device in eufy app?

I have an indoor ptz camera without sd card, so it does not record any video events so there is nothing to show.

**Comment by PhilippEngler** [comment]
I have the same issue. It seems, that this is a HomeBase 3 specific issue. With the "older" bases it works.

**Comment by bropat** [comment]
Homebase3 get history events is not yet implemented.

With Homebase 3, the cloud is no longer involved. The events are requested directly from the Homebase via the P2P protocol.

**Comment by maddogrvo** [comment]
Thanks for the answer, guess we will wait then :)

**Comment by fuatakgun** [comment]
@bropat should we keep this open and ask someone share the device for you so you can implement this in the future?
