### ISSUE TITLE
[Feature request]: T8210 doorbell - Get RTSP Url to be able to start or get the video

### ISSUE THREAD

**Issue by phyllox** [bropat/eufy-security-ws#184]
### Describe the solution you'd like

Hello
The T8210 doorbell, unlike cameras, does not let us redirect the RTSP stream to a NAS and therefore we do not have access to the RTSP stream to start it, or even just view it in third-party software like directly with Euft app.

Is there a way to get the T8210 doorbell stream URL and start it through the plugin ? If not, is there just a way to retrieve this URL?
Thanks

**Comment by fuatakgun** [comment]
I can chime in as a consumer of this package. If RTSP is not supported by your device, you should either write your own library and generate RTSP address using P2P bytes or you can use home assistant and generate the URL there using custom integration. It is far from reliable but it is working to some extent
