### ISSUE TITLE
[Question]: Where did the Global Motion sensor go?

### ISSUE THREAD

**Issue by copekyle** [bropat/eufy-security-ws#187]
I'm using the 8201 doorbell. I'm using it in Home Assistant. The global motion binary sensor was the only sensor that showed motion in the past. At some point, there was an update to remove the global motion sensor. What sensor actually shows motion now?  I only have "Motion Detected" (binary sensor) and "Motion Detection"(switch). The Motion detected sensor just shows unavailable and the motion detection switch shows clear all the time.

**Comment by fuatakgun** [comment]
This is not correct place to ask this question. Use custom integration repository to ask this question
