### ISSUE TITLE
[Question]: Using "Last camera picture URL" in HA

### ISSUE THREAD

**Issue by copekyle** [bropat/eufy-security-ws#188]
I see the sensor exists as part of my 8201 doorbell. The data in the sensor is " T8201XXXX~/mnt/userdata/video/h264_video_20230116_181919n.jpg"

How would I use that data to show the image in a picture entity card on HA?

**Comment by fuatakgun** [comment]
This is not the correct place for this question, use custom integration repository. Before opening an issue, you have to check open ones there
