### ISSUE TITLE
[Question]: T8010/T8113 commands not found: device / station.trigger_alarm / reset_alarm 

### ISSUE THREAD

**Issue by lxrootard** [bropat/eufy-security-ws#191]
### Ask your question

hello

I'm working on the Jeedom Eufy plugin. Thank you for your great work, without this plugin wouldn't exist!
Are [these commands](https://bropat.github.io/eufy-security-ws/#/api_cmds?id=trigger-alarm-sound) still implemented on T8010/T8113?

- device.trigger_alarm
- device.reset_alarm
- station.trigger_alarm
- station.reset_alarm

`{"command": "device.trigger_alarm" ,"serialNumber": "T8113NXXXXXXXXX", "seconds":"1" }
{"type":"result","success":false,"errorCode":"unknown_command"}`

I've found no equivalent writable properties from the metadata
Thks

**Comment by bropat** [comment]
Yes, since schema version 3 as described in the documentation. I think you have not set the schema version as described in the [documentation](https://bropat.github.io/eufy-security-ws/#/api_introduction?id=schema-version).

**Comment by lxrootard** [comment]
hello @bropat 

There must be something else as I've already set the API version to the latest schema available:
`{"command": "set_api_schema", "schemaVersion": 16}"`
`{"type":"version","driverVersion":"2.4.0","serverVersion":"1.3.0","minSchemaVersion":0,"maxSchemaVersion":16}`

I've made many tests, the chosen guardMode does not matter
I've noticed that only `reset_alarm` works and only when the alarm rings.
in that case I get the following answer:
`{"type":"result","success":true,"result":{"async":true}}`

**Comment by bropat** [comment]
Check the logs for an error. If necessary, activate the debug mode.
