### ISSUE TITLE
[Bug]: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by RienduPre** [bropat/eufy-security-ws#194]
### Ask your question

I get this in my log:

`2023-02-05 11:36:27.270  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
(node:10) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 station talkback start listeners added to [EufySecurity]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 station talkback stop listeners added to [EufySecurity]. Use emitter.setMaxListeners() to increase limit
2023-02-05 11:36:37.639  INFO  Connected to station T8010P2322412672 on host 192.168.0.50 and port 22457 
2023-02-05 11:36:41.479  INFO  Push notification connection successfully established 
2023-02-05 11:37:41.100  INFO  Disconnected from station T8010P2322412672 `

The emitter.setMaxListeners seems to be to low. Is this an issue or not?

One minor point, My host and port are displayed incorrectly. It should be localhost and port 3200

-----------------------------
Eufy Security Add-on
Current version: 1.3.0

![Scherm­afbeelding 2023-02-05 om 12 59 29](https://user-images.githubusercontent.com/9009949/216817410-e22db90c-056d-492d-a64c-7b7e22d69380.png)

**Comment by RienduPre** [comment]
I think it's a bug .

Please comment on this issue.

Thanks,
Rien

**Comment by bropat** [comment]
This is a bug that will be fixed in the next version.

**Comment by RienduPre** [comment]
👍

**Comment by bropat** [comment]
Fixed in release `1.3.1` .
