### ISSUE TITLE
[Bug]: Disconnection and log

### ISSUE THREAD

**Issue by Kri72** [bropat/eufy-security-ws#196]
### Version

1.3.0 of Eudy Security Add - on (home assistant)

### Node version

Don't know where to find it.

### Operating System type

Other

### Operating system version

Home Assistant

### Describe the bug

Hello, I'm using the Eufy Security integration built by fuatakgun, in my Home Assistant running on a Raspberry Pi 4. However, I got the below issue, for which fuatakgun told me I could maybe get some help here : 
In the log of the Eufy Security Add-on, I get the following 
![image](https://user-images.githubusercontent.com/91803162/219879831-0b8b6ec0-aaee-4e91-a557-7e8c94bff4a5.png)

It seems there are numerous connection issue.. Any clue on where this could come from?

I'm not sure there is a direct link, but I then get in My Home Assistant log, numerous information (new URLs?), even, when the Eufy system is disarmed!?
![image](https://user-images.githubusercontent.com/91803162/219879417-9c328fab-bfc6-468b-af82-151711ba25ea.png)

Any clue on what I should do?
Thanks in advance,

### To reproduce

Log in Home Assistant

**Comment by bropat** [comment]
Try out last version `1.3.1`.

**Comment by Kri72** [comment]
Hello Bropat, 
How can I get the latest version?
Even if I put it as "Auto-update", i only have the 1.3.0
Thanks!

![image](https://user-images.githubusercontent.com/91803162/219966914-add6fad8-39c3-4400-829c-88e484f381ce.png)

**Comment by bropat** [comment]
@fuatakgun need to update the version of the addon [here](https://github.com/fuatakgun/eufy_security_addon/blob/main/config.json) before you see the new version.

**Comment by fuatakgun** [comment]
Will do it soon

**Comment by bropat** [comment]
@fuatakgun 

I have created an official [hassio-eufy-security-ws](https://github.com/bropat/hassio-eufy-security-ws) repository here, with the corresponding `eufy-security-ws` add-on. The add-on is already running in host mode and local discovery works as expected.
I have already tested it with your integration and it works perfectly.
Back then you asked me if I could manage it and now it's done 😉.

One thing I haven't implemented yet is the code signing with codenotary (I don't understand where I can register 😅).

**Comment by fuatakgun** [comment]
Thanks, shared with community

**Comment by RienduPre** [comment]
Cool.
I tried to use @bropat 's version, but I get errors during startup. (I raised an issues about it)
What do you mean by running in host mode?

Thanks,
Rien

**Comment by WillWNL** [comment]
> @fuatakgun
> 
> I have created an official [hassio-eufy-security-ws](https://github.com/bropat/hassio-eufy-security-ws) repository here, with the corresponding `eufy-security-ws` add-on. The add-on is already running in host mode and local discovery works as expected. I have already tested it with your integration and it works perfectly. Back then you asked me if I could manage it and now it's done 😉.
> 
> One thing I haven't implemented yet is the code signing with codenotary (I don't understand where I can register 😅).

Unfortunatly i couldnt get the add-on to work on a Rpi4 Hassio set-up.  Got the same errors starting the Add-on as @RienduPre.

**Comment by bropat** [comment]
Fixed in latest release.
