### ISSUE TITLE
[Bug]: Username for Eufy Cloud is missing!

### ISSUE THREAD

**Issue by sythesigh** [bropat/eufy-security-ws#197]
![6529CBBC-FA7F-4D5C-B1E2-D47A97D5A876](https://user-images.githubusercontent.com/107685183/220095560-c20a0963-b76f-4207-bef7-275a6ff6afa3.png)
### Version

1.3.1

### Node version

16.19.1

### Operating System type

Docker

### Operating system version

Debian bullseye

### Describe the bug

Hi, thanks for the integration, it usually works really well, but I’ve just updated my docker container, now all I get is this message in the logs:
Error: Username for Eufy Cloud is missing!

it looks like it’s just restarting the container over and over
please advise me to fix

thanks

### To reproduce

2. Click on '...'
 I do nothing

### Screenshots & Logfiles

![7A0A2EFA-7A69-4A8B-8A10-6807E03400B6](https://user-images.githubusercontent.com/107685183/220057109-46ac2b15-efd3-4cb9-9371-35037130f913.png)
![1588DC73-C5FB-470F-B619-AF806C4B13A7](https://user-images.githubusercontent.com/107685183/220058088-5cab8e19-c8c6-4334-b3bd-cc786146a678.jpeg)

### Additional context

Also posted here: (https://github.com/fuatakgun/eufy_security/issues/743#issue-1591375169)

**Comment by OXERY** [comment]
I got the same problem with the bropat/eufy-security-ws Docker container. I also tried it with the image pushed yesterday, but mine also says "Username for Eufy Cloud is missing".
Nevertheless thanks for the great work, bropat :-) Using your ioBroker addon since the beginning, but as I'm now switching to Home Assistant, I had to switch this too

**Comment by sythesigh** [comment]
> Could it be that, your password has some difficult characters, did you try too switch into simpler one just to validate?

I have a very simple username/password for this integration, which was working before the recent update, do you know of anything that was changed with that update, that would require an update of the username or password?

**Comment by bropat** [comment]
@sythesigh @OXERY 

Try version `1.3.3` and let me know.

**Comment by sythesigh** [comment]
> @sythesigh @OXERY
> 
> Try version `1.3.3` and let me know.

That’s fixed it for me, thank you and thank you for the quick response!
