### ISSUE TITLE
[Bug]: T8203 Image Preview Aspect Ratio all Wrong

### ISSUE THREAD

**Issue by ejpenney** [bropat/eufy-security-ws#208]
### Version

1.3.5

### Node version

18.15.0

### Operating System type

Other

### Operating system version

HAOS 10.1

### Describe the bug

This might be more of a feature request, but the aspect ratio of the camera snapshot for doorbell dual is wrong, I suspect the aspect ratio might be right for other devices.

The image looks fine when streaming but terrible when idle.  I retrieved the image directly from `api/camera_proxy/...` and have attached two examples (streaming vs idle).
![streaming](https://user-images.githubusercontent.com/21226768/235323857-dbb81595-786b-41aa-a8db-1bd2cffec651.png)
![idle](https://user-images.githubusercontent.com/21226768/235323858-5021cbce-e202-415a-a6b1-795b94a286a2.jpg)

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
This project does not interfere in any way with the aspect ratio of the image, so the cause must lie somewhere else.
