### ISSUE TITLE
[Question]: How to respond to Camera Person Detected Events?

### ISSUE THREAD

**Issue by lavoy** [bropat/eufy-security-ws#210]
### Ask your question

Hello, I'm getting iOS notifications from Eufy Security when a person is detected `[Camera Name]: Someone has been spotted.`

I don't see any state changed on the camera when this happens though. Is there an event or state I can watch to respond to the event, like sound an alarm indoors?

Thank you!

**Comment by jesse-kaufman** [comment]
There should be motion detected and/or person detected binary sensor entities in HA as part of your device (depending what's supported by your device). On one of my devices, it's a switch instead of binary sensor (which has been fixed in 1.6.3), so it could also be that on some devices.

**Comment by lavoy** [comment]
This is working now, thank you for the help!
