### ISSUE TITLE
[Question]: some commands not working as expected or not implemented?

### ISSUE THREAD

**Issue by lxrootard** [bropat/eufy-security-ws#212]
### Ask your question

Hi @bropat 

I'm the developper of [Jeedom's Eufy plugin](https://github.com/lxrootard/eufy) 
First a huge thanks for your work, without it we'd have no ways to interact with these devices.
The plugin is still in beta on the Jeedom market but the # of end-users is increasing everyday!
Also your new device picture property in v2.5.0 works like a charm! I'm integrating it in Jeedom on supported cams.

However reading your [APIDoc](https://bropat.github.io/eufy-security-ws/#/api_cmds) I've noticed several `eufy-security-ws` commands that either:  
* don't produce the expected output on the devices I've tested, eg:
`station.trigger_alarm` and `station.reset_alarm` that don't produce any sound as already reported [here](https://github.com/bropat/eufy-security-ws/issues/191)
* or return `unknown_command` error eg:
`station.get_commands, station.has_command, station.download_image`
`device.get_commands, device.has_command`

I can live with it but I'd like to understand if it's a doc issue or if I'm missing something here?
If needed I can send you my Postman logs in MP

Many thanks ;)

**Comment by bropat** [comment]
Hi @lxrootard,

thank you very much for the feedback. much appreciated :)

> don't produce the expected output on the devices I've tested, eg:
station.trigger_alarm and station.reset_alarm that don't produce any sound as already reported https://github.com/bropat/eufy-security-ws/issues/191

It is possible that Eufy has prevented this with new firmware.

> or return unknown_command error eg:
station.get_commands, station.has_command, station.download_image
device.get_commands, device.has_command

`unknown_command` means that you have most likely executed a command that was not known in the specified `schema_version`. Look [here](https://bropat.github.io/eufy-security-ws/#/api_introduction?id=schema-version).
The latest `schema_version` is `17`.

**Comment by lxrootard** [comment]
Thanks for your reply
I'm setting the schema version to the latest before REST calls.
So far I didn't use the `message_id` parameter. I've noticed the doc is not consistent: string or int?
Is it mandatory? what does the value `message_id=1` mean?

**Comment by fuatakgun** [comment]
message_id is used for internal tracking purposes, you send a message with id and you get a response with respective message id. You can send multiple messages and receive responses in different order and these IDs would help to track the answers internally

**Comment by duylong** [comment]
> Hi @lxrootard,
> 
> thank you very much for the feedback. much appreciated :)
> 
> > don't produce the expected output on the devices I've tested, eg:
> > station.trigger_alarm and station.reset_alarm that don't produce any sound as already reported #191
> 
> It is possible that Eufy has prevented this with new firmware.
> 

Same problem with my Home Base 2 version 3.2.9.5h (2023/06/29). Somebody has the same issue with this firmware ? Chime mode works.

**Comment by bropat** [comment]
I have successfully tested all the functionalities mentioned above. So the problem is not in this project. 
I am therefore closing this.
