### ISSUE TITLE
[Bug]: Docker image fails to start: syntax error in `run.sh` on line 62

### ISSUE THREAD

**Issue by gmta** [bropat/eufy-security-ws#216]
### Version

1.5.1

### Node version

unknown - cannot start

### Operating System type

Docker

### Operating system version

Debian 11

### Describe the bug

The Docker image fails to start and produces the following error:

```
/usr/src/app/run.sh: line 62: syntax error: unexpected "(" (expecting "fi")
```

### To reproduce

1. Start Docker image

**Comment by bropat** [comment]
Have you set the parameter `STATION_IP_ADDRESSES`? If so, with what value?

**Comment by GMTA** [comment]
No, I have not set `STATION_IP_ADDRESSES`. These are the env variables I did set:

```
ACCEPT_INVITATIONS=true
COUNTRY=NL
EVENT_DURATION_SECONDS=5
LANGUAGE=nl
P2P_CONNECTION_SETUP=0
PASSWORD=...
POLLING_INTERVAL_MINUTES=10
TRUSTED_DEVICE_NAME=...
USERNAME=...
```

**Comment by GMTA** [comment]
Looking at commit 9a00632c494984c789baa3dda7b07dc4a120d030, you added `bash` as a dependency without having changed anything else. Looks like the upstream image (`node:16-alpine`) was suddenly missing this dependency? The commit message doesn't really tell me why it was added.

At any rate, it seems to have an issue with the following syntax:

```bash
VALUE=(`command ...`)
```

Maybe the following could work?

```bash
VALUE=$(command ...)
```
