### ISSUE TITLE
[Question]: Basic or Digest

### ISSUE THREAD

**Issue by c0nt4x** [bropat/eufy-security-ws#218]
### Ask your question

Should I set my Eufy camera devices to Basic or Digest to be able to view the images/streams in HA? Digest is more secure from what I understand?

I'm asking because one of my Eufy RTSP cams works in HA when set to Digest but another one gets the below error but if I set that camera to Basic it works fine. 

<img width="228" alt="Screenshot 2023-05-16 at 21 37 52" src="https://github.com/bropat/eufy-security-ws/assets/70321584/d19d8a67-c5ac-4a8f-8369-54c4ac32c26a">

**Comment by bropat** [comment]
Unfortunately, I cannot help you with this.

**Comment by fuatakgun** [comment]
Basic works for me in home assistant but digest not.
