### ISSUE TITLE
[Question]: Entry sensors only work when push notification is on

### ISSUE THREAD

**Issue by RemcoveHA** [bropat/eufy-security-ws#220]
### Ask your question

Hello all, 

I have a question. After a few days of trail and error I managed to get the entry sensors working in HA. For some reason the open/close state was not updating in the app while I was able to change the alarm state for homebase to away or home etc..

It turned out that the entry sensors (open / close state) only update if you allow push-notifications in the Eufy Security app. Else Eufy won't send out the change of state.

Now its quite annoying to get notifications on my mobile all of the time when someone opens or closes a door or window so my question is, is it possible to have the open/close state in HA updated WITHOUT having 9000 push notifications on my phone. I thought about blocking the notifications on my phone from the app but that way I don't get a notification when the alarm is triggered and that's nor really helpful..

Kind regards,
Remco

**Comment by bropat** [comment]
Hi @RemcoveHA ,
from the attached logs in [this issue](https://github.com/bropat/eufy-security-ws/issues/219), I have seen that Eufy has now implemented a new P2P event for signalling the status of the sensor that did not exist earlier. This P2P event has now been implemented [here](https://github.com/bropat/eufy-security-client/commit/6afd69291e28accbb0ecbc29c0a750518333fead) and will be available in a next version.
I can't test it myself so please test it as soon as the new version is released and give feedback.

Thanks!

**Comment by RemcoveHA** [comment]
Hallo @bropat thanks for your reply. I will certainly give the update a try. Do you need more log files or any other info to help you make the update?

When do you expect it to be released?

Thanks!

**Comment by joostlitjens** [comment]
With my Android phone i can mute an specific notification. I did this with the doorbell movement notification.
It's a workaround but maybe it helps you
