### ISSUE TITLE
[Bug]: no problem in eufy-security-client after connect

### ISSUE THREAD

**Issue by maltic42** [bropat/eufy-security-ws#221]
### Version

1.5.2

### Node version

14.21.3

### Operating System type

Linux

### Operating system version

Linux raspberrypi 5.10.103-v7+

### Describe the bug

I installed the latest version in a different directory - using the same config.json as before (version from last year). When trying to connect with eufy-security-client to the running server I got no prompt. The server is logging a captcha, the client stops at 

root@raspberrypi:~# /usr/lib/node_modules/.bin/eufy-security-client
{
  type: 'version',
  driverVersion: '2.6.2',
  serverVersion: '1.5.2',
  minSchemaVersion: 0,
  maxSchemaVersion: 18
}
{
  type: 'result',
  success: true,
  messageId: 'api-schema-id',
  result: {}
}

When using the same config.json with an older version, everything works.

### To reproduce

Install latest version using npm, start the server start the client.

**Comment by maltic42** [comment]
The server responds with 

2023-05-20 17:12:47.165  DEBUG [ClientsController.addSocket] New client with ip: 127.0.0.1 port: 56918

**Comment by fuatakgun** [comment]
seems to be similar: https://github.com/bropat/eufy-security-ws/issues/211
