### ISSUE TITLE
[Bug]: container hangs when  issuing start_listening command

### ISSUE THREAD

**Issue by lxrootard** [bropat/eufy-security-ws#223]
### Version

1.5.2

### Node version

docker aarch64

### Operating System type

Linux

### Operating system version

Linux JeedomLuna 4.4.194 #101 SMP Wed Sep 14 01:49:23 UTC 2022 aarch64 GNU/Linux

### Describe the bug

Hi bropat

one of my Jeedom users experiences a container hang at startup in the start_listening command using my [test script](https://github.com/lxrootard/eufy/blob/master/resources/test_eufy.py)
Here's his output:
`

    root@JeedomLuna:/var/www/html/plugins/eufy/resources# python3 test_eufy.py

    *** Create connexion to 127.0.0.1:3000***
    {« type »:« version »,« driverVersion »:« 2.6.2 »,« serverVersion »:« 1.5.2 »,« minSchemaVersion »:0,« maxSchemaVersion »:18}

    *** Start listening ***
`
Here's the container log:
`root@JeedomLuna:/var/www/html/plugins/eufy/resources# docker logs --follow 2bb9f41c394a
2023-06-03 16:10:17.706 INFO Eufy Security server listening on host 0.0.0.0, port 3000
2023-06-03 16:14:30.730 INFO Client disconnected with ip: 172.17.0.1 port: 45706 code: 1006 reason: Abnormal Closure
2023-06-03 16:43:02.766 INFO Client disconnected with ip: 172.17.0.1 port: 46100 code: 1006 reason: Abnormal Closure
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use node --trace-warnings ... to show where the warning was created)
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 stations loaded listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
2023-06-03 16:51:14.209 INFO Client disconnected with ip: 127.0.0.1 port: 37730 code: 1000 reason: Normal Closure
2023-06-03 16:53:52.470 INFO Client disconnected with ip: 127.0.0.1 port: 37748 code: 1000 reason: Normal Closure`

and his image:
`REPOSITORY TAG IMAGE ID CREATED SIZE
bropat/eufy-security-ws latest 9e0b57a40c3f 2 weeks ago 150MB`

I've found [this similar issue MaxListenersExceededWarning](https://github.com/bropat/eufy-security-ws/issues/194) that you said you fixed in an earlier release. 
Any hints?
Thanks

### To reproduce

2. Click on '...'

**Comment by fuatakgun** [comment]
probably related: https://github.com/bropat/eufy-security-ws/issues/211
