### ISSUE TITLE
[Bug]: 'ERR_NON_2XX_3XX_RESPONSE' with T8200

### ISSUE THREAD

**Issue by Raarrrinator** [bropat/eufy-security-ws#225]
### Ask your question

Hi there,

Thanks for creating and maintaining this add-on!

I recently updated to your add-on in stead of the one from Fuatakgun. Since then my T8200 doorbell keeps giving errors in the log.

I've noticed that when movement is registered the image doesn't reload in HA. The strange thing is that movement on my T8410 ís registered and the image in HA does refresh. In order to get the latest image I first have to restart the add-on and afterwards reload Fuatakgun integration. But after new movement the same error occurs.

I tried completely removing the integration, add-on and HACS integration, rebooting and reinstalling (in reverse order) but the error remains.

---------------------------------------------------------------------------------------------------------------------------------------------
Add-on log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-06-15 13:02:32.263  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-06-15 13:02:33.680  INFO  Connected to station T8410P3121361F9F on host 192.168.3.208 and port 13791 
2023-06-15 13:02:42.452  INFO  Connected to station T8200N0021121A14 on host 192.168.3.113 and port 18828 
2023-06-15 13:02:45.622  INFO  Push notification connection successfully established 
2023-06-15 13:04:46.012  ERROR EufyError - Code: undefined Message: undefined (HTTP Code: 404) - requestUrl: https://security-app-eu.eufylife.com/v1/s/g/K_O42bs6L 
2023-06-15 13:04:46.015  ERROR Generic Error: 
 EufyError  Code: undefined Message: undefined (HTTP Code: 404)
details:
{
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1686834285856,
    socket: 1686834285857,
    lookup: 1686834285873,
    connect: 1686834285900,
    secureConnect: 1686834285973,
    upload: 1686834285974,
    response: 1686834286009,
    end: 1686834286009,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 16,
      tcp: 27,
      tls: 73,
      request: 1,
      firstByte: 35,
      download: 0,
      total: 153
    }
  }
}
error stack:
• index.js:118 <anonymous>
    usr/src/app/node_modules/got/dist/source/as-promise/index.js:118:42
• task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5

---------------------------------------------------------------------------------------------------------------------------------------------
Info:

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest
Eufy Security Add-on Version 1.5.2
Eufy Security Integration Version 6.3.0

If you need more, please let me know.

Thank you advance for your support!

---------------------------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/bropat/eufy-security-ws/assets/69963716/219154dd-a4ab-4779-91a0-c4b1d61604c9)

**Comment by googanhiem** [comment]
Also get this issue on T8010 homebase connected to multiple generations of camera (T8140, T8222, T8140, T8113). 

As its a 404, that might be something to do with connection issues, I'm going to try reducing the polling interval to every 15 minutes to see if that reduces it.

**Comment by Raarrrinator** [comment]
Bump! This bug is still there :(

**Comment by bropat** [comment]
The HTTP error 404 means not found. In this case, an attempt is being made to download the image from the URL received via the push notification.
Unfortunately, I cannot do anything about this.
