### ISSUE TITLE
[Question]: Is there a way to manually trigger recording on Eufy doorbell or floodlight (usually triggered by motion)?

### ISSUE THREAD

**Issue by magicmega** [bropat/eufy-security-ws#226]
### Ask your question

I have a front gate sensor that if opened, I want to trigger a recording event in my Eufy doorbell and floodlight cam 2 pro. These both trigger too late on motion so this would be to speed it up. I'm not recording to NAS so streaming won't be sufficient.

**Comment by bropat** [comment]
Not that I'm aware of.
