### ISSUE TITLE
Unable to arm or disarm T8410

### ISSUE THREAD

**Issue by renslinden** [bropat/eufy-security-ws#227]
### Version

1.5.2

### Node version

Docker

### Operating System type

Docker

### Operating system version

Docker

### Describe the bug

Since a few days I'am unable to arm and disarm the T8410 (Indoor Can Pan & Tilt) while other Eufy devices are working fine.

### To reproduce

1. Go to 'arm or disarm device' 
2. Nothing happens, see Docker warning below

### Screenshots & Logfiles

```
2023-06-20 10:37:23.503  WARN Station T8410P312******** - Command aged out from queue 
{
  commandType: 1224,
  nestedCommandType: undefined,
  channel: 255,
  ageing: 2733179,
  maxAgeing: 120000
}
```

**Comment by renslinden** [comment]
I did some restarts of the Docker container. Also restarted the Eufy integration in HA sometimes and suddenly it's back working again.

What am I doing wrong to get this warning / failure?

**Comment by bropat** [comment]
The cause is a connection problem with this unit.
