### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by sanderhoeppermans** [bropat/eufy-security-ws#228]
### Ask your question

After updating I added the bropat repo in HACS. Do you need to run the bropat repo (Eufy Security WS) and the Eufy security Add-on (fuatakgun) at the same time? I use two separate e-mails, both with admin rights. Now, I receive an error that the port is in use, both of these integrations use 3000. 

After restarting HA Eufy Security WS stops running automatically.

**Comment by fuatakgun** [comment]
No, just run the one from bropat

**Comment by sanderhoeppermans** [comment]
> No, just run the one from bropat

Thanks for all the replies Fuat, I appreciate! I run only the repo from bropat and still stuck on the add-on installation. The setup is loading for ages. After that, the integration shows 'Failed to Setup' (2FA is disabled). 

<img width="446" alt="Scherm­afbeelding 2023-06-20 om 20 50 36" src="https://github.com/bropat/eufy-security-ws/assets/121697071/eae4de9e-0c00-441c-9f8b-129a5bcf8833">

<img width="297" alt="Scherm­afbeelding 2023-06-20 om 20 53 21" src="https://github.com/bropat/eufy-security-ws/assets/121697071/965ef9a9-0fd2-43c6-8264-d69de9fbeba5">

**Comment by fuatakgun** [comment]
Integration is failing to run with 2fa or captcha challenges as of now, your's seems to be stuck at captcha.

**Comment by sanderhoeppermans** [comment]
> Integration is failing to run with 2fa or captcha challenges as of now, your's seems to be stuck at captcha.

Is there a way I can fix this myself, or is this a known issue and will get fixed later by properly a developer?

**Comment by sanderhoeppermans** [comment]
> > Integration is failing to run with 2fa or captcha challenges as of now, your's seems to be stuck at captcha.
> 
> Is there a way I can fix this myself, or is this a known issue and will get fixed later by properly a developer?

Hi Fuat, finally the problem is solved. The issue was the e-mail/login in the add-on. I changed it to a new one with all de admin rights. Thanks for all the help!!

**Comment by fuatakgun** [comment]
> > Integration is failing to run with 2fa or captcha challenges as of now, your's seems to be stuck at captcha.
> 
> Is there a way I can fix this myself, or is this a known issue and will get fixed later by properly a developer? 

Yes, known issue and raised it to bropat
