### ISSUE TITLE
[Feature request]: T8530 Smart Lock Support

### ISSUE THREAD

**Issue by AnthonyHuscher** [bropat/eufy-security-ws#233]
### Describe the solution you'd like

Would love a minimum lock/unlock and battery level support for the T8530.

**Comment by rlippmann** [comment]
+1. Camera support would be nice too.

I've tried to look at the device through the client, and it shows no commands supported.

I'd be glad to help with this, although I'm not really a javascript programmer.

**Comment by paulbaird87** [comment]
I have this installed also @bropat. How can I assist you? To start with I will definitely be jumping over here https://ko-fi.com/bropat and donating to your efforts.

**Comment by bropat** [comment]
The device must first be implemented in the driver project. See [here](https://github.com/bropat/eufy-security-client/issues/220).

The currently supported devices can be found [here](https://bropat.github.io/eufy-security-client/#/supported_devices).
