### ISSUE TITLE
[Feature request]: S220 Solo Support 

### ISSUE THREAD

**Issue by FeromonDE** [bropat/eufy-security-ws#234]
### Describe the solution you'd like

Please, can you add support for S220 Solo Cam.

Thanks.

**Comment by chris173972** [comment]
Please add this. I have recently been talking with Eufy and they are basically blaming this plugin for my battery dropping 80% in 1 night. 

![Screenshot_20230906-165602~2](https://github.com/bropat/eufy-security-ws/assets/5174337/31271ff0-ccd9-4141-9f21-1b13b3a4c769)

**Comment by vTomTom** [comment]
What is needed to support this device?

**Comment by tango13** [comment]
I second this. Is there any chance this cam could be supported? Thank you.

**Comment by tango13** [comment]
Thank you so much!

**Comment by kibohely** [comment]
Hi,
thank you for adding the support for this device!

I'm using [fuatakgun/eufy_security](https://github.com/fuatakgun/eufy_security) to integrate your module in Home Assistant, i'm under 1.7.1 for eufy_security_ws, but many entities don't seems to be available, especially for starting the live stream. Its all classified under "Diagnostic", and can't be toggled.

![Capture d’écran du 2023-11-06 17-14-12](https://github.com/bropat/eufy-security-ws/assets/5594559/5b53be67-402a-4b37-a633-554d65f5cb59)
"
![Capture d’écran du 2023-11-06 17-08-19](https://github.com/bropat/eufy-security-ws/assets/5594559/af456247-ba95-425e-bbc5-9682857543af)

![Capture d’écran du 2023-11-06 17-17-00](https://github.com/bropat/eufy-security-ws/assets/5594559/3230e566-1320-426f-886d-06a87e2512b5)

Do you think it's a issue from your side or from fuatakgun ?

**Comment by fuatakgun** [comment]
Anything about home assistant goes through my integration.

You just need to enable those entities.

**Comment by kibohely** [comment]
I can share the device if you want ?

**Comment by fuatakgun** [comment]
Please use my repository to create an issue but you must follow the bug template.
