### ISSUE TITLE
[Feature request]: T8502 (C210) Wi-Fi Lock Support

### ISSUE THREAD

**Issue by skp19** [bropat/eufy-security-ws#236]
### Describe the solution you'd like

Hoping to get simple lock/unlock and status support for the T8502.

**Comment by IlPicasso** [comment]
Behind this too! How can I help

**Comment by aceonce** [comment]
Any ETA when T8502 will be supported? Thanks

**Comment by ujwalkoirala0** [comment]
+1, any updates on when T8506 will be supported? Thanks!
