### ISSUE TITLE
[Bug]: Eufy Door Lock not working even after assigning the station manually

### ISSUE THREAD

**Issue by marcelrees** [bropat/eufy-security-ws#238]
### Version

1.5.2-1

### Node version

?

### Operating System type

Linux

### Operating system version

Proxmox 7.4-3

### Describe the bug

I recently migrated from the old Eufy addon to this one after the last update made it stop working. Everything was working except for my T8520 lock, I found the other bug reports for this issue and set a static IP and added the following code:
stations:
  - serial_number: T8520Q##########
    ip_address: 192.168.1.##
Yet my lock is still not responding to lock/unlock commands, nor is it even showing an accurate state. It is all but dead.
The logs aren't even showing any errors... I'm at a dead end and getting desperate!

### To reproduce

It just doesn't work at all

**Comment by marcelrees** [comment]
@bropat there is no error, so I'm not sure how to get debug logs

**Comment by bropat** [comment]
Try latest version.
