### ISSUE TITLE
[Bug]: Installed the addon yesterday, today 2 ghost rings

### ISSUE THREAD

**Issue by uneatensoup** [bropat/eufy-security-ws#239]
### Version

1.5.2-1

### Node version

?

### Operating System type

Linux

### Operating system version
Hassio 
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3

### Describe the bug

Device: 
Eufy doorbel 2k (T8210) 
Firmware version: 5.8.1.2

what’s happening: since I installed this addon yesterday my doorbel has rang 2 times randomly this morning. This also registered as an ring event in the Eufy app.

Maybe this is an issue with the doorbell itself but it did nit happen before I installed this addon.

### To reproduce

Probably not possible it happens at random.

### Screenshots & Logfiles

Will add later. Need to sanitize them first.

**Comment by bropat** [comment]
As far as I know, there is no way to programmatically trigger the ringing of the bell. At least my projects have no support for it ;)
