### ISSUE TITLE
[Bug]: getting mfa code but no option to fill it in

### ISSUE THREAD

**Issue by TheRecovery007** [bropat/eufy-security-ws#240]
### Version

1.5.2-1

### Node version

.

### Operating System type

Linux

### Operating system version

debian 12

### Describe the bug

I get the mfa code from eufy in an email but i cannot find any option to put it in.

### To reproduce

restart addon 

log shows:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-07-27 06:33:43.942  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-07-27 06:33:44.445  INFO  Requested verification code for 2FA 

i get the mfa email from eufy

**Comment by RichardKeschinger** [comment]
what is the work around?
