### ISSUE TITLE
[Feature request]: Capture Door Lock User

### ISSUE THREAD

**Issue by freddydopfel** [bropat/eufy-security-ws#243]
### Capture Door Lock User

It would be wonderful if you could capture which users locked/unlocked a door (or if it was unlocked manually). This would be really powerful when mixed with the HomeAssistant addon.

For example:

When the door is unlocked by me, turn off cameras and set routines based on my preferences
When the door is unlocked by houseguest, leave cameras on
When door is unlocked by UPS / Amazon, take photos and send notification to phone, use speaker to give directions to just close the door behind them.
When the door is locked by "one tap", arm security system and turn on cameras

**Comment by InstigatorX** [comment]
Would love to see this added for exactly the reasons you suggested. I previously (w/ zwave lock) disarmed my alarm if a legit user unlocked the door with a code vs breaking window and reaching it to open the lock manually.

**Comment by InstigatorX** [comment]
Some additional info...looks like NICKNAME is captured. Can this be exposed so Home Assistant integration can take advantage of it?

2023-11-01 13:37:02.896  DEBUG [MqttClient.<anonymous>] Received a smart lock message over MQTT 
{
  message: {
    eventType: 259,
    userId: 'e1e41b56-0a8b-4c3c-bd47-d4909ffxxxxx',
    data: {
      timestamp: '1698845822857',
      uuid: '6203828c-a4e7-4ffa-ba1a-d7503c8xxxxx',
      data: {
        stationSn: 'T8520Q25231xxxxx',
        deviceSn: 'T8520Q25231xxxxx',
        eventType: 259,
        eventTime: '1698845822503',
        shortUserId: '0001',
        nickName: 'Izzy',
        userId: 'e1e41b56-0a8b-4c3c-bd47-d4909ffxxxxx',
        deviceName: 'Back Door'
      }
    }
  }
}
