### ISSUE TITLE
[Bug]: Eufy security error on startup after new release

### ISSUE THREAD

**Issue by EDelsman** [bropat/eufy-security-ws#244]
### Version

1.6.0

### Node version

?

### Operating System type

Other

### Operating system version

HAOS 10.3

### Describe the bug

A persistent notification saying: Error: <Task finished name='Task-5938' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>

### To reproduce

Happened on startup of the Home Assistant addon directly after updating to 1.6.0

### Screenshots & Logfiles

The logs show:
2023-08-02 08:15:10.788  ERROR Data decryption error, invalidating session data and reconnecting... 
 Error  error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
details:
{
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}
error stack:
• cipher:193 final
    node:internal/crypto/cipher:193:29
• utils.ts:190 decryptAPIData
    usr/src/app/node_modules/eufy-security-client/src/http/utils.ts:190:16
• api.ts:1072 decryptAPIData
    usr/src/app/node_modules/eufy-security-client/src/http/api.ts:1072:47
• api.ts:1270 getPassportProfile
    usr/src/app/node_modules/eufy-security-client/src/http/api.ts:1270:46
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• api.ts:384 login
    usr/src/app/node_modules/eufy-security-client/src/http/api.ts:384:33
• eufysecurity.ts:756 connect
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:756:9
• server.ts:495 start
    usr/src/app/node_modules/eufy-security-ws/src/lib/server.ts:495:9
• server.ts:66 <anonymous>
    usr/src/app/node_modules/eufy-security-ws/src/bin/server.ts:66:9

**Comment by bajwamar** [comment]
the addon after the update is has made all the devices unresponsive.
I have restarted the addon and HA multiple times but this does not resolve the issue

**Comment by relighted** [comment]
Addon 1.6.0, ha 2023.08.01
Same error after about 24h, HA restart enables and clears it. But issue returns after a day or so.

**Comment by muckie89** [comment]
same here... not updating picture entities and producing this error. reloading integration helps, but only a certain amount of time. some kills the integration.

**Comment by mattheeussen** [comment]
Worked well for one week. Now i get:
Error: <Task finished name='Task-2444' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>
Also after restart.

**Comment by fuatakgun** [comment]
> Worked well for one week. Now i get:
> Error: <Task finished name='Task-2444' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>
> Also after restart.
> Version 1.6.2
> Dont know what changed

This is related to home assistant not here.

**Comment by dernorberto** [comment]
I had the same issue and it seems resolved since a recent HA release.
I was not able to control the alarm state before, it works again now
