### ISSUE TITLE
[Question]: image file image:event_image location

### ISSUE THREAD

**Issue by TStko93** [bropat/eufy-security-ws#247]
### Ask your question

I'm trying to find this file on home assistant and turn it into a jpg so I can get this file to show on my android notifications for tv. The image file keeps updating but because it's not a camera image I can't get a snapshot to save as a jpeg or png. The url uses a temporary token. Looking for anyway to either get to the image or save the image as a file. Thanks in advance

**Comment by fuatakgun** [comment]
Technically, you can save the image into a file and use it in your notifications.

But i will (very) soon convert it into a camera so it would be easy to use it automations.

While bropat can expose the url, it won't be useful as the content is encrypted and requires difficult decryption methods (handled thanks to bropat through eufy-security-client), so it won't be useful for your case.

**Comment by TStko93** [comment]
That's what I've been struggling with locating the file to save as an image. Since it's not a camera entity it won't let me snapshot save it. I've been going through all my files trying ro find it with no success. If you can direct me to where it's at that woukd be great.
