### ISSUE TITLE
[Bug]: AFter Updating 1.6.3->  P2P streaming doesnt work on floodflight

### ISSUE THREAD

**Issue by kvanbiesen** [bropat/eufy-security-ws#253]
### Version

1.6.3

### Node version

latest

### Operating System type

Linux

### Operating system version

HASSOS

### Describe the bug

When startting the P2P stream, the stream neve starts and keeps hanging indefendly on PREPARING. 
Seems like command is sended to the camera but camera never actually starts....

```
data: <Buffer d1 00 00 0b 58 5a 59 48 a4 06 80 01 00 00 01 00 00 01 00 00 18 68 64 03 7e f4 47 28 67 d0 2d 0a 83 14 62 9e 71 67 b4 74 b2 b3 4d 09 be 44 11 be cb 96 ... 354 more bytes>,
    customData: {
      command: {
        name: 'deviceStartLivestream',
        value: 0
      }
    }
  },
  resultCodeName: 'ERROR_NULL_POINT',
  resultCode: -100
}
2023-08-22 13:13:36.381  DEBUG [Station.onCommandResponse] Got p2p command response 
{
  station: 'T8424N1021291061',
  commandType: 1000,
  channel: 0,
  returnCodeName: 'ERROR_NULL_POINT',
  returnCode: -100,
  customData: {
    command: {
      name: 'deviceStartLivestream',
      value: 0
    }
  }
}
2023-08-22 13:13:36.382  DEBUG [P2PClientProtocol.handleMsg] Station T8424N1021291061 - DATA DATA - Received expected sequence (expectedSeqNo: 12 seqNo: 11 queuedData.size: 0) 
2023-08-22 13:13:41.382  INFO  [Timeout._onTimeout] Stopping the station stream for the device T8424N1021291061, because we haven't received any data for 5000 seconds 
2023-08-22 13:13:41.383  DEBUG [P2PClientProtocol._sendCommand] Sending p2p command... 
{
  station: 'T8424N1021291061',
  sequence: 12,
  commandType: 1004,
  channel: 0,
  retries: 0,
  messageStatesSize: 1
}
2023-08-22 13:13:41.395  DEBUG [P2PClientProtocol.handleMsg] Station T8424N1021291061 - ACK DATA - received from host 192.168.20.212:10426 for sequence 12 
2023-08-22 13:13:41.406  DEBUG [P2PClientProtocol.handleMsg] Station T8424N1021291061 - DATA DATA - received from host 192.168.20.212:10426 - Processing sequence 12... 
2023-08-22 13:13:41.406  DEBUG [P2PClientProtocol.parseDataMessage] Station T8424N1021291061 - Received data 
{
  seqNo: 12,
  header: {
    commandId: 1004,
    bytesToRead: 132,
    channel: 0,
    signCode: 1,
    type: 1
  },
  bytesRead: 132,
  bytesToRead: 132,
  firstPartMessage: true,
  messageSize: 148
}
2023-08-22 13:13:41.407  DEBUG [P2PClientProtocol.handleData] Station T8424N1021291061 - Received data 
{
  commandIdName: 'CMD_STOP_REALTIME_MEDIA',
  commandId: 1004,
  resultCodeName: 'ERROR_PPCS_SUCCESSFUL',
  resultCode: 0,
  message: '\x00\x00\x04\x00\x00\x04\x00\x00...\n' +
    '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
  data: '0000000000000400000400002e2e2e0a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  seqNumber: 13,
  energySavingDeviceP2PDataSeqNumber: 0,
  offsetDataSeqNumber: 0
}
2023-08-22 13:13:41.407  DEBUG [P2PClientProtocol.handleData] Station T8424N1021291061 - Result data for command received 
{
  message: {
    sequence: 12,
    commandType: 1004,
    nestedCommandType: undefined,
    channel: 0,
    acknowledged: true,
    retries: 0,
    returnCode: -133,
    data: <Buffer d1 00 00 0c 58 5a 59 48 ec 03 10 00 00 00 01 00 00 01 00 00 87 47 44 a1 ac be 2a b3 5d 70 29 f1 a1 0e 26 55>,
    customData: {
      command: {
        name: 'deviceStopLivestream'
      }
    }
  },
  resultCodeName: 'ERROR_PPCS_SUCCESSFUL',
  resultCode: 0
}
2023-08-22 13:13:41.408  DEBUG [Station.onCommandResponse] Got p2p command response 
{
  station: 'T8424N1021291061',
  commandType: 1004,
  channel: 0,
  returnCodeName: 'ERROR_PPCS_SUCCESSFUL',
  returnCode: 0,
  customData: {
    command: {
      name: 'deviceStopLivestream'
    }
  }
}
2023-08-22 13:13:41.409  DEBUG [P2PClientProtocol.handleMsg] Station T8424N1021291061 - DATA DATA - Received expected sequence (expectedSeqNo: 13 seqNo: 12 queuedData.size: 0) 
```

### To reproduce

Start Stream on floodllight tru integration. NOthing happens

In App it still works fine.

**Comment by bropat** [comment]
To fix this problem, I need access to your device. So I ask you to share the device with me (with admin rights):

* patrick.broetto+eu1@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

**Comment by bropat** [comment]
This device has not yet been tested by me. I will now check all functionalities and correct them if necessary.
The command to start the livestream is already incorrect.

**Comment by kvanbiesen** [comment]
Yeah, untill 1.6.x it has been working.
Someone on the fuatakgun repo also said that guard mode changing didnt work anymore. i've tested it also and indeed its not working. You can use mine to test it.

Please use the Home / Disarmed method if you wanna test tho, dont want the neighbours to panic when the alarm goes of lol (so not arm it :p) :D

**Comment by bropat** [comment]
The problem lies in the p2p encryption. Some commands are still sent unencrypted with this device. e.g. "start livestream".

**Comment by kvanbiesen** [comment]
Then propably the change guard mode also same issue. Also turning on the
light doesn't work either.

**Comment by bropat** [comment]
Disabling p2p encryption for this unit fixes all problems with the P2P commands (incl. start livestream as guard mode).

**Comment by kvanbiesen** [comment]
Can you disable per decice p2p or is that something your end and wait for upgrade?

1.6.2 work withouth issues so far btw.

**Comment by bropat** [comment]
What is not yet clear to me is where I get the information whether a device supports p2p encryption or not.
In the meantime, I will deactivate it again for all devices except Homebase devices.

**Comment by kvanbiesen** [comment]
All devices I think that get an update now....most people upgraded and issues with. P20p started, (mine didn't receive update) floodlight is not popular so.

I think for now, only way of knowing is people like me making error. 

Dunno if it possible but maybe add a per device switch to enable p2p encryption? Well think that's more fuatakside but your add on bass to support the switch.

Thanks for the support man, great work!

**Comment by bropat** [comment]
I won't be able to look again for a few days (probably at the weekend). I want to try to understand from where the app understands whether a device supports p2p encryption or not.
In the meantime, you can use the previous version ;).
If this is not a problem for you, I would keep the device sharing for the time being.

**Comment by kvanbiesen** [comment]
Yeah I don't mind. You can use the device.  As long as you don't put it on away mode or make the siren go "whieeeeee"..... :-)

No I don't mind using he 1.6.2 release as my home is still the old  not latest firmware so still supports non encryption. 

No rush my friend. ..I appreciate already all your work

**Comment by jesse-kaufman** [comment]
Getting the same issue on my doorbell cam (T8200) .. downgrading to 1.6.2 still works, of course, as my floodlight cam and doorbell haven't received a firmware update forcing encryption .. thanks for all your work on this!

**Comment by bropat** [comment]
@kvanbiesen 

I have now implemented everything so that the library now recognises whether a device supports P2P encryption and which or not.
You can revoke the sharing.
I will release everything soon.

**Comment by kvanbiesen** [comment]
super, thanks for the support. 

Just give me a holler if you need access again :)

**Comment by bropat** [comment]
Fixed in version `1.6.4`.

**Comment by DominicMuir** [comment]
I still seem to have the issue on Eufy Dual doorbell (even after updating to 1.6.4)

**Comment by andrewlelos** [comment]
Hi, I seem to be having this issue in the latest version with a Eufy Floodlight E340 (support was only added in the latest version)

**Comment by kotana** [comment]
> Hi, I seem to be having this issue in the latest version with a Eufy Floodlight E340 (support was only added in the latest version)

I have the same problem.
Is there a solution?

**Comment by Raphdeumax** [comment]
> > Hi, I seem to be having this issue in the latest version with a Eufy Floodlight E340 (support was only added in the latest version)
> 
> I have the same problem. Is there a solution?

Hi, there,

I have the same problem when I try to access the camera on my Floodlight E340. When I look in the module log, I get the following message: 

`Decrypt Error {
  error: {
    cause: undefined,
    message: 'Error: error:1C80006B:Provider routines::wrong final block length',
    context: undefined,
    stacktrace: 'Error: error:1C80006B:Provider routines::wrong final block length\n' +
      '    at Decipheriv.final (node:internal/crypto/cipher:199:29)\n' +
      '    at decryptP2PData (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:102:18)\n' +
      '    at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1175:71)\n' +
      '    at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1152:26)\n' +
      '    at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:986:26)\n' +
      '    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:118:56)\n' +
      '    at Socket.emit (node:events:517:28)\n' +
      '    at Socket.emit (node:domain:489:12)\n' +
      '    at UDP.onMessage [as onmessage] (node:dgram:942:8)'
  },
  stationSN: 'T8425T11240XXXXX',
  message: {
    seqNo: 2,
    channel: 255,
    commandType: 'CMD_HUB_REBOOT',
    signCode: 1,
    type: 1,
    dataType: 'DATA',
    data: '000000000000000000000000000000000000000000000000000000000000000000000000'
  }
}`

Thanks ;-)

**Comment by DaniloSia** [comment]
hi,
I bave sam problem with model t8416 (indoor Cam S350):

2024-07-16 23:11:25.348 DEBUG   eufy-security-ws:eufy-security-client   [p2p] [P2PClientProtocol.handleData] Handle DATA DATA - Decrypt Error {                                                                                                                                  
  error: {                                                                                                                                                                                                                                                                       
    cause: undefined,                                                                                                                                                                                                                                                            
    message: 'Error: error:1C80006B:Provider routines::wrong final block length',                                                                                                                                                                                                
    context: undefined,                                                                                                                                                                                                                                                          
    stacktrace: 'Error: error:1C80006B:Provider routines::wrong final block length\n' +                                                                                                                                                                                          
      '    at Decipheriv.final (node:internal/crypto/cipher:193:29)\n' +                                                                                                                                                                                                         
      '    at decryptP2PData (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:102:18)\n' +                                                                                                                                                                     
      '    at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1175:71)\n' +                                                                                                                                                    
      '    at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1152:26)\n' +                                                                                                                                              
      '    at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:986:26)\n' +                                                                                                                                                      
      '    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:118:56)\n' +                                                                                                                                                               
      '    at Socket.emit (node:events:518:28)\n' +                                                                                                                                                                                                                              
      '    at Socket.emit (node:domain:488:12)\n' +                                                                                                                                                                                                                              
      '    at UDP.onMessage [as onmessage] (node:dgram:941:8)'                                                                                                                                                                                                                   
  },

**Comment by Birdack** [comment]
hi,
I bave sam problem with model t8416 (indoor Cam S350):

2024-07-16 23:11:25.348 DEBUG eufy-security-ws:eufy-security-client [p2p] [P2PClientProtocol.handleData] Handle DATA DATA - Decrypt Error {
error: {
cause: undefined,
message: 'Error: error:1C80006B:Provider routines::wrong final block length',
context: undefined,
stacktrace: 'Error: error:1C80006B:Provider routines::wrong final block length\n' +
' at Decipheriv.final (node:internal/crypto/cipher:193:29)\n' +
' at decryptP2PData (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:102:18)\n' +
' at P2PClientProtocol.handleData (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1175:71)\n' +
' at P2PClientProtocol.parseDataMessage (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:1152:26)\n' +
' at P2PClientProtocol.handleMsg (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:986:26)\n' +
' at Socket. (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:118:56)\n' +
' at Socket.emit (node:events:518:28)\n' +
' at Socket.emit (node:domain:488:12)\n' +
' at UDP.onMessage [as onmessage] (node:dgram:941:8)'
},
