### ISSUE TITLE
[Bug]: T8503 Doesn't stay connected to Server

### ISSUE THREAD

**Issue by iamehkri** [bropat/eufy-security-ws#254]
### Version

2.8/-

### Node version

-

### Operating System type

Other

### Operating system version

Home Asisstant

### Describe the bug

My batteries were low on my Eufy T8503 lock so it wasn't reporting properly to Home Assistant; after replacing them the Eufy server seems to disconnect after finding it, when I reload the integration it works, and then disconnects.  I got a notification error in Home assistant , and the log files show that it was connected/disconnected.

Not sure what I can do, I've uninstalled the add-on, integration, factory reset the lock, but I can't get HA to connect to it longer than a few seconds.

### To reproduce

1. Start Eufy add on
2. Add Eufy Integration
3. Connects for a 15 seconds to get lock status
4.  Disconnects

### Screenshots & Logfiles

Home Assitant Error

`Error: <Task finished name='Task-619061' coro=<WebSocketClient._process_messages() done, defined at /config/custom_components/eufy_security/eufy_security_api/web_socket_client.py:62> result=None>`

Eufy Logfile

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-08-30 12:51:35.098  INFO  Eufy Security server listening on host 0.0.0.0, port 3001 
2023-08-30 12:51:37.538  INFO  MQTT connection successfully established 
2023-08-30 12:51:37.577  INFO  Successfully registered to MQTT notifications for lock T8503Q1022330628 
2023-08-30 12:51:38.708  INFO  Push notification connection successfully established 
2023-08-30 12:51:40.782  INFO  Connected to station T8503Q1022330628 on host 192.168.1.230 and port 29301 
2023-08-30 12:51:41.286  INFO  Disconnected from station T8503Q1022330628 `

**Comment by bropat** [comment]
This device is not yet supported. See [here](https://bropat.github.io/eufy-security-client/#/supported_devices).
For now, please check the relative documentation so that I don't have to answer the same thing several times. I am only one person, you are many...

**Comment by iamehkri** [comment]
I apologize…. But I’m baffled as to why it worked for months?  I’m not making this up,  was this device recently marked as incompatible?
