### ISSUE TITLE
[Question]: Is there a way to Ignore a Station (in a config.json)

### ISSUE THREAD

**Issue by TaZZaT** [bropat/eufy-security-ws#256]
### Ask your question

Question.  I was wondering if I could ignore a station?  

Background:  I have a new wifi Eufy Lock (T8502).  On the current code it doesn't seem to be supported - the server is constantly "Connected to Station..."/"Disconnected to Station" which is killing the battery in the lock (lasts less than a week).  My HomeBase Station works as expected (not reconnecting/disconnecting). 

Thanks in advance.

**Comment by fuatakgun** [comment]
I don't have an answer for your question but you can create a separate account and share only relevant devices with it and use the second account with this library. Makes sense?

**Comment by TaZZaT** [comment]
> I don't have an answer for your question but you can create a separate account and share only relevant devices with it and use the second account with this library. Makes sense?

Yep.. I just figured that out.  Thank you and have a great day!
