### ISSUE TITLE
[Bug]: Streamstatus goes to Preparing and no stream is showing.

### ISSUE THREAD

**Issue by DarkAllMan** [bropat/eufy-security-ws#257]
### Version

1.6.4

### Node version

?

### Operating System type

Linux

### Operating system version

HA OS 10.5 / 2023.8.3

### Describe the bug

No streaming video (worked before, do not know when it stopped working)

### To reproduce

1. Go to Settings
2. Go to Devices & Service
3. Go to Eufy Security Devices List
4. Select any device
5. Scroll down to Diagnostic
6. Press Start P2P Stream
7. Check Stream Status
8. Stop P2P stream

### Screenshots & Logfiles

![image](https://github.com/bropat/eufy-security-ws/assets/1582343/11c286e9-b2e6-4838-91d2-876ad655bcaa)

### Additional context

It's on all my Eufy Devices:
T8114-Z
T8210
T8113-Z

**Comment by DarkAllMan** [comment]
This seemed to be related to WebRTC using port 8554. 
I removed that port from WebRTC and it is working now.

**Comment by nadzvee** [comment]
Hi I am having a similar issue. Tweaking the go2rtc ports has not helped as no matter what port I select. When I start scrypted server my stream crashes. How do I get the scrypted webrtc plugin to stop conflicting with my eufy streams
