### ISSUE TITLE
[Question]: Pan&Tilt camera API: Rotate is OK but the other directions don't work

### ISSUE THREAD

**Issue by lxrootard** [bropat/eufy-security-ws#258]
### Ask your question

Hello @bropat 
One of my Jeedom end-users is asking if I can add Pan & Tilt support for T841x.
I don't have this device so I can't test. 
What is the `direction ` parameter value format for the [device.pan_and_tilt](https://bropat.github.io/eufy-security-ws/#/api_cmds?id=pan-and-tilt-camera) API ? 
text? integer? 

Thanks

**Comment by fuatakgun** [comment]
You can work backwards from here: https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/eufy_security_api/camera.py#L187

**Comment by lxrootard** [comment]
hello

My user made the test unfortunately it does NOT work ??

`import json
from websocket import create_connection
ws = create_connection("ws://127.0.0.1:3000")
print(ws.recv())
print ('\n*** Init ***')
ws.send(json.dumps({"command": "start_listening"}))
print(ws.recv())
print ('\n*** Station pan & tilt ***')
ws.send(json.dumps({"command": "device.pan_and_tilt","serialNumber": "T8410xxxx", "direction": "1" }))
print(ws.recv())
ws.close()
`
Result:
`
*** Init ***
{« type »:« result »,« success »:true,« result »:{« state »:{« driver »:{« version »:« 2.6.2 »,« connected »:true,« pushConnected »:true},« stations »:[{« name »:« Salon »,« model »:« T8410 »,« serialNumber »:« T8410XXXXXXXXX »,« hardwareVersion »:« P2 »,« softwareVersion »:« 2.1.9.5 »,« lanIpAddress »:« 192.168.1.10 »,« macAddress »:« 8CXXXXXXXXXXXX »,« currentMode »:1,« guardMode »:1,« connected »:true}],« devices »:[{« name »:« Salon »,« model »:« T8410 »,« serialNumber »:« T8410XXXXXXXXXX »,« hardwareVersion »:« P2 »,« softwareVersion »:« 2.1.9.5 »,« stationSerialNumber »:« T8410XXXXXXXXXX »,« enabled »:true,« motionDetected »:false,« personDetected »:false,« personName »:«  »,« soundDetected »:false,« petDetected »:false,« cryingDetected »:false,« autoNightvision »:true,« motionDetection »:true,« soundDetection »:false,« petDetection »:false,« rtspStream »:true,« pictureUrl »:« /media/mmcblk0p1/Camera00/20230729190418n.jpg »,« ledStatus »:true}]}}}

*** Device pan & tilt ***
{« type »:« result »,« success »:false,« errorCode »:« unknown_command »}
`

**Comment by lxrootard** [comment]
Hello
Forget my previous message it works with integer instead of string

**Comment by lxrootard** [comment]
Hello

I'm reopening this issue as the [device.pan_and_tilt](https://bropat.github.io/eufy-security-ws/#/api_cmds?id=pan-and-tilt-camera) command doesn't work as expected on T8410:
My end-user has determined that ROTATE360 = 0 works OK but the other commands eg LEFT = 1, RIGHT = 2, UP = 3, DOWN = 4 also rotate the camera instead of moving it.

@fuatakgun I understand you've [implement this feature in HA](https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/eufy_security_api/camera.py#L187). Does it work???

**Comment by fuatakgun** [comment]
I have one 2k indoor pan/tild and it is working as expected

**Comment by lxrootard** [comment]
> I have one 2k indoor pan/tild and it is working as expected

strange...could you please indicate which FW you're using?
