### ISSUE TITLE
[Question]: use control panel as a remote

### ISSUE THREAD

**Issue by sanderhoeppermans** [bropat/eufy-security-ws#259]
### Ask your question

Hi,

Is there a way to use the control panel/keypad as a remote to run other actions? Like, hold '1' for a long press and shot down the lights? On Philips Hue remote, this is a possibility. See below:

<img width="1080" alt="image" src="https://github.com/bropat/eufy-security-ws/assets/121697071/69464671-9fe6-457b-94c7-d986e6461202">

**Comment by bropat** [comment]
Not that I know of.
