### ISSUE TITLE
[Bug]: Eufy T8410 Not showing in the integration, and I have 2

### ISSUE THREAD

**Issue by DavidFFerreira** [bropat/eufy-security-ws#260]
### Version

1.6.4

### Node version

1.6.4

### Operating System type

Linux

### Operating system version

Debian 11

### Describe the bug

I have an integration with eufy working for outdoor cameas and doorringbell. Also I have the HomeBase2
My indoor cameras T8410 are connected via wifi, since HomeBase2 dont support those cameas.

in the Addon integration only show up what is on print screen
![image](https://github.com/bropat/eufy-security-ws/assets/32928749/55cfa69e-9b07-4284-88c8-197cfdc493de)

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
Missing devices is a configuration issue on your side. Not a bug.

**Comment by DavidFFerreira** [comment]
If is a issue on my side (thats not) than tell me how. Cause I add boght cameras on IP Servers on your normal configuration

- serial_number: T8410P4223220XXX
  ip_address: 192.168.1.XXX
- serial_number: T8410P4223220XXX
  ip_address: 192.168.1.XXX

**Comment by fuatakgun** [comment]
Not sure where is the problem, but sharing the add-on logs might help; such as;

```
2023-10-06 10:08:35.160  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-10-06 10:08:39.818  INFO  Connected to station T8010N23xxx0480 on host 192.168.xx.xx and port 11389 
2023-10-06 10:08:40.541  INFO  Connected to station T84A1P10xxx28E1 on host 83.99.xx.xx and port 21181 
2023-10-06 10:08:40.598  INFO  Connected to station T8410P20xxx12B3 on host 83.99.xx.xx and port 24817 
2023-10-06 10:08:42.667  INFO  Push notification connection closed 
2023-10-06 10:08:42.680  INFO  Push notification connection successfully established 
2023-10-06 10:08:48.387  INFO  Push notification connection successfully established 
```

**Comment by DavidFFerreira** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-10-06 16:25:11.560  INFO  Eufy Security server listening on host 0.0.0.0, port 3331 

it custs all and i got only the next error

     '    at Camera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:2352:32\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  data: '{"r'
}
2023-10-06 16:24:04.145  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2708,
  value: '{"r'
}
2023-10-06 16:24:04.145  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:154:21)\n' +
      '    at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n' +
      '    at Camera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at Camera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:2352:32\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  data: '{"r'
}
2023-10-06 16:24:04.146  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2707,
  value: '{"r'
}
2023-10-06 16:24:04.146  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:154:21)\n' +
      '    at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n' +
      '    at Camera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at Camera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:2352:32\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  data: '{"r'
}
2023-10-06 16:24:04.147  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2708,
  value: '{"r'
}
2023-10-06 16:24:04.147  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:154:21)\n' +
      '    at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n' +
      '    at BatteryDoorbellCamera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at BatteryDoorbellCamera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:2352:32\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  data: '{"r'
}
2023-10-06 16:24:04.148  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2708,
  value: '{"r'
}
2023-10-06 16:24:04.148  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSON (/usr/src/app/node_modules/eufy-security-client/build/utils.js:154:21)\n' +
      '    at Function.readValue (/usr/src/app/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n' +
      '    at BatteryDoorbellCamera.updateRawProperty (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:127:57)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/http/device.js:54:22\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at BatteryDoorbellCamera.update (/usr/src/app/node_modules/eufy-security-client/build/http/device.js:53:35)\n' +
      '    at /usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:2352:32\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  data: '{"r'
}
2023-10-06 16:24:04.148  WARN Non-parsable parameter value received from eufy cloud. Will be ignored. 
{
  type: 2707,
  value: '{"r'
}
2023-10-06 16:24:05.823  INFO  Push notification connection successfully established

**Comment by DavidFFerreira** [comment]
damm, you are right @bropat , i did not share the last 2 cameras with my profile :O
