### ISSUE TITLE
[Bug]: won't work after Update to 1.6

### ISSUE THREAD

**Issue by tmbs1988** [bropat/eufy-security-ws#262]
### Version

1.6

### Node version

?

### Operating System type

Other

### Operating system version

Hassos?

### Describe the bug

Seems I posted this first time in the wrong forum so I am trying it here now since it hasn't worked for over 2 weeks now and I don't know what to do.. 

> **Suddenly lost connection to all devices, worked for a very long time before. Updated addon, and HA and now it don't want to connect anymore **
> 
> Restarting the Add-On and then going back to the integration to put in the configure just to move back to the Add-On and seeing this error in the log file
> 
> s6-rc: info: service s6rc-oneshot-runner: starting s6-rc: info: service s6rc-oneshot-runner successfully started s6-rc: info: service fix-attrs: starting s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting s6-rc: info: service legacy-cont-init successfully started s6-rc: info: service legacy-services: starting s6-rc: info: service legacy-services successfully started 2023-09-06 20:41:03.442 INFO Eufy Security server listening on host 0.0.0.0, port 3002 2023-09-06 20:41:05.313 INFO Connected to station T8410P3122094E5E on host 192.168.1.127 and port 26407 2023-09-06 20:41:05.499 INFO Connected to station T8010T2322090471 on host 192.168.1.108 and port 19961 2023-09-06 20:41:07.395 INFO Push notification connection successfully established 2023-09-06 20:41:54.511 INFO Client disconnected with ip: 127.0.0.1 port: 58132 code: 1000 reason: Normal Closure
> 
> I searched for the error here and found some relations to trusted device, but trying to follow those steps and nothing changes.
> 
> What should I do?

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

In the post

**Comment by lukeqormi95** [comment]
Same issue here, did you manage to resolve it ?

**Comment by tmbs1988** [comment]
Nope, still no resolution and no response. Been weeks now

**Comment by akathedrummer** [comment]
I had the same issue but found that I also had to update the add-on under the HACS tab. After that everything worked like a charm again. Maybe that helps some of you out too.

**Comment by lukeqormi95** [comment]
> I had the same issue but found that I also had to update the add-on under the HACS tab. After that everything worked like a charm again. Maybe that helps some of you out too.

This was it ! Missed the add on under the hacs tab, everything is working fine now after updating. Thanks !

**Comment by bropat** [comment]
@tmbs1988 

I do not see any error here for this reason I am closing this issue.
