### ISSUE TITLE
[Feature request]: eufyCam E330 Professional (T8600) wired camera support

### ISSUE THREAD

**Issue by jesse-kaufman** [bropat/eufy-security-ws#263]
### Describe the solution you'd like

I'd love support for the eufyCam E330 Professional wired camera, even if it's just the event image and sensors to start. (I haven't had luck with streaming on Eufy cameras that are h265-only, and the image/sensors are way more important to me)

I'm more than happy to share my device whenever you have time to look into it!

Currently I get a Reset Alarm button, Trigger Alarm button, and Debug (Device) with the following:

properties: 
model: T8600
serialNumber: T8600P102*******
hardwareVersion: P2
softwareVersion: 0.5.7.7
type: 24
stationSerialNumber: T8030P132*******

commands: 
voices: null

**Comment by jesse-kaufman** [comment]
I'm happy to share access to my E330 to get it supported. Let me know what address to share it with (it's located in the US).

**Comment by bropat** [comment]
The device must first be implemented in the driver project. See [here](https://github.com/bropat/eufy-security-client/issues/422).

The currently supported devices can be found [here](https://bropat.github.io/eufy-security-client/#/supported_devices).
