### ISSUE TITLE
[Bug]: motionDetectionType for eufycam3/Homebase 3 not consistently working

### ISSUE THREAD

**Issue by bdormael** [bropat/eufy-security-ws#269]
### Version

1.6.4

### Node version

18

### Operating System type

Docker

### Operating system version

Debian 12

### Describe the bug

For my Eufycam3 on Homebase 3 products:

- When turning on motionDetectionTypeHuman or motionDetectionTypeHumanRecognition then motionDetectionTypePet is also turned on
- When turning motionDetectionTypeAllOtherMotions, it works fine but you cannot turn it off anymore (false doesn't work)

as example, this is the format I use for the requests:

`{
    "messageId": "string",
    "command": "device.set_property",
    "serialNumber": "T8160P21224202E1",
    "name": "motionDetectionTypeHuman",
    "value": "true"
}`
- [ ] 

### To reproduce

1. connect to the ws endpoint
2. Send the following json to the endpoint: 
`{
    "messageId": "string",
    "command": "device.set_property",
    "serialNumber": "T8160P21224202E1",
    "name": "motionDetectionTypeHuman",
    "value": "true"
}`
3. Check in the Eufy app on your device, now you can see that the previously motionDetectionTypePet which was false now also is true

1. connect to the ws endpoint
2. Send the following json to the endpoint: 
`{
    "messageId": "string",
    "command": "device.set_property",
    "serialNumber": "T8160P21224202E1",
    "name": "motionDetectionTypeAllOtherMotions",
    "value": "true"
}`
3. you can see now in the Eufy app that this is turned on
4. Send the following json to the endpoint: 
`{
    "messageId": "string",
    "command": "device.set_property",
    "serialNumber": "T8160P21224202E1",
    "name": "motionDetectionTypeAllOtherMotions",
    "value": "false"
}`
5. the motionDetectionTypeAllOtherMotions is still true in the eufy app

**Comment by bropat** [comment]
I think something has changed in the firmware since it was implemented here.
