### ISSUE TITLE
`device.stop_livestream` does not generate an event as `livestream stopped`

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-ws#27]
**Describe the bug**  
When I was using 0.3.3 version `device.stop_livestream` was succesfully generating `livestream stopped` event but I had tried latest (0.4.2) and I am not able to get respective event to detect the status

**To Reproduce**  
1. sent: {"messageId": "start_livesteam", "command": "device.start_livestream", "serialNumber": "T8113N1320483643"}
2. received: {'type': 'event', 'event': {'source': 'device', 'event': 'livestream started', 'serialNumber': 'T8113N1320483643'}}
3. sent: {"messageId": "start_livesteam", "command": "device.stop_livestream", "serialNumber": "T8113N1320483643"}
4. nothing specifically received

**Expected behavior**  
to receive: {'type': 'event', 'event': {'source': 'device', 'event': 'livestream stopped', 'serialNumber': 'T8113N1320483643'}}

**Screenshots & Logfiles**  
N/A

**Versions:**  
Docker version 0.4.2 (latest tag(

**Additional context**  
N/A

**Comment by fuatakgun** [comment]
Logs from docker;
```
LivestreamNotRunningError  Livestream for device T8113N63205014E2 could not be stopped, because it is not running
details:
{
  name: 'LivestreamNotRunningError'
}
error stack:
• message_handler.ts:145 handle
    src/lib/device/message_handler.ts:145:31
• server.ts:46 device
    src/lib/server.ts:46:34
• server.ts:98 receiveMessage
    src/lib/server.ts:98:58
• server.ts:57 <anonymous>
    src/lib/server.ts:57:53
• events.js:400 emit
    events.js:400:28
• websocket.js:1009 receiverOnMessage
    node_modules/ws/lib/websocket.js:1009:20
• events.js:400 emit
    events.js:400:28
• receiver.js:522 dataMessage
    node_modules/ws/lib/receiver.js:522:14
• receiver.js:440 getData
    node_modules/ws/lib/receiver.js:440:17
• receiver.js:148 startLoop
```

**Comment by bropat** [comment]
@fuatakgun Have you already tried the same directly with the available eufy-security-ws client application?
Is the behaviour the same?

Sorry I don't have much time at the moment.

**Comment by fuatakgun** [comment]
i will give it a try and update here.

No worries, 0.3.3 is doing work well enough, do you think we are missing anything important because of lacking 0.4.2? Users are mostly interested faster p2p streaming :-)

**Comment by bropat** [comment]
@fuatakgun 

> i will give it a try and update here.

ok, thx.

> do you think we are missing anything important because of lacking 0.4.2? Users are mostly interested faster p2p streaming :-)

Mainly the correct handling of multiple clients who want to view the same P2P stream.
Otherwise, some important bug fixes have been made in the eufy-security-client driver (see mainly changelog). 0.3.3 uses version 0.9.4 of the driver, 0.4.2 version 1.1.2.

**Comment by fuatakgun** [comment]
Got it, thanks, i will check

**Comment by bropat** [comment]
The latency of the livestream has also been optimised (sometimes at the expense of the audio; I still have to find a better solution there...)

**Comment by fuatakgun** [comment]
Issue is happening through bare client too. This is not of the blockers for me to update version, please let me know if i can help

**Comment by bropat** [comment]
@fuatakgun 

Please check out new version and let me know

**Comment by bropat** [comment]
@fuatakgun 

1. Which version do you use? 0.5.0?
2. With which scheme version? 6?

**Comment by bropat** [comment]
I don't think the problem is with eufy-security-ws, rather with eufy-security-client.
To find the cause, I need the entire log of the test in debug mode.

**Comment by fuatakgun** [comment]
sorry, again channels are mixed :) I will give a summary soon

**Comment by fuatakgun** [comment]
when I commented out following your advice, I was able to receive event once, but for the rest, add-on became unstable as example like below;
```
2021-10-19 20:20:07.290  INFO Disconnected from station T8010N2320460480
2021-10-19 20:20:08.007  INFO Connected to station T8010N2320460480 on host 192.168.178.23 and port 20519
2021-10-19 20:20:14.117  INFO Client disconnected with ip: ::ffff:192.168.178.119 port: 59312 code: 1006 reason:
2021-10-19 20:20:14.198  INFO Disconnected from station T8010N2320460480
2021-10-19 20:20:19.253  INFO Connected to station T8010N2320460480 on host 192.168.178.23 and port 26197
2021-10-19 20:20:25.194  INFO Disconnected from station T8010N2320460480
2021-10-19 20:20:30.243  INFO Connected to station T8010N2320460480 on host 192.168.178.23 and port 14179
2021-10-19 20:20:36.198  INFO Disconnected from station T8010N2320460480
2021-10-19 20:20:41.244  INFO Connected to station T8010N2320460480 on host 192.168.178.23 and port 12823
2021-10-19 20:21:42.094  WARN Station T8010N2320460480 - Heartbeat check failed. Connection seems lost. Try to reconnect...
2021-10-19 20:21:42.096  INFO Disconnected from station T8010N2320460480
2021-10-19 20:21:42.688  INFO Connected to station T8010N2320460480 on host 192.168.178.23 and port 12823
2021-10-19 20:21:42.700  INFO Disconnected from station T8010N2320460480
```
