### ISSUE TITLE
[Feature request]: Support for the E340 Doorbell (T8214)

### ISSUE THREAD

**Issue by viscerian** [bropat/eufy-security-ws#272]
### Describe the solution you'd like

Please add support for the E340 Doorbell. Currently the device is detected, but only shows debug entities.

**Comment by raed21** [comment]
I second this request. Please let me know if there is any information that we can collect from the T8214 to help make this happen.

**Comment by frenchish** [comment]
+1 this request, have the same doorbell here too, happy to provide any info I can too.

@raed21 I see there's a repo for the client but nothing in the addon store, is it yet to be released?

**Comment by johannes281** [comment]
+1

**Comment by Stefan774** [comment]
+1 please update/release the eufy-security-ws with E340 Doorbell support. Would love to see it working in HA before Christmas
;) THX

**Comment by hursss** [comment]
> +1 please update/release the eufy-security-ws with E340 Doorbell support. Would love to see it working in HA before Christmas
> ;) THX

+1

**Comment by eversteegt** [comment]
+1 ! If releasing the next version/milestone for now is not yet doable, maybe we can have some brief overview of steps on how to fork the repos that are involved for eufy-security-ws and the HA addons and what to change to install it for testing manually in HA ?

**Comment by filou01** [comment]
Please add the E340 doorbell support to the downloadable release. 
Or give us a foresight when it will be released. 
Thank you in advice.

**Comment by JohnDNI** [comment]
+1 Hopefully coming soon!
