### ISSUE TITLE
[Feature request]: e340 Floodlight Cam Support

### ISSUE THREAD

**Issue by same2you** [bropat/eufy-security-ws#276]
### Describe the solution you'd like

Would also love support for the e340 Floodlight cam

**Comment by wolfjank** [comment]
I would fully agree with that. I need support for E340 and S340. :-)

**Comment by johannes281** [comment]
+1

**Comment by brianallen14** [comment]
+1 as well! Would love to see this device supported.

**Comment by bropat** [comment]
The device must first be implemented in the driver project. See [here](https://github.com/bropat/eufy-security-client/issues/388).

The currently supported devices can be found [here](https://bropat.github.io/eufy-security-client/#/supported_devices).

**Comment by kotana** [comment]
+1

**Comment by robinhood-code** [comment]
when will this be released? thanks.
