### ISSUE TITLE
[Question]: how is device.start_download supposed to work?

### ISSUE THREAD

**Issue by lxrootard** [bropat/eufy-security-ws#278]
### Ask your question

Hello

How is [device.start_download](https://bropat.github.io/eufy-security-ws/#/api_cmds?id=device-level-commands) supposed to work?
`{"command": "device.start_download" , "serialNumber": "T8410xxxxxx", "path": "/tmp" }
{"type":"result","success":false,"errorCode":"unknown_command"}`

From [this post](https://github.com/bropat/eufy-security-ws/issues/176) it's not clear what should be the value for `cipherId` ?
[Reading the code](https://github.com/bropat/eufy-security-client/blob/7fc2a45a75ee1bf69ced36d351d1ec6d623896f6/src/http/station.ts#L3600) it seems it's an RSA key. Where do I get it?

Thanks

**Comment by lxrootard** [comment]
Up!
Could you please indicate if this command is either:
1. functional > please explain further
2. deprecated ?
Thanks

**Comment by hrqiang** [comment]
Same here. I'm looking for a way to download recording from command line(client.js) as well.

**Comment by bropat** [comment]
It's deprecated and no more working.
