### ISSUE TITLE
Can't figure out 2fa

### ISSUE THREAD

**Issue by 1DontEx1st** [bropat/eufy-security-ws#28]
I'm running the docker container, and am receiving an emailed 2fa code when starting, but I have no idea how to get that code _to_ the  server. What am I missing?

**Comment by bropat** [comment]
@1DontEx1st 
By making the call `driver.set_verify_code` with the additional parameter `verifyCode`, where you specify the received verification code, to complete the 2fa.

**Comment by 1DontEx1st** [comment]
Is this something I could do with Postman? Not a developer but I'm trying to pretend...

**Comment by 1DontEx1st** [comment]
In case someone else who doesn't know what they're doing comes behind me, I was able to use Postman to send the following message to my instance and get it going. Thanks @bropat !

{
    "command": "driver.set_verify_code",
    "verifyCode": "XXXXXX"
}

**Comment by rollesky** [comment]
@1DontEx1st can you elaborate a bit more how you have managed that? I am running 
newman run eufy.json 
where eufy.jsanon is what you have written above with XXXXX replaced by my code but my container is still showing:
INFO  Requested verification code for 2FA 
What am I doing wrong?

**Comment by 1DontEx1st** [comment]
I don't know what newman is, so not sure what you mean. Postman is an application that lets you send GET and POST codes to a web server. In this case the web server is the eufy-security-ws instance, and the code is that little bit of JSON above. Does that make sense?

**Comment by rollesky** [comment]
![20220403_201758](https://user-images.githubusercontent.com/87335898/161442392-d7224428-805c-4af7-a654-3e4316a18302.jpg)
I went to my sever and this is what I was trying to do (see attached picture). I replaced of course 0.0.0.0 with my server ip were container was up and waiting for 2FA code and 1234 with a code I got from eufy.
What am I doing wrong?

**Comment by YassineElbouchaibi** [comment]
It uses websockets. You can use something like websocat to send out commands to the server.
```
echo '{"messageId": "0001", "command": "driver.set_verify_code", "verifyCode": "XXXXXX"}' | websocat ws://127.0.0.1:3000
```

**Comment by anuragdeshpande** [comment]
> It uses websockets. You can use something like websocat to send out commands to the server.
> 
> ```
> echo '{"messageId": "0001", "command": "driver.set_verify_code", "verifyCode": "XXXXXX"}' | websocat ws://127.0.0.1:3000
> ```

Thank you so much! This helped me out.
