### ISSUE TITLE
[Feature request]: T8506 Lock/Unlock

### ISSUE THREAD

**Issue by pyr8** [bropat/eufy-security-ws#282]
### Describe the solution you'd like

Is it currently possible to "Lock/Unlock" the T8506 using this integration? If so, how do I go about it? I have setup Eufy-Security-WS and under sensors all I see are 2 "Debug" devices.

**Comment by Michael-ibanez** [comment]
I just got a T8506 and would like to see support for this device as well.
Thanks

**Comment by dariusz65** [comment]
Same issue here. Got T8506 and only see 2 debug devices.

**Comment by bropat** [comment]
The device must first be implemented in the driver project. See [here](https://github.com/bropat/eufy-security-client/issues/356).

The currently supported devices can be found [here](https://bropat.github.io/eufy-security-client/#/supported_devices).
