### ISSUE TITLE
[Error]:  DeviceNotFoundError: Device doesn't exists

### ISSUE THREAD

**Issue by buzurk26** [bropat/eufy-security-ws#284]
### Version

1.7.1

### Node version

.

### Operating System type

Linux

### Operating system version

HASS OS

### Describe the bug

Seeing error in my logs for the addon

![image](https://github.com/bropat/eufy-security-ws/assets/39994663/e45ea553-0191-432c-9da9-065e837c50d2)

### To reproduce

Error is in logs

### Screenshots & Logfiles

.

### Additional context

.

**Comment by PhilippEngler** [comment]
Please have a look at #265. This occurs after delete a device and will be fixed in next version.
