### ISSUE TITLE
[Question]: On startup I get an ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by jcouzy** [bropat/eufy-security-ws#286]
### Ask your question

Hi, try to start de container with the specified command and get this error:

2023-12-12 17:03:54.533  ERROR Register FID - Generic Error 
{
  error: {
    cause: undefined,
    message: 'RequestError: connect ECONNREFUSED 0.0.0.0:443',
    context: undefined,
    stacktrace: 'RequestError: connect ECONNREFUSED 0.0.0.0:443\n' +
      '    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:970:111)\n' +
      '    at Object.onceWrapper (node:events:632:26)\n' +
      '    at ClientRequest.emit (node:events:529:35)\n' +
      '    at ClientRequest.emit (node:domain:489:12)\n' +
      '    at origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n' +
      '    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n' +
      '    at TLSSocket.emit (node:events:517:28)\n' +
      '    at TLSSocket.emit (node:domain:489:12)\n' +
      '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
      '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
      '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)'
  }
}

Any clue what is going wrong?

Thanks!

**Comment by bropat** [comment]
`ECONNREFUSED` is a faulty configuration on your side, such as a firewall that blocks or a software solution that blocks ads (pi-hole or ad-aware). In this case, the DNS resolution returns `0.0.0.0` instead of the correct IP address. This results in the error `ECONNREFUSED`.

**Comment by eskiiom** [comment]
Hello @bropat I have the same issue and have pi-hole running on the network.
I understand this is linked, but can you please explain what is called so I can allow it in pi-hole, then have the correct ip returned and the WS running ?
And I didn't find this in the log or documentation

Thanks !
