### ISSUE TITLE
[Bug]: When adding Homebase missing most functions. (Only noticed since having two Homebases S380 and Homebase 2 on same account)

### ISSUE THREAD

**Issue by soulroyale** [bropat/eufy-security-ws#288]
### Version

1.7.1

### Node version

?

### Operating System type

Linux

### Operating system version

HAOS 11.2

### Describe the bug

I have been using this addon with an S380 for some time with no issues, I recently add into my eufy account my Home Base 2, the Home Base 2 has Motion and Door sensors only. However Although it shows up most functions are not available. 

I tried reinstalling the add-in etc. however this resulted in both Home Bases then having the problem. 

If I restore my HA from backup the S380 functions are restored and the Home Base 2 syncs back in again, but still broken. 

The only options available are:
- Set value for Home Base Prompt Volume
- Set value for Home Base Alarm Volume

Cameras seem to have all options available.

### To reproduce

As above, just having the 2 devices in my account and setting up the addon. The issue reoccurs everytime.

### Screenshots & Logfiles

![Screenshot 2023-12-21 211848](https://github.com/bropat/eufy-security-ws/assets/16874470/9a22cec9-17bc-40ab-9437-2f722a6d9e75)
![Screenshot 2023-12-21 212204](https://github.com/bropat/eufy-security-ws/assets/16874470/905dda87-98e8-450c-a8b6-574c7a191303)

**Comment by bropat** [comment]
wrong repo
