### ISSUE TITLE
[Bug]: S100(T84A1): getting/setting color properties raise error

### ISSUE THREAD

**Issue by lxrootard** [bropat/eufy-security-ws#293]
### Version

1.7.1

### Node version

docker

### Operating System type

Linux

### Operating system version

official docker image

### Describe the bug

Hi @bropat 
Happy new year and kudos for your great work on Eufy devices!
I'm having errors getting and setting color properties on an end-user S100(T84A1).

`device.get_properties` reads the color OK eg:
`"lightSettingsManualColoredLighting":{"red":255,"green":65,"blue":0}`

However `device.get_property` raises an error:
`{"type":"result","success":false,"errorCode":"unknown_command"}`

Also from` device.get_properties_metadata` lightSettingsXXXColoredLighting are read/write.
Still `device.set_property` raises another error:
`{"type":"result","success":false,"errorCode":"device_invalid_property_value"}`

### To reproduce

See my py test program and log attached
Thanks ;)

### Screenshots & Logfiles

[log2.txt](https://github.com/bropat/eufy-security-ws/files/13845108/log2.txt)

### Additional context

[test_color_S100.py.txt](https://github.com/bropat/eufy-security-ws/files/13845117/test_color_S100.py.txt)

**Comment by lxrootard** [comment]
@bropat the logs are in attachment, see screenshots & logfiles section

**Comment by bropat** [comment]
Please always demonstrate the misbehaviour by demonstrating the problem directly with the supplied client, otherwise the issue will be closed. Unfortunately I don't have the time to look at every implementation.

Thank you!
