### ISSUE TITLE
[Bug]: HomeBase trigger alarm button stopped working

### ISSUE THREAD

**Issue by mandrusiaks** [bropat/eufy-security-ws#294]
### Version

1.7.1

### Node version

18.17.1

### Operating System type

Docker

### Operating system version

Docker version 20.10.22

### Describe the bug

The "Trigger Alarm" button on the HomeBase device (T8030) stopped working after upgrading to v1.7.1. Pressing the button does not activate the alarm on the HomeBase.

### To reproduce

1. Go to your Eufy HomeBase device in Home Assistant
2. Under "Diagnostic" there should be a "Trigger Alarm" item with a button "PRESS"
3. Press the button and observe the HomeBase alarm is not triggered

### Additional context

I downgraded back to v1.6.4 and the button works as expected. The alarm is successfully triggered on the HomeBase for version 1.6.4

**Comment by lxrootard** [comment]
@mandrusiaks I get the same behavior on Homebase2 (T8010) but it never worked, see #212

**Comment by bropat** [comment]
I have successfully tested this functionality on a Homebase 2.
As I have not received any logs, do not own this homebase and cannot reproduce the problem with another homebase, I am closing this issue.
