### ISSUE TITLE
Why doesn't it not work

### ISSUE THREAD

**Issue by shaeser** [bropat/eufy-security-ws#296]
### Ask your question

What do i do wrong?

got this error:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024-01-14 15:25:13.573  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2024-01-14 15:25:14.689  INFO  Connected to station T8010P232303078E on host 192.168.2.193 and port 14137 
2024-01-14 15:25:18.000  ERROR Register FID - Generic Error 
{
  error: {
    cause: undefined,
    message: 'RequestError: connect EHOSTUNREACH 2a00:1450:400e:803::200a:443',
    context: undefined,
    stacktrace: 'RequestError: connect EHOSTUNREACH 2a00:1450:400e:803::200a:443\n' +
      '    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:970:111)\n' +
      '    at Object.onceWrapper (node:events:632:26)\n' +
      '    at ClientRequest.emit (node:events:529:35)\n' +
      '    at ClientRequest.emit (node:domain:489:12)\n' +
      '    at origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n' +
      '    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n' +
      '    at TLSSocket.emit (node:events:517:28)\n' +
      '    at TLSSocket.emit (node:domain:489:12)\n' +
      '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
      '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
      '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)'
  }
}
2024-01-14 15:25:18.017  ERROR Create push credentials Error 
{
  error: {
    cause: RequestError: connect EHOSTUNREACH 2a00:1450:400e:803::200a:443
        at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:970:111)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:529:35)
        at ClientRequest.emit (node:domain:489:12)
        at origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
        at TLSSocket.socketErrorListener (node:_http_client:501:9)
        at TLSSocket.emit (node:events:517:28)
        at TLSSocket.emit (node:domain:489:12)
        at emitErrorNT (node:internal/streams/destroy:151:8)
        at emitErrorCloseNT (node:internal/streams/destroy:116:3)
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
      code: 'EHOSTUNREACH',
      timings: {
        start: 1705245914920,
        socket: 1705245914921,
        lookup: 1705245914927,
        connect: undefined,
        secureConnect: undefined,
        upload: undefined,
        response: undefined,
        end: undefined,
        error: 1705245917992,
        abort: undefined,
        phases: {
2024-01-14 15:25:18.051  INFO  Push notification connection closed 
          wait: 1,
          dns: 6,
          tcp: undefined,
          tls: undefined,
          request: undefined,
          firstByte: undefined,
          download: undefined,
          total: 3072
        }
      }
    },
    message: 'FidRegistrationFailedError: FID registration failed',
    context: {
      fid: 'do6VqQxFJmy-ufV4wKctYt'
    },
    stacktrace: 'FidRegistrationFailedError: FID registration failed\n' +
      '    at PushNotificationService.registerFid (/usr/src/app/node_modules/eufy-security-client/build/push/service.js:130:19)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async PushNotificationService.createPushCredentials (/usr/src/app/node_modules/eufy-security-client/build/push/service.js:194:16)\n' +
      '    at async PushNotificationService._open (/usr/src/app/node_modules/eufy-security-client/build/push/service.js:635:32)\n' +
      '    at async PushNotificationService.open (/usr/src/app/node_modules/eufy-security-client/build/push/service.js:697:13)'
  },
  credentials: undefined,
  renew: false
}
2024-01-14 15:25:18.054  ERROR Push notifications are disabled, because the registration failed! 
{
  credentials: undefined,
  renew: false
}
2024-01-14 15:25:18.055  INFO  Retry to register/login for push notification in 5 seconds...

**Comment by luwii** [comment]
Same problem here. I installed the old one by accident, removed it, installed this one, did full reboot and entered my credentials into the UI. After that did not work I added the details to the configuration yml file as well. Still no luck.

Errors seem to indicate credential issue, double checked it.

**Comment by bropat** [comment]
@shaeser 

No connection to `firebaseinstallations.googleapis.com` could be established, which is a prerequisite for receiving the push notifications.

You have some network issue:

```
RequestError: connect EHOSTUNREACH 2a00:1450:400e:803::200a:443
```

**Comment by luwii** [comment]
Thanks! I clearly miss understood the problem. Will investigate.

**Comment by luwii** [comment]
IPV6 was turned off on my router from a previous set of testing - works now.
