### ISSUE TITLE
[Feature request]: Support broadcast names in station lists

### ISSUE THREAD

**Issue by sunburntastronomer** [bropat/eufy-security-ws#297]
### Version

1.7.1

### Node version

No idea

### Operating System type

Windows

### Operating system version

Windows 11

### Describe the bug

If you create a station list with broadcast names instead of IP addresses, it fails the regular expression validation and will not save.

### To reproduce

1. Go to Configuration
2. Enter in the stations list:
- serial_number: T8400P2021XXXXXX
  ip_address: XXXXXXXX.modem

Error message as follows:
Failed to save add-on configuration, does not match regular expression ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$. 

### Additional context

I note that the help shows the idea of a broadcast address, but in fact only shows an IP address.  I suspect this is soemthing that was intended but never done. If I knew where to find the config file, I'd edit it directly and see if it works.

**Comment by bropat** [comment]
This is not an error, as you can see from the regular expression. This is the expected behaviour.
Marked as enhancement request.
