### ISSUE TITLE
[Bug]: No device is found. Only the UPDATE configuration is showing up on the list of available devices

### ISSUE THREAD

**Issue by ajavier29** [bropat/eufy-security-ws#298]
### Version

1.7.1

### Node version

14.15.1

### Operating System type

Linux

### Operating system version

home assistant 11.4

### Describe the bug

Can't find my T8210 eufy video doorbell or my Homebase under the eufy-security-ws add on. Only the UPDATE configuration is showing up.

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
This is always a configuration error. Check the country setting.
