### ISSUE TITLE
[Question]: Fast battery drain on Eufy C220/T8506 Lock 

### ISSUE THREAD

**Issue by xybu** [bropat/eufy-security-ws#304]
### Ask your question

So I installed a new C220 lock late Nov 2023 and once configured it showed up in my Home Assistant's eufy-security-ws integration despite lock/unlock functionalities not supported. And then I noticed its battery lasted about just 15 days even though usage was light and batteries were brand new, while the product description says it can last up to four months.

After three occurrences of such 15-day-battery-drain I came across a webpage from Eufy suggesting third-party integrations may affect battery life and thus disabled eufy-security-ws add-on and integration in my HA to see. It was on Jan 11. It's been 42 days now and batteries are still running very strong.

Since the only difference from before was that eufy-security-ws addon and integrations were disabled, I suspect it caused the battery drain, and wonder if anyone has thoughts, fixes, or workarounds.

Thanks!

**Comment by bropat** [comment]
This device is not yet supported. It will be supported in the next release (1.8.0).
Furthermore, in the next release of eufy-security-client (3.0.0; which will be used by this project in version 1.8.0) the problem of battery drain for unsupported devices has also been fixed.
