### ISSUE TITLE
[Question]: Can't install bropat/hassio-eufy-security-ws Relese 1.8.0

### ISSUE THREAD

**Issue by kotana** [bropat/eufy-security-ws#306]
### Ask your question

Can't install bropat/hassio-eufy-security-ws-aarch64:1.8.0: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=1.8.0&fromImage=bropat%2Fhassio-eufy-security-ws-aarch64&platform=linux%2Farm64: Not Found ("manifest for bropat/hassio-eufy-security-ws-aarch64:1.8.0 not found: manifest unknown: manifest unknown")

**Comment by bropat** [comment]
It has not yet been released...
