### ISSUE TITLE
[Feature request]: Support for more than one Homebase 3 on the same network/system/account

### ISSUE THREAD

**Issue by mwareman** [bropat/eufy-security-ws#307]
### Describe the solution you'd like

Eufy told me to get a second Homebase 3 because their marketing claims are lies (cannot support more than 4 cameras when continuous recording is enabled). However, I cannot control guard mode on the second Homebase 3 as it is not being seen at all. 

I suspect the situation of multiple Homebase 3 devices may not have been accomodated. Is it possible to add?

Thank you!

**Comment by bropat** [comment]
Multiple homebases are already supported.

**Comment by mwareman** [comment]
Awesome - thank you. I'll file a seperate issue for the second Homebase not being seen.
