### ISSUE TITLE
[Bug]: 1.8.0 docker image not pushed

### ISSUE THREAD

**Issue by artushin** [bropat/eufy-security-ws#311]
### Version

1.8.0

### Node version

N/A

### Operating System type

Docker

### Operating system version

OSX Sonoma 14.3.1

### Describe the bug

Looks like the docker image wasn't pushed on release.

### To reproduce

```
docker pull bropat/eufy-security-ws:1.8.0
Error response from daemon: manifest for bropat/eufy-security-ws:1.8.0 not found: manifest unknown: manifest unknown
```

**Comment by mcoms** [comment]
The Github Action run failed after hanging for 6 hours: https://github.com/bropat/eufy-security-ws/actions/runs/8130956768

**Comment by NTGDeveloper** [comment]
+1

**Comment by robinhood-code** [comment]
has someone complied the docker image that can be shared before this is officially resolved? Not sure how long probat is going to be away and come back to fix this....

**Comment by artushin** [comment]
Wait, you mean doing something for ourselves... terrifying 😮‍💨 

pushed to `artushin/eufy-security-ws:1.8.0`
