### ISSUE TITLE
[Bug]: Eufy T8520 battery draining rapidly after eufy-security-ws 1.8.0 update

### ISSUE THREAD

**Issue by DChiuch** [bropat/eufy-security-ws#315]
### Version

1.8.0

### Node version

16.20.0

### Operating System type

Linux

### Operating system version

Synology DSM 7.2

### Describe the bug

Since upgrading eufy-security-ws to version 1.8.0, my Eufy T8520 lock is draining its battery much more rapidly than before.

<img width="1641" alt="image" src="https://github.com/bropat/eufy-security-ws/assets/6777430/8c4d8dcb-0610-4f34-8e4f-90482898c079">

### To reproduce

-

**Comment by KJThaDon** [comment]
Seeing this also on both my locks
