### ISSUE TITLE
linux/arm/v7 support missing

### ISSUE THREAD

**Issue by Sprocket02** [bropat/eufy-security-ws#317]
### Ask your question

I'm not sure if the question is correctly placed here. I have the client running as a docker container on a Raspberry. With the latest version 1.8.0 the support for the linux/arm/v7 architecture [https://hub.docker.com/r/bropat/eufy-security-ws/tags](url) is missing. Is there a reason for this?

![image](https://github.com/bropat/eufy-security-ws/assets/37394766/1a69d68b-4501-4181-bd22-be2c9073082f)

**Comment by rdecat** [comment]
I wonder the same, since the Eufy control fails if I do not update the docker image up to the latest release :(

**Comment by rdecat** [comment]
any update there @bropat ? :-)

**Comment by Ruizu22** [comment]
Same for me, can we have an update, please ?

**Comment by FlagadaJack** [comment]
Same here, can't wait for this update. Thank you very much! 👍

**Comment by bropat** [comment]
Support has been discontinued due to image generation issues with GitHub Actions.

**Comment by rdecat** [comment]
@bropat , I am trying to build the image for armV7 architecture (currently running in wsl2, a bit slow)
would you authorize me to push the image on docker hub if I succeed ?
