### ISSUE TITLE
Eufy Smart Lock T8502 (C210) recognized as alarm instead of smart lock

### ISSUE THREAD

**Issue by ben-simpson-4realz** [bropat/eufy-security-ws#318]
### Version

1.8.0

### Node version

18.8.0

### Operating System type

Linux

### Operating system version

Ubuntu 22.0.4

### Describe the bug

I'm using the docker version of eufy-security-ws with Home Assistant v2024.3.0 and Eufy Security HACS custom integration v8.0.1. The container is running and I can add my device into Home Assistant, but I can't see any Lock Entities created.
I can see

Sensors:
-Debug (device)
-Debug (station)

Entities:
-Connected
-Reset Alarm
-Trigger Alarm

My devices is Smart Lock T8502 (C210) with firmware version 2.1.1.1

### To reproduce

1. I ran the docker file command here https://github.com/bropat/eufy-security-ws/blob/master/docs/docker.md
2. I added the custom integration in Home Assistant and entered the settings to connect to the docker
3. Integration is created successfully and device info is pulled into Home Assistant
4. Unrelated entities are created which aren't usable with my device

### Additional context

It seems like the connection to Eufy is made and it pulls the correct info about the device into home assistant. It seems like it's recognized as an alarm rather than a lock and the entities it creates don't have any affect on the device.

**Comment by pdecker414** [comment]
I have the same lock but slightly different result
Sensors:
-Debug (device)
-Debug (station)
-Person name

Entities:
All disabled involving alarm along with lock status, 
![Screenshot_20240726_194314_Home Assistant](https://github.com/user-attachments/assets/bf804146-198d-4b09-b688-20af223d5aa1)
