### ISSUE TITLE
[Question]: Where to enter the 2fa code?

### ISSUE THREAD

**Issue by Bandoffe** [bropat/eufy-security-ws#320]
### Ask your question

I use my Eufy app with 2fa. Registration in the add-on is not possible because I can't find a way to enter my 2fa code. Am I missing something, or is this not possible?

**Comment by tsmanz** [comment]
I'm facing the same issue. I've searched for a solution and it appears some people have been able to authenticate with 2fa in place, but I can't find any step by step instructions on how to do it. Some people have suggested creating a separate eufy account without 2fa disabled to use with the app, but I'd like to avoid that. I get the email with 2fa code, but there doesn't appear to be anywhere to enter it.

**Comment by PhilippEngler** [comment]
As far as I remember, there must be a API-function called `verify code` or similar.

**Comment by dweeden** [comment]
I ran into this same problem (plus captcha) while running the server manually with this command: ` tsx src/bin/server.ts`

Note that I'm using tsx as ts-node from the "try it out" instructions seems to struggle with ts files.

It strangely seemed to hang but providing a -v param to the server showed it was actually needing captcha which it sends back via a base64 image you can copy into https://www.base64decode.net/base64-image-decoder for viewing

Once you know that, you can set it from another terminal window (server has to keeping running in the first) as follows:

`tsx src/bin/client.ts --command device.set_captcha -a abcd

Once you're past that you should get a verify code via email from eufy that can be set as follows:

`tsx src/bin/client.ts --command device.set_verify_code -a 123456`

**Comment by rkbest13** [comment]
- Where do you enter these commands. I have my home assistant vm running the addon and wonder if these steps are to be performed on the vm itself with hassos?

**Comment by dweeden** [comment]
I was running those commands on a linux machine after downloading this repo.   Within HA you should download and follow the instructions for [eufy_security](https://github.com/fuatakgun/eufy_security).   The HA OS should spawn dialogs for you to enter info for these fields.  If it's not, changing the password in eufy should trigger it to do so.
