### ISSUE TITLE
[Bug]: eufy-security-ws causing HA to crash

### ISSUE THREAD

**Issue by gmcdon** [bropat/eufy-security-ws#335]
### Version

1.8.0-2

### Node version

v22.1.0

### Operating System type

Linux

### Operating system version

Home Assistant Operating System 12.3

### Describe the bug

Web socket is causing HA OS to crash requiring a manual restart of the VM every time. When web socket is enabled, HA can run anywhere from 1 to 7 hours before a hard crash of the system. 
unable to find anything in logs with debugging enabled for WS as logs are automatically cleared once system is rebooted. Log streaming had been setup to forward logs to a syslog server but again unfortunately system crashes before error is sent. 

### To reproduce

Unable to determine precise steps apart from enabling WS and waiting for system crash. 
system will crash without any interactions

**Comment by xekil** [comment]
I have the same problem, but in my case the CPU usage of the extension goes from 1% to 40%, fortunately my CPU is strong otherwise it would crash, restarting the extension fixes the problem for a few hours or days then it starts again.
