### ISSUE TITLE
Doorbell E340; Error: TypeError: Cannot read properties of undefined (reading 'active')

### ISSUE THREAD

**Issue by mik55** [bropat/eufy-security-ws#338]
### Version

serverVersion 1.8.0 driverVersion 3.0.0

### Node version

v20.14.0

### Operating System type

Linux

### Operating system version

12.5

### Describe the bug

I have a Eufy Doorbell E340 (T8214). The connection with eufy-security-server and eufy-security-client works without errors. See attached log files Client_get_parameter.txt and Server_GetParameter.txt. 
As soon as I start the lifestream, an error "TypeError: Cannot read properties of undefined (reading 'active')" occurs. The stream is aborted. The same thing happens in the IOBroker adapter (v. 1.3.0 installed from GitHub).
See logfiles "Client_start_livestream.txt" and "Server_start_livestream.txt".

### To reproduce

Start Server:  
  ./eufy-security-server -v -c test.json -p 3000 -H localhost
Start Client command: 
 ./eufy-security-client -v -H localhost -p 3000 -c device.start_livestream -a T821451023381264

### Screenshots & Logfiles

[eufy-security-Client_Get_Parameter.txt](https://github.com/user-attachments/files/15667036/eufy-security-Client_Get_Parameter.txt)
[eufy-security-Server_Get_Parameter.txt](https://github.com/user-attachments/files/15684131/eufy-security-Server_Get_Parameter.txt)
[eufy-security-Client_start_livestream.txt](https://github.com/user-attachments/files/15684579/eufy-security-Client_start_livestream.txt)
[eufy-security-Server_start_livestream.txt](https://github.com/user-attachments/files/15684749/eufy-security-Server_start_livestream.txt)

**Comment by mercuryin** [comment]
No one is answering anymore here, so or this project is dead or the developer is really busy lately. I have a s100 and the addon crash just after a few minutes of p2p streaming and no reply from like 2 months ago.

**Comment by mik55** [comment]
Hello mercuryin
Have you tried the Develop version at "https://github.com/bropat/ioBroker.eusec/tree/develop"?

**Comment by mik55** [comment]
I found a way to solve this error. Using the "eufy-security-client/-server" tool, I set all values ​​that were displayed as (null) in the objects of the IoBroker adapter to plausible values. Since then the adapter has worked except for problems with the lifestream.

**Comment by mik55** [comment]
I found a way to solve this error. Using the "eufy-security-client/-server" tool, I set all values ​​that were displayed as (null) in the objects of the IoBroker adapter to plausible values. Since then the adapter has worked (except for problems with the lifestream).

**Comment by ancellitto** [comment]
Hey @mik55 , I'm in the same situation. Can you please explain how did you use this tool? I'm using this has a home assistant addon  and I'm not able find such a tool

**Comment by mik55** [comment]
@ancellitto Hello Ancelitto,
Do you know which parameter triggers the error? 
if not, just set all parameters to logical values.
The tools are command line tools that you can get from Brobat's GitHub page (https://github.com/bropat).
1. "eufy-security-client" a shared library for the EUFY systems.
2. "eufy-security-ws" the actual command line tools. There is a server that must be started beforehand and the client with which you can issue commands.
The configuration file of the server is a bit tricky and is explained here (https://bropat.github.io/eufy-security-ws/#/tryitout?id=start-server).
You can then read out the parameters of the devices and set them individually to plausible values.
Mik55
