### ISSUE TITLE
Solar powered cameras - Does integration work with them?

### ISSUE THREAD

**Issue by noirrak** [bropat/eufy-security-ws#340]
Hello,

Does integration work properly with [SoloCam](https://www.eufy.com/collections/solar-powered-security-camera) models?
I am interested in working with the [S220](https://www.eufy.com/products/t8134121) model. 

What features are available for this model? Due to the battery power, I think that only taking a screenshot when an incident is detected, sending a screenshot at a specified time interval are enough. Live streaming for SoloCam is unnecessary.

**Comment by bropat** [comment]
https://bropat.github.io/eufy-security-client/#/supported_devices
