### ISSUE TITLE
[Bug]: eufy-ws error: Connection to Eufy Security add-on is broken, retrying in background!

### ISSUE THREAD

**Issue by martoq** [bropat/eufy-security-ws#341]
### Version

1.8.0-2

### Node version

unknown

### Operating System type

Docker

### Operating system version

Home Assistant

### Describe the bug

Eufy Websocket seems to stop answering.  The following is found in the log.  The add-on doesn't crash but the integration no longer seems to be able to communicate with the websocket.

2024-06-12 12:37:59.173	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8411P20203004CD',
  message: {
    sequence: 4,
    commandType: 1350,
    nestedCommandType: 1306,
    channel: 0,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 00 04 58 5a 59 48 46 05 c0 00 00 00 01 00 00 02 00 00 e8 ed 86 3c 77 02 a7 0b e3 ca a3 50 9b c3 1b 47 0a fe 44 b1 d1 bd 33 bf 5c 13 b6 08 d6 e3 ... 162 more bytes>
  }
}

### To reproduce

It happens within an hour of restarting the Websocket.

### Screenshots & Logfiles

2024-06-12 12:37:59.173	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8411P20203004CD',
  message: {
    sequence: 4,
    commandType: 1350,
    nestedCommandType: 1306,
    channel: 0,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 00 04 58 5a 59 48 46 05 c0 00 00 00 01 00 00 02 00 00 e8 ed 86 3c 77 02 a7 0b e3 ca a3 50 9b c3 1b 47 0a fe 44 b1 d1 bd 33 bf 5c 13 b6 08 d6 e3 ... 162 more bytes>
  }
}

**Comment by michaeleverist** [comment]
Also having the same issue shortly after restarting the container:

```
2024-06-21 22:47:50.465	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P112230112B',

  message: {
    sequence: 6,
    commandType: 1144,
    nestedCommandType: undefined,
    channel: 255,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 00 06 58 5a 59 48 78 04 00 00 00 00 01 00 ff 00 00 00>
  }
}
2024-06-21 22:47:51.016	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P112230112B',

  message: {
    sequence: 7,
    commandType: 1350,
    nestedCommandType: 1308,
    channel: 255,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 00 07 58 5a 59 48 46 05 00 01 00 00 01 00 ff 02 00 00 bf 1a 12 3d a2 d5 8f a3 e2 c9 de 59 f5 03 a6 4d 9e 1b 8e b3 1d e9 53 52 e0 36 c7 32 e3 0b ... 226 more bytes>
  }
}
```


The last error message with commandType: 1350 repeats every 10 minutes

**Comment by Tierney11290** [comment]
Following as I have this issue as well but then again, I never was able to get my doorbell camera to work. These are my logs:

`2024-07-04 20:03:46.721	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P1123210939',
  message: {
    sequence: 486,
    commandType: 1350,
    nestedCommandType: 1306,
    channel: 0,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 01 e6 58 5a 59 48 46 05 c0 00 00 00 01 00 00 02 00 00 bf b4 32 32 03 a6 56 07 68 f7 68 0b 51 5c 4a 41 65 04 9a 81 37 2c 2b e6 e3 61 bf 0d 87 2f ... 162 more bytes>
  }
}
2024-07-04 20:13:26.466	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P1123210939',
  message: {
    sequence: 488,
    commandType: 1144,
    nestedCommandType: undefined,
    channel: 255,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 01 e8 58 5a 59 48 78 04 00 00 00 00 01 00 ff 00 00 00>
  }
}
2024-07-04 20:23:27.416	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P1123210939',
  message: {
    sequence: 490,
    commandType: 1144,
    nestedCommandType: undefined,
    channel: 255,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 01 ea 58 5a 59 48 78 04 00 00 00 00 01 00 ff 00 00 00>
  }
}
2024-07-04 20:33:29.498	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P1123210939',
  message: {
    sequence: 492,
    commandType: 1144,
    nestedCommandType: undefined,
    channel: 255,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 01 ec 58 5a 59 48 78 04 00 00 00 00 01 00 ff 00 00 00>
  }
}
2024-07-04 20:43:28.547	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P1123210939',
  message: {
    sequence: 493,
    commandType: 1144,
    nestedCommandType: undefined,
    channel: 255,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 01 ed 58 5a 59 48 78 04 00 00 00 00 01 00 ff 00 00 00>
  }
}
2024-07-04 20:48:24.352	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P1123210939',
  message: {
    sequence: 494,
    commandType: 1003,
    nestedCommandType: undefined,
    channel: 0,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 01 ee 58 5a 59 48 eb 03 04 01 00 00 01 00 00 00 00 00 00 00 00 00 63 38 39 38 38 34 36 39 37 65 36 66 63 62 66 38 37 32 63 38 30 61 65 31 64 37 ... 230 more bytes>
  }
}
2024-07-04 20:49:44.061	WARN	eufy-security-ws:eufy-security-client	[p2p] [Timeout._onTimeout] Result data for command not received {
  stationSN: 'T8021P1123210939',
  message: {
    sequence: 495,
    commandType: 1004,
    nestedCommandType: undefined,
    channel: 0,
    acknowledged: true,
    retries: 0,
    returnCode: undefined,
    data: <Buffer d1 00 01 ef 58 5a 59 48 ec 03 10 00 00 00 01 00 00 02 00 00 1b f7 87 f9 ba 81 0f 91 fe ee 27 70 f9 67 1b 13>
  }
}`

**Comment by bropat** [comment]
These log entries only indicate that no feedback from the executed command was received by the device. This is about the connection between eufy-security-client and station/device. These errors have nothing to do with the websocket communication between eufy-security-ws and the Eufy integration by HomeAssistant.
