### ISSUE TITLE
speakerVolume and value: input_number

### ISSUE THREAD

**Issue by SmartM-ui** [bropat/eufy-security-ws#35]
Hi @bropat 
I was trying to create a slider for the speaker volume control, but it doesn't work and I get an error. How can I solve?

```
service: eufy_security.send_message
data:
   message: | -
     {
       "messageId": "cmdspeakerVolume",
       "command": "device.set_property",
       "serialNumber": "T8410PXXX",
       "name": "speakerVolume",
       "value": {{states (" input_number.eufy_camera_salone_speakervolume ") | round}}
     }
```
Thanks

**Comment by SmartM-ui** [comment]
> Hey @SmartM-ui , let's not mix what is the issue of home assistant and add-on. I can help you to triage if the issue is related to add on (which is home assistant independent) or custom integration specific (which is home assistant dependent).
> 
> I see that you have an error in automation while calling eufy security ws, so this looks like home assistant integration related, rather than add on.
> 
> @bropat is actually not a home assistant developer or a user

Hi @fuatakgun ,
I posted directly in the component because I think the problem depends on him and not on the home assistant. 
Leaving aside the automation I posted to have an additional information log, the problem occurs when the command "messageId": "cmdspeakerVolume" is launched, reported in the @bropat add-on.

Were you able to understand the problem or does it have to be written some other way?

If it's not a problem with the add-on, I apologize for opening this request :-)

Congratulations again to both of you for the excellent work

**Comment by bropat** [comment]
I am closing this issue as it is not a bug in eufy-security-ws.
