### ISSUE TITLE
[Feature request]: E340 "Enable Floodlight" not to be confused with Light On

### ISSUE THREAD

**Issue by barney34** [bropat/eufy-security-ws#354]
### Describe the solution you'd like

Would it be possible to add enable/ disable to the Floodlight for the E340. There are times when we are in the backyard when we still need recording of activity at the pool but dont need the flood. It would be great if I could turn off the floodlight when say our pool pump is on via a Homeassistant automation or motion activated illumination toggle if motion and pool is on turn off flood.  The option is under E340 "Light Settings"  Enable Floodlight which is different than light "On"

**Comment by bropat** [comment]
> The option is under E340 "Light Settings" Enable Floodlight which is different than light "On"

This functionality is already available (property `lightSettingsEnable`).
