### ISSUE TITLE
[Question]: I try to set the GuardMode. Result is unknown_command

### ISSUE THREAD

**Issue by scarefirego** [bropat/eufy-security-ws#361]
### Ask your question

HI,
what is wrong. I cant change the guard Mode? Connection is true.

**This is from client**

/eufy-security> station.set_guard_mode T8030P23XXXXXX 2
eufy-security> 
{
  type: 'result',
  success: false,
  messageId: 'set_guard_mode'
  errorCode: 'unknown_command'
}
eufy-security> 

**This is from server**

 StationNotFoundError  Station doesn't exists, , [object Object], StationNotFoundError
error stack:
  • eufysecurity.js     EufySecurity.getStation
        /home/pi/eufy/node_modules/eufy-security-ws/node_modules/eufy-security-client/build/eufysecurity.js:448
  • message_handler.js  StationMessageHandler.handle
        /home/pi/eufy/node_modules/eufy-security-ws/dist/lib/station/message_handler.js:8
  • server.js   Object.station
        /home/pi/eufy/node_modules/eufy-security-ws/dist/lib/server.js:31
  • server.js   Client.receiveMessage
        /home/pi/eufy/node_modules/eufy-security-ws/dist/lib/server.js:94
  • server.js   WebSocket.<anonymous>
        /home/pi/eufy/node_modules/eufy-security-ws/dist/lib/server.js:43
  • events      WebSocket.emit
        events:519
  • domain      WebSocket.emit
        domain:488
  • websocket.js        Receiver.receiverOnMessage
        /home/pi/eufy/node_modules/eufy-security-ws/node_modules/ws/lib/websocket.js:1220
  • events      Receiver.emit

**This command works fine:**
station.get_properties T8030P23XXXXXXX

thx

**Comment by bropat** [comment]
Please read the [docs](https://bropat.github.io/eufy-security-ws/#/api_cmds?id=set-guard-mode).
