### ISSUE TITLE
[Question]: How to start streaming a battery powered camera?

### ISSUE THREAD

**Issue by jayjoshi64** [bropat/eufy-security-ws#362]
### Ask your question

I have battery powered Eufy 2C.   When I check the dashboard or device, it's always off since there are no events triggering record.

To start seeing video for a small time, I started calling "Start RSTP Streaming" event.  But it takes 2-5 minutes to start the stream.   

Is there a better / faster way to start streaming for battery powered devices?

context: I am using Home assistant to control the devices & frigate to view the live feed.  but mostly the question is about how to trigger the streaming faster using this library.

**Comment by bropat** [comment]
Wrong repo.

Look [here](https://github.com/fuatakgun/eufy_security?tab=readme-ov-file#2-install-go2rtc-add-on).
