### ISSUE TITLE
How to set Guard Mode to "geofencing" like in the app

### ISSUE THREAD

**Issue by guny74** [bropat/eufy-security-ws#38]
Hello,

I tried to set the guard mode "to geofencing control", but I did not find the right command.

Any hint ?

Thank you

**Comment by bropat** [comment]
@guny74 

What did you try?

**Comment by guny74** [comment]
Hello,

I want from my smarthome system (with node red <-> eufy-security-ws) switch between the different modes based on the selected "alarm level". One Scenario is to switch back to the "geofencing mode" via the smarthome system.

**Comment by bropat** [comment]
Using the command [station.set_guard_mode](https://github.com/bropat/eufy-security-ws#set-guard-mode) with mode `47`.

Possible values:

```
AWAY = 0
HOME = 1
DISARMED = 63
SCHEDULE = 2
GEO = 47
CUSTOM1 = 3
CUSTOM2 = 4
CUSTOM3 = 5
OFF = 6           => only supported if there is a keypad
```

**Comment by guny74** [comment]
Thank you, thatworks for me.

Are these values documented in the project and I only didn't find it ?

**Comment by bropat** [comment]
No, there's not much documentation at the moment...
