### ISSUE TITLE
How to delete events/videos or how to actove person detection without video capture

### ISSUE THREAD

**Issue by guny74** [bropat/eufy-security-ws#39]
Hello,

first I tried to activate (via api and APP) person detection without video catupture. Without success.

So my next idea was so delete "old" events/video via this api like in the app... but found nothing 
Any hint ?

Thank you

**Comment by bropat** [comment]
@guny74 

> first I tried to activate (via api and APP) person detection without video catupture. Without success.

What did you try?

> So my next idea was so delete "old" events/video via this api like in the app... but found nothing
Any hint ?

This functionality has not yet been implemented. Thus, it is not possible today.

**Comment by guny74** [comment]
I want to get the event "person detected" to my smarhome system  (Node red <-->eufy-security-ws) the hole day and  decide there based on the "alarm level". So I want to protocol if persons are detected, e.g. to switch light on (not for other motions) or something else.... but I want not to span the "event log in the app" or the video storage.

**Comment by bropat** [comment]
> but I want not to span the "event log in the app" or the video storage.

This functionality has not yet been implemented. Thus, it is not possible today.

**Comment by guny74** [comment]
Ok, Thank you for the response
