### ISSUE TITLE
Stop RTSP Live Stream Function error

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-ws#40]
**Describe the bug**  
When calling `stop_rtsp_livestream`, docker throws error as 
```
 ERROR Station stop rtsp livestream error (station: T8010N2320460480 channel: -1)
 DeviceNotFoundError  No device with channel -1 found on station with serial number: T8010N2320460480!
details:
{
  name: 'DeviceNotFoundError'
}
error stack:
• eufysecurity.ts:280 getStationDevice
    node_modules/eufy-security-client/src/eufysecurity.ts:280:15
• eufysecurity.ts:1081 onStopStationRTSPLivestream
    node_modules/eufy-security-client/src/eufysecurity.ts:1081:33
• eufysecurity.ts:341 <anonymous>
    node_modules/eufy-security-client/src/eufysecurity.ts:341:95
• events.js:400 emit
    events.js:400:28
• station.ts:475 onStopRTSPLivestream
    node_modules/eufy-security-client/src/http/station.ts:475:14
• station.ts:62 <anonymous>
    node_modules/eufy-security-client/src/http/station.ts:62:81
• events.js:400 emit
    events.js:400:28
• session.ts:1444 endRTSPStream
    node_modules/eufy-security-client/src/p2p/session.ts:1444:18
• session.ts:561 _sendCommand
    node_modules/eufy-security-client/src/p2p/session.ts:561:26
• session.ts:436 sendQueuedMessage
    node_modules/eufy-security-client/src/p2p/session.ts:436:22
```

Steps
- Enable RTSP streaming on a camera
- `{"messageId": "start_rtsp_livestream", "command": "device.start_rtsp_livestream", "serialNumber": "T8113N63205018FC"}`
- Call start rtsp live stream function and wait for `rtsp livestream started` event
- `{'type': 'event', 'event': {'source': 'device', 'event': 'rtsp livestream started', 'serialNumber': 'T8113N63205018FC'}}`
- Call stop rtsp live stream function and wait for `rtsp livestream stopped` event
- Rather, it is generating the error in docker but it is actually halting the stream, it is not playable anymore.

**Expected behavior**  
Do not throw and error and fire `rtsp livestream stopped` event to client

**Versions:**  
 - Client version: eufy-security-ws 0.5.1

**Additional context**  
Related issue: https://github.com/fuatakgun/eufy_security/issues/59

**Comment by bropat** [comment]
@fuatakgun 

This is a bug in the eufy-security-client library. It will be fixed in version 1.2.2.
In eufy-security-ws it will be fixed with version 0.5.2.

**Comment by fuatakgun** [comment]
when do you plan to publish new version? I will plan accordingly to publish new version of integration either relying on enabling/disabling RTSP (as it is for today) or starting/stopping RTSP livestream.

**Comment by bropat** [comment]
It depends on the issue #15. Whether it is effectively still a bug or not.

**Comment by bropat** [comment]
@fuatakgun 

Have now published the new version.

**Comment by fuatakgun** [comment]
thanks, checking now
