### ISSUE TITLE
Enabling RTSP vs Starting RTSP Stream

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-ws#41]
I am walking in corner/dangerous cases now, but I would like to know your opinion on this.
- enabling RTSP - enables rtsp support for a specific device and starts the stream by itself.
- start RTSP live stream - starts the stream
When you enable RTSP, there is no `rtsp livestream stopped` and `rtsp livestream finished` events, which would make sense, as we are not directly controlling them. For couple of minutes, streaming continues and you will not be able to stop the stream as it is not registered internally to us and you will not be able to start one, as there is already ongoing one.

Can you block starting the stream when it is being enabled? so, these functions would become totally unique without overlapping functionalities. There might be software level limitation from eufy on this.

**Comment by bropat** [comment]
Unfortunately, my hands are tied here. In the Eufy App, 2 commands are sent in succession when RTSP is activated:

1. enable rtsp
2. start rtsp stream

I only execute the 1st command when activating and the 2nd command when starting the stream.

Furthermore, I do not get a message that an RTSP stream is already active or not. There is 0 control here...
