### ISSUE TITLE
arm/disarm status stops working after some time for my indoor pan&tilt cameras.

### ISSUE THREAD

**Issue by zadigre** [bropat/eufy-security-ws#42]
the arm/disarm status stops updating after some time for my indoor cameras in home assistant.
If I open the Eufy app on my iPhone, it will updated immediately in home assistant. but will not update for any change after that. 
If I restart the the Eufy Security Integration, it will start working again... but will eventually fail again. 

1. restart Home Assistant or the Eufy Security integration
2. wait a few hours. 

apparently the push token is expiring. 
here's the log for the eufy_security_addon:
Error FID Token renewal failed with error: Bad Request
error stack:
• service.ts:131 renewFidToken
node_modules/eufy-security-client/src/push/service.ts:131:23
• service.ts:155 renewPushCredentials
node_modules/eufy-security-client/src/push/service.ts:155:45
• service.ts:491 _open
node_modules/eufy-security-client/src/push/service.ts:491:32
• service.ts:510 
node_modules/eufy-security-client/src/push/service.ts:510:17
2021-11-06 14:55:08.878 ERROR Push credentials renew Error:
Error FID Token renewal failed with error: Error: FID Token renewal failed with error: Bad Request
error stack:
• service.ts:135 renewFidToken
node_modules/eufy-security-client/src/push/service.ts:135:19
• service.ts:155 renewPushCredentials
node_modules/eufy-security-client/src/push/service.ts:155:45
• service.ts:491 _open
node_modules/eufy-security-client/src/push/service.ts:491:32
• service.ts:510 
node_modules/eufy-security-client/src/push/service.ts:510:17
2021-11-06 14:55:08.886 ERROR Push notifications are disabled, because the registration failed!

I'm running everything on the latest home assistant OS 6.6, core-2021.11.1, supervisor-2021.10.8

**Comment by fuatakgun** [comment]
Docker version is 0.3.3, we can wait maybe till updating version inside HA

**Comment by zadigre** [comment]
should I wait or there's an an easy way to update to the latest non officially released version. (I don't like to do manual things... yes I'm lazy 😀)
I in the meantime, I can also add an automation to restart the integration every few hours.

**Comment by zadigre** [comment]
My indoor camera stopped updating even after restarting integration or HA. Is this an issue with 0.3.3 that may be fix when it will be updated to a newer version?

**Comment by fuatakgun** [comment]
restarting integration or restarting HA will not restart add-on. you have to restart add-on independently using supervisor.

**Comment by zadigre** [comment]
I restarted the add-on multiple times. it does essentially nothing for the past two days. Eufy may have changed something on their side.
I was somewhat able to make it work for a few hours before by restarting the integration... but it stopped working yesterday or the day before. 
I updated the integration yesterday night. still same problem. 
in the mean time, to force a refresh of the status, I reload the integration every time one of my automation is changing the arm/disarm status of my camera.

/edit
as I was writing this, I tried it again. and now it works fine. but it will probably eventually stop working after a few minutes or hours. 
No notification on state change on these cameras is not helping at all.

**Comment by zadigre** [comment]
hello again!

just to let you know, I removed the RTSP add-on, disabled RTSP on all my cameras in the Eufy App (but it reenabled itself after a few minutes/seconds on my indoor cameras), restarted all cameras... and now it's working fine. I didn't have to restart the integration or add-on after more than 12 hours and I don't see any errors in the log.

**Comment by zadigre** [comment]
hello again. 
I installed the 2021.11.3 update and status wasn't updating after the reboot. 
I just restart my two indoor cameras... and it started working fine after that. 
in the add-on log, I see a disconnect (when rebooting the camera) and reconnect (after cameras have finished rebooting). 
no errors before these events.

**Comment by bropat** [comment]
@zadigre 

Is this behaviour present in the current version (0.5.2)?

**Comment by zadigre** [comment]
@bropat 
I believe it works better... I didn't experience the problem yet. 
but it may or may not have something to do with 0.3.3 or now 0.5.2 since the problem was resolved by rebooting my two cameras. or maybe this reboot forced some kind of "update" in 0.3.3.
that said, some warning that were in the logs are not longer there... which is good.

but now I'm seeing things like that... 
How can I clear the host list so it doesn't try to connect to some other previous ip and takes more time to reconnect ?(I now have fixed IP address for my cameras). 
2021-11-16 06:01:13.762  WARN Station T8410P2020283CE8 - Heartbeat check failed. Connection seems lost. Try to reconnect... 
2021-11-16 06:01:13.767  INFO Disconnected from station T8410P2020283CE8 
2021-11-16 06:01:48.921  WARN Station T8410P2020283CE8 - Tried all hosts, no connection could be established 
2021-11-16 06:01:48.924  INFO Timeout connecting to station T8410P2020283CE8 
2021-11-16 06:02:28.957  WARN Station T8410P2020283CE8 - Tried all hosts, no connection could be established 
2021-11-16 06:02:28.959  INFO Timeout connecting to station T8410P2020283CE8 
2021-11-16 06:03:03.967  ERROR P2PClientProtocol.lookup(): station: T8410P2020283CE8 - All address lookup tentatives failed. 
2021-11-16 06:03:03.970  INFO Timeout connecting to station T8410P2020283CE8 
2021-11-16 06:03:34.021  INFO Connected to station T8410P2020283CE8 on host 192.168.25.112 and port 29166
