### ISSUE TITLE
issues on docker container

### ISSUE THREAD

**Issue by LucaBors** [bropat/eufy-security-ws#43]
Hi, 
just installed the container and hopefully i'm doing something wrong. Server is up and i can connect at port 3000 but no device is showed.
When i look and the container log i see: 
    _currentUrl: 'https://mysecurity.eufylife.com/api/v1/passport/login',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
error stack:
• dns.js:71 onlookup
    dns.js:71:26

2021-11-08 11:37:45.088  ERROR Status return code not 200 
{
  status: undefined,
  statusText: undefined
}
2021-11-08 11:37:45.089  ERROR Token error 

Can you please help?
Thank you!

**Comment by bropat** [comment]
This is a container network problem. In the error above you can see a DNS resolution problem.
