### ISSUE TITLE
Multiple RTSP streams are not managed

### ISSUE THREAD

**Issue by bropat** [bropat/eufy-security-ws#45]
Created for tracking issue: https://github.com/bropat/eufy-security-client/issues/63

**Comment by fuatakgun** [comment]
hi @bropat , anything pending on me for this?

**Comment by bropat** [comment]
This problem should now be solved. You are welcome to test it and if necessary write here if the problem has not yet been solved.

**Comment by fuatakgun** [comment]
I missed that it has been resolved, my bad, thanks
