### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by sanderjohan** [bropat/eufy-security-ws#46]
Hi,

I am trying to get the Eufy Security Add-on working and I get the following log:

2021-11-19 20:39:27.076 INFO Authentication properties changed, invalidate saved cloud token.
2021-11-19 20:39:27.090 INFO Eufy Security server listening on port 3000
2021-11-19 20:39:27.846 INFO Switching to another API_BASE (https://security-app-eu.eufylife.com/v1) and get new token.
2021-11-19 20:39:27.901 ERROR Status return code not 200
{
status: 204,
statusText: 'No Content'
}
2021-11-19 20:39:27.904 ERROR Token error

Any idea what to do?

**Comment by Malnes** [comment]
I have the same issue. My guess is that the url is wrong. I tried to run some http requests to the eufy api a coupe of months ago, and I had to change the url for it to work. I cant find the script i made, and dont remember what the new url was. I guess by your username that you have set he country to NO aswell.

**Comment by Malnes** [comment]
seems the error is with bropat/eufy-security-client   

https://github.com/bropat/eufy-security-client/issues/67

**Comment by danstreeter** [comment]
I had this error (Running in Docker) and changed my `COUNTRY` env var from `GB` to `gb` which enabled it to get past this inital step, getting different errors now but at least got past that one.

**Comment by AnthoPakPak** [comment]
Hey, I've just updated `eufy-security-ws` (v. 0.6.0) (and `eufy-security-client` (v. 1.4.0)) and I'm still facing this issue. I've tried removing my `persistent.json` file but it didn't helped either. Is there anything else I should do?
