### ISSUE TITLE
Docker Container 0.5.1 and above crashes during start 

### ISSUE THREAD

**Issue by guny74** [bropat/eufy-security-ws#47]
**Describe the bug**  
I tried to update to one of the newest versions 0.5.4 of the docker container,
but durcng start it crashes with fatal error.
I tried 0.5.1 ,  0.5.2, 0.5.3 ...all the same

Image 0.5.0 does not crash but get the known "token error"

```
Fatal error in , line 0

 unreachable code
FailureMessage Object: 0xffe6c8ac

Illegal instruction (core dumped)

```

**To Reproduce**  
Start the Docker container

**Expected behavior**  

**Screenshots & Logfiles**  

**Versions:**  
 -docker container 0.5.1 - 0.5.4
- Operating system: debian buster

**Comment by skrobul** [comment]
This is bigger problem with alpine version of nodejs - the only way I was able to get it working was to rebuild my own docker image using `node:14.17.6-alpine3.12` instead of `node:14-alpine` as a source. This was on the armv7 architecture.

**Comment by guny74** [comment]
Thank you for sharing your image. I will use it, to get it run again. If I have a little bit more time, I will build my own.

**Comment by bropat** [comment]
@skrobul 

`eufy-security-ws` is also compatible with node 16. Have you already tested `node:16-alpine`? If it works for you, I could update the Docker image to use `node:16-alpine`.

Please let me know.

**Comment by skrobul** [comment]
@bropat I attempted to, but failed miserably. After changing the source image to `node:16-alpine`, the second/production stage of a build [insists on running the `npm run build` again](https://gist.github.com/skrobul/9eda8054c364c25cfe03888d880891a7) - obviously `tsc` is not available in the production stage, so it fails. For troubleshooting, I have tried following:
* deleting `package-lock.json` and rebuilding it locally with Node v16
* updating `Dockerfile` to run `NODE_ENV=production npm ci --only=production` instead of just `npm ci --only=production`

Will try to play around some more with it later on, but if you have any other suggestions in the meantime I'm all ears :)

**Comment by bropat** [comment]
@skrobul

Try `eufy-security-ws:0.6.0` and let me know.

**Comment by skrobul** [comment]
@bropat broken in a same way as previous:
```
❯ docker ps -a | egrep 'IMAGE|eufy-security-ws'
CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                        PORTS                                                                                                                                                        NAMES
c983bc19e583   bropat/eufy-security-ws:0.6.0                     "docker-entrypoint.s…"   19 minutes ago   Exited (133) 19 minutes ago                                                                                                                                                                homeassistant_eufy-security-ws_1



❯ docker-compose logs eufy-security-ws
Attaching to homeassistant_eufy-security-ws_1
eufy-security-ws_1  |
eufy-security-ws_1  |
eufy-security-ws_1  | #
eufy-security-ws_1  | # Fatal error in , line 0
eufy-security-ws_1  | # unreachable code
eufy-security-ws_1  | #
eufy-security-ws_1  | #
eufy-security-ws_1  | #
eufy-security-ws_1  | #FailureMessage Object: 0xbec8f58c
eufy-security-ws_1  | Trace/breakpoint trap (core dumped)
```

**Comment by bropat** [comment]
@skrobul 

Can you try to use the image `16-slim` and let me know if it works for you?
If so, I will switch to this image for `eufy-security-ws`. ;)

**Comment by skrobul** [comment]
@bropat I believe this won't be necessary - it will work on the alpine image if you pin it specifically to `node:16-alpine3.12` or even more specifically `node:16.3.0-alpine3.12`.

Your current base image resolves to `node:16-alpine3.14` which causes the problem, moving to 3.12 should fix it.

Snippet below explains in more detail what is the problem

<details>

```
skrobul@pi4:~ $ docker run --rm node:16-alpine3.14 npm -v




#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbec8063c
skrobul@pi4:~ $ docker run --rm node:16-alpine3.13 npm -v


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbe8a1644
skrobul@pi4:~ $ docker run --rm node:16-alpine3.12 npm -v
8.1.0
skrobul@pi4:~ $
```
</details>



Of course the `-slim` image works too, but it's almost 50% larger and probably has more vulnerabilities down the line.

**Comment by skrobul** [comment]
For anyone ending up here from a search engine, you can find more details about this bug [here](https://github.com/Koenkk/zigbee2mqtt/issues/7662#issuecomment-853146458).

**Comment by bropat** [comment]
Since 3.13 Alpine requires the following on the host OS (https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements):

* Docker 19.03.9 or newer
* libseccomp 2.4.2 or newer

Have you checked whether you are complying with these requirements?

**Comment by ticknert** [comment]
This may not be a true fix, but adding `privileged: true` to my docker-compose file fixed this problem for me. My full docker-compose file is as follows:
```
version: '3'
services:
  eufy-security-ws:
    environment:
      - 'USERNAME=${EUFY_USERNAME}'
      - 'PASSWORD=${EUFY_PASSWORD}'
    ports:
      - '3000:3000'
    image: 'bropat/eufy-security-ws:0.5.5'
    restart: unless-stopped
    privileged: true
```

**Comment by skrobul** [comment]
> Have you checked whether you are complying with these requirements?

I did, and the libseccomp2 version was older (I believe the newest one in debian buster is 2.3.4), so upgrading it to the backported version is a decent workaround. It's just that having to upgrade the host system for something needed in the container feels entirely wrong.  Technically the Debian buster is going to be supported until 2024, so still should be good for another 2 years or so.

Just to confirm that this is the problem we've seen above, I have implemented workaround on my system.
In case anyone needs it, here's how to do it if you happen to run Debian Buster on Raspberry Pi or similar: 

```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list

sudo apt update && sudo apt install libseccomp2 -t buster-backports
```

and now the newer alpine image works correctly:
```
skrobul@pi4:~ $ docker run --rm node:16-alpine3.13 npm -v
8.1.0
skrobul@pi4:~ $
```

**Comment by guny74** [comment]
is there again a docker image running out of the box ?

**Comment by bropat** [comment]
@guny74 

The problem is with the host (outdated libraries!) and not with the Docker image.

**Comment by Beer17HWAM** [comment]
> > Have you checked whether you are complying with these requirements?
> 
> I did, and the libseccomp2 version was older (I believe the newest one in debian buster is 2.3.4), so upgrading it to the backported version is a decent workaround. It's just that having to upgrade the host system for something needed in the container feels entirely wrong. Technically the Debian buster is going to be supported until 2024, so still should be good for another 2 years or so.
> 
> Just to confirm that this is the problem we've seen above, I have implemented workaround on my system. In case anyone needs it, here's how to do it if you happen to run Debian Buster on Raspberry Pi or similar:
> 
> ```shell
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
> echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
> 
> sudo apt update && sudo apt install libseccomp2 -t buster-backports
> ```
> 
> and now the newer alpine image works correctly:
> 
> ```
> skrobul@pi4:~ $ docker run --rm node:16-alpine3.13 npm -v
> 8.1.0
> skrobul@pi4:~ $
> ```

I have:
ii  libseccomp2:armhf                    2.3.3-4                                 armhf        high level interface to Linux seccomp filter

Do I have to do the same thing? I have this problem:

pi@raspberrypi4:~ $ docker run -it --privileged -e USERNAME=[xx@debeertjes.com](mailto:xx@debeertjes.com) -e PASSWORD=xxxx -p 3300:3000 bropat/eufy-security-ws:latest
2022-02-06 13:30:13.737  INFO  Eufy Security server listening on host 0.0.0.0, port 3000
2022-02-06 13:30:16.033  ERROR MQTT Error
 Error  Connection refused: Not authorized
details:
{
  code: 5
}
error stack:
• client.js:1386 MqttClient._handleConnack
    node_modules/mqtt/lib/client.js:1386:17

• client.js:547 MqttClient._handlePacket
    node_modules/mqtt/lib/client.js:547:12

• client.js:436 work
    node_modules/mqtt/lib/client.js:436:12

• client.js:450 writable._write
    node_modules/mqtt/lib/client.js:450:5

• _stream_writable.js:409 doWrite
    node_modules/readable-stream/lib/_stream_writable.js:409:139

• _stream_writable.js:398 writeOrBuffer
    node_modules/readable-stream/lib/_stream_writable.js:398:5

• _stream_writable.js:307 Writable.write
    node_modules/readable-stream/lib/_stream_writable.js:307:11

• readable:754 ondata
    node:internal/streams/readable:754:22

• node:events:390 emit
    node:events:390:28

• readable:315 addChunk
    node:internal/streams/readable:315:12


2022-02-06 13:30:16.074  INFO  MQTT connection closed
2022-02-06 13:30:17.174  INFO  No stations found.
2022-02-06 13:30:17.708  INFO  No devices found.
2022-02-06 13:30:17.735  INFO  Push notification connection successfully established
