### ISSUE TITLE
Camera 2C has no image

### ISSUE THREAD

**Issue by skank01** [bropat/eufy-security-ws#48]
I think the issue is announced in version 5.0
Entity picture (url) is not showing anything , i get an internal server error and/or the entity inside HA isnt showing any picture/thumbnail

camera is T8114
I'm on last version of ws

**Comment by fuatakgun** [comment]
Can you validate if you have pictureUrl attribute in camera state?

**Comment by bropat** [comment]
Look [here](https://github.com/fuatakgun/eufy_security/issues/70#issuecomment-971371006):

> "Picture URL" is based on the cover_path attribute of the Eufy Cloud response. In your case this attribute is missing and therefore I cannot do anything here. I'm sorry.

**Comment by skank01** [comment]
Yes the attribute is there
[url=https://imgbb.com/][img]https://i.ibb.co/bzf1rNG/camera.jpg[/img][/url]

However, it worked before, its after new version of addons, it doesnt work anymore

**Comment by bropat** [comment]
This is something that is not related to eufy-security-ws or eufy-security-client. If the attribute is missing in eufy-security-ws, it is because the Eufy Cloud response no longer contains the `cover_path` attribute for some reason (already happened with others; Eufy problem).

**Comment by skank01** [comment]
The attribute isnt missing, its just not showing

Ok, guess then it can be closed here, but fuatakgun needs to look into it?
not sure?

**Comment by bropat** [comment]
On my site, this attribute is forwarded 1:1 from the Eufy Cloud response. There is no change here. If it is only not visible in @fuatakgun's integration, then you need to open an issue on his project. Otherwise, nobody can do anything here... ;)

**Comment by fuatakgun** [comment]
I will make this clearer in my repository, how to find correct repository for any further issues.

@skank01 , can you access pictureUrl address  from browser? Sometimes, eufy generates non accessible urls for me, but it happens very rarely

**Comment by skank01** [comment]
> I will make this clearer in my repository, how to find correct repository for any further issues.
> 
> @skank01 , can you access pictureUrl address from browser? Sometimes, eufy generates non accessible urls for me, but it happens very rarely

No i get that error when accessing the pictureUrl
But its all the time with latest version from 5.0 and up
Before it was ok

**Comment by bropat** [comment]
I looked into this and found out that if you request the url with HTTP 2.0, no more errors occur. I think the Eufy Cloud sometimes has a problem with HTTP 1.0/1.1 requests (typical error is HTTP error code 204 - No content).

With the last update of the eufy-security-client library I have already changed everything to HTTP 2.0 (if supported).

Long story short, the problem is not with this project. ;)

**Comment by skank01** [comment]
Bropat,
When using picture url i get this error:

<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>

When using entity picture , i get :
500: Internal Server Error


The picture url is pointing to amazonaws

**Comment by fuatakgun** [comment]
@bropat did you already release a new version of Eufy security ws including this fix? (0.6.0)

**Comment by bropat** [comment]
> @bropat did you already release a new version of Eufy security ws including this fix? (0.6.0)

There's nothing to fix. I can't fix the Eufy Cloud ;)

**Comment by fuatakgun** [comment]
I see, currently, http 2.0 is used but sometimes eufy might require http 1.0/1.1 and there is nothing we can do about it? I might have lost in details

**Comment by skank01** [comment]
If eufy requires 1.0 or 1.1 why dont we use those then bropat?
