### ISSUE TITLE
Cameras all unavailable

### ISSUE THREAD

**Issue by boctok** [bropat/eufy-security-ws#49]
**Describe the bug**  
Although they were working fine before, none of my cameras are available. After checking the logs for the add-on, I see: 

`Restarted HA
Restarted add-on
Log:
2021-11-22 23:06:31.890 INFO Eufy Security server listening on port 3000 2021-11-22 23:06:36.321 INFO Connected to station T8400XXXXXXXXXXX on host 192.168.86.47 and port 27574 2021-11-22 23:06:36.346 INFO Connected to station T8410XXXXXXXXXXX on host 192.168.86.52 and port 13210 2021-11-22 23:06:36.383 INFO Connected to station T8010XXXXXXXXXXX on host 192.168.86.22 and port 21326 2021-11-22 23:06:36.416 INFO Connected to station T8021XXXXXXXXXXX on host 192.168.86.67 and port 14910 2021-11-22 23:06:36.457 INFO Connected to station T8410XXXXXXXXXXX on host 192.168.86.33 and port 20757 2021-11-22 23:06:36.991 INFO Push notification connection successfully established 2021-11-22 23:06:41.240 INFO Connected to station T8124XXXXXXXXXXX on host 192.168.86.26 and port 16848`

Then after a minute or two:

`2021-11-22 23:06:50.980 INFO Disconnected from station T8124XXXXXXXXXXX 2021-11-22 23:06:52.180 ERROR P2PClientProtocol.lookup(): station: T8401XXXXXXXXXXX - All address lookup tentatives failed. 2021-11-22 23:06:52.181 INFO Timeout connecting to station T8401XXXXXXXXXXX 2021-11-22 23:07:12.189 ERROR P2PClientProtocol.lookup(): station: T8401XXXXXXXXXXX - All address lookup tentatives failed. 2021-11-22 23:07:12.191 INFO Timeout connecting to station T8401XXXXXXXXXXX 2021-11-22 23:07:37.197 ERROR P2PClientProtocol.lookup(): station: T8401XXXXXXXXXXX - All address lookup tentatives failed. 2021-11-22 23:07:37.198 INFO Timeout connecting to station T8401XXXXXXXXXXX 2021-11-22 23:08:12.200 ERROR P2PClientProtocol.lookup(): station: T8401XXXXXXXXXXX - All address lookup tentatives failed. 2021-11-22 23:08:12.201 INFO Timeout connecting to station T8401XXXXXXXXXXX 2021-11-22 23:08:57.204 ERROR P2PClientProtocol.lookup(): station: T8401XXXXXXXXXXX - All address lookup tentatives failed. 2021-11-22 23:08:57.205 INFO Timeout connecting to station T8401XXXXXXXXXXX`

**To Reproduce**  
1. Just rebooting HA.

**Expected behavior**  
Sorta expected to see my cameras

**Screenshots & Logfiles**  
Logfiles posted above.

**Versions:**  
 - Adapter version: ?
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: Home Assistant Eufy Security Add-on 0.5.5

**Additional context**

**Comment by bropat** [comment]
What I understand from your logs is this:

* You have a Eufy Solo S40 camera. With this camera it is normal that after a short time the P2P connection is disconnected. This is a standalone battery camera, if this were not the case your camera would not last 1 day ;)
* You also have a station (T8010) and the connection is maintained. This is also ok.
* You have an Eufy Solo IndoorCam C22. I have never tested this camera myself. Here it is not normal that no stable P2P connection is established. I would need access to understand what the problem is.

Could you share your device with me on one of the following accounts:

* patrick.broetto+eu1@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

Let me know.

**Comment by boctok** [comment]
I ended up uninstalling everything, restarting several times, and then reinstalling from scratch and now, it seems for the time being, everything is working again.

As to your above points, yes, I have an S40 battery camera which also has solar. The Solo IndoorCam is powered. The connection drops well within 30 seconds after a restart of the add-on. As soon as it does this, I lose "all" of my cameras. Not just the Solo cams.

I don't have cards set up so that the video is streaming continuously. Only when I click on them.

Not trying to sound like a jerk, but I didn't buy security cameras to share them.

I guess I'll just go with it for now.
