### ISSUE TITLE
How to use captcha implementation

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-ws#50]
I see that you have quickly implemented captcha support in WS, i am trying to catch up with it :-) thanks for quick implementation

So, when docker is starting up, it tries to login and generates captcha request event so client can send the captcha. In home assistant case, docker is always running in background and integration is connected to it later on.

Please help me to find answers for these;
- are you sending captcha required events to clients who had connected after event is generated or client should connect before captcha event?
- if client required to be connected before captcha event is generated, can i restart the sequence with a command by client, so client can get captcha event after sending a restart/reconnect request?

**Comment by bropat** [comment]
> are you sending captcha required events to clients who had connected after event is generated or client should connect before captcha event?

The client should already be connected. I don't cache the events, because in the example of the captcha, the captcha is only valid for certain seconds and this would have to be managed.

> if client required to be connected before captcha event is generated, can i restart the sequence with a command by client, so client can get captcha event after sending a restart/reconnect request?

Yes, if the client is not yet connected, you can send the command `driver.connect` and initiate a reconnection.

**Comment by fuatakgun** [comment]
thanks
