### ISSUE TITLE
Auth Issue

### ISSUE THREAD

**Issue by dsheard** [bropat/eufy-security-ws#51]
When running on docker, I get this issue. Using latest docker image. Username and password is correct. Have tried disabling 2fa

<img width="776" alt="image" src="https://user-images.githubusercontent.com/1242601/143506528-87bdc157-5f60-485c-9974-ce725c9c531d.png">

**Comment by bropat** [comment]
As already described in the release: https://github.com/bropat/eufy-security-ws/releases/tag/0.5.5

When updating from a version lower than 0.5.5 to 0.5.5 or higher, this applies:

```
Note: If you have 2FA enabled, you will need to authenticate again after this update.
```

**Comment by Gelix** [comment]
@bropat Can you expand on what "authenticate again" entails?  Everything I have tried is resulting in the same clip as @dsheard above.

**Comment by bropat** [comment]
@Gelix 

Sorry, you are right. 
I have several projects and overlooked the fact that for this project, at the moment, the following is necessary:

* Delete the file `persistent.json` and restart the eufy-security-ws Docker container.

**Comment by Gelix** [comment]
> @Gelix
> 
> Sorry, you are right. I have several projects and overlooked the fact that for this project, at the moment, the following is necessary:
> 
> * Delete the file `persistent.json` and restart the eufy-security-ws Docker container.

Thank you!  This did fix it for me.
