### ISSUE TITLE
T8020 Wi-Fi Doorbell Chime & T8220 Doorbell 1080p Camera support?

### ISSUE THREAD

**Issue by RichardRHM** [bropat/eufy-security-ws#52]
Hi bropat, great work done with the integrations. :-) 

I think I encountered a (new) Eufy product that is not added yet?
The T8020 Wi-Fi doorbell chime & T8220 doorbell combination.
It also does not appear in your list of devices.

I encountered this in my installation process with fuatakgun's Home Assistant add-on.
I did the setup exactly as described, but in the logs it says:
2021-11-28 11:04:43.297 INFO Eufy Security server listening on port 3000
2021-11-28 11:04:44.995 INFO No stations found.
2021-11-28 11:04:45.125 INFO No devices found.
2021-11-28 11:04:45.894 INFO Push notification connection successfully established
They are on the same network as my HA device.
Looks like the account is also connected properly.

Type number WiFi chime: T8020P10212301D6, Wi-Fi Doorbell Chime
Type number doorbell: T8220P6021210810, Battery doorbell 1080P
Manufacturer Part Number (MPN) for this set: E8220311

It looks the same as the T8222 model, only the number is different: T8220.

If you would like to add the product and need some data, let me know how I can be of assistance. 

Greetings, Richard

**Comment by bropat** [comment]
Hi Richard,

thank you.

Regarding your problem, the cause lies in the sharing of the devices. Regardless of whether the device is supported or not, it should still appear as a station or device.
Therefore, I suggest you to share the devices again with admin rights and then try again.

**Comment by RichardRHM** [comment]
Hi Bropat,

Thanks for the reply, really appreciate it.

After adding again it still did not work, but after that I switched from my second to my first account and that worked like a charm. Switching back to the second account, device found again. No idea why it was not working the first time, but nice! :-)

Thanks again!

Greeting, Richard
