### ISSUE TITLE
Trigger doorbell/camera to start recording (by for example hue outdoor motion sensor) 

### ISSUE THREAD

**Issue by rickleka** [bropat/eufy-security-ws#58]
Is there an option (send msg?) to trigger the doorbell to start recording?

For example, doorbell normally triggers on motion/persons within 5 meters. Having a hue outdoor motion sensor at the entrance of my yard at 12 meters. Would be nice to have the option to send a command to the doorbell to start recording.
Eufy suggests a similar solution with their own motion detector so maybe it is possible with some commands already..

so a third party (hue) motion sensor in HA can trigger a recording that I can see in the eufy app (just like normal recordings captured by de doorbell itself)

**Comment by bropat** [comment]
@rickleka 

> Is there an option (send msg?) to trigger the doorbell to start recording?

No, unfortunately that is not possible.
