### ISSUE TITLE
Add abitity to set "working mode" for cameras

### ISSUE THREAD

**Issue by ricco24** [bropat/eufy-security-ws#59]
**Description**  
On all my cameras i have working mode set to "Optimal Battery Life". But when i leaving house or going to sleep it will be nice set all my cameras to "Optimal Surveillance" mode. But Eufy native global security modes (Home, Away ...) doesn't have this functionality.

**Desired behavior**  
Ability to setup "working mode" (from Power Manager) per camera via HA services call. Then i can setup desired functionality with automation/node red.

P.S.: I dont know if Eufy API has capability for this functionality.

**Comment by bropat** [comment]
@ricco24 

This is already possible by setting the property `powerWorkingMode` via [this](https://github.com/bropat/eufy-security-ws#set-property-value-1) method.
The values that are supported are already returned when [this](https://github.com/bropat/eufy-security-ws#get-properties-metadata) method is called.
The values are different depending on the device.

**Comment by ricco24** [comment]
Thank you for you response 👍
