### ISSUE TITLE
Internet blocked

### ISSUE THREAD

**Issue by Heliem** [bropat/eufy-security-ws#60]
Sorry that this is not a bug, but strangely I cannot find any information about this.
Is this library not supposed to work when the homebase 2 is blocked from accessing the internet? I can still use the eufy app when at home but this library just gives me the error:
`ERROR P2PClientProtocol.lookup(): station: T8010XXXXXXX - All address lookup tentatives failed`

I'm probably wrong, but from what I understand about the logs/code, the library tries to get the homebase local ip from one of the cloud addresses and then connects directly to it. 
The problem seems to be that if the homebase has no internet access, then the cloud address returns nothing and the library doesn't connect.

Couldn't a multicast be used to find the homebase? Or maybe even easier, couldn't the library try to use the IP that eufy sent when the connection is made? From what I can see in the logs, when the connection is made eufy sends a lot of information about the cameras and homebase including the (probably last seen) local ip. Couldn't the library use that to connect for a truly offline experience?

I'm sorry in advance if what I'm saying makes no sense..
And thank you @bropat for an excellent library! and @fuatakgun for the HA integration!

**Comment by ronaldt80** [comment]
I have this error as well, however in my case it is not blocked from internet. I do however have the homebase on a different vlan since last week and have changed dns to adguard. Maybe the Chinese government / Eufy doesn't like this..

**Comment by ronaldt80** [comment]
Put them back on the same vlan. For ca. 18 hrs  no errors, theY just returned though, again the P2P one, seems as if it can't find the homebase.

**Comment by bropat** [comment]
@Heliem 
> I'm probably wrong, but from what I understand about the logs/code, the library tries to get the homebase local ip from one of the cloud addresses and then connects directly to it.
The problem seems to be that if the homebase has no internet access, then the cloud address returns nothing and the library doesn't connect.

Correct.

**Comment by Heliem** [comment]
It is now possible to use this plugin while keeping the homebase completely cut off from the internet!
Thank you so much @bropat it was totally worth the wait!
