### ISSUE TITLE
Battery does not appear in device information.

### ISSUE THREAD

**Issue by jconn7** [bropat/eufy-security-ws#61]
Thank you very much for this project. One issue I have run into is I am running 2 "eufyCam 2" but I can not see either of their battery statistics in the device details. Everything else is working flawlessly, but that one stat of each camera is missing. Is this specific to this model or have I mucked up implementation somewhere. Thank you!

Camera Details Below:
type: DEVICE_TYPE.CAMERA
category: CAMERA
state:
name: Front Yard
model: T8111
serialNumber: T8111H121941037E
hardwareVersion: HAIYI-IMX323
softwareVersion: 1.9.3
stationSerialNumber: T8001H13193500C8
enabled: true
motionDetected: false
personDetected: false
personName: ''
antitheftDetection: true
autoNightvision: true
motionDetection: true
rtspStream: false
watermark: 2
pictureUrl: >-
https://zhixin-security-pr.s3.us-west-2.amazonaws.com/xxx
type: 1
motionDetectionType: 0
microphone: true
speaker: true
audioRecording: true
powerSource: 0
powerWorkingMode: 1
recordingEndClipMotionStops: true
recordingClipLength: 60
recordingRetriggerInterval: 5
notificationType: 1
motionDetectionSensitivity: 86
statusLed: false
rtspStreamUrl: ''
chargingStatus: 2
p2pLiveStreamingStatus: false
rtspLiveStreamingStatus: false
properties:
name:
value: Front Yard
timestamp: 1638307529000
model:
value: T8111
timestamp: 1638307529000
serialNumber:
value: T8111H121941037E
timestamp: 1638307529000
type:
value: 1
timestamp: 1638307529000
hardwareVersion:
value: HAIYI-IMX323
timestamp: 1638307529000
softwareVersion:
value: 1.9.3
timestamp: 1621561266000
stationSerialNumber:
value: T8001H13193500C8
timestamp: 1638307529000
pictureUrl:
value: >-
https://zhixin-security-pr.s3.us-west-2.amazonaws.com/xxx
timestamp: 1638504051000
recordingClipLength:
value: 60
timestamp: 1638310456697
recordingRetriggerInterval:
value: 5
timestamp: 1638310456697
recordingEndClipMotionStops:
value: true
timestamp: 1638310456697
rtspStreamUrl:
value: ''
timestamp: 1638310456697
motionDetectionType:
value: 0
timestamp: 1621560464000
chargingStatus:
value: 2
timestamp: 1629688219000
watermark:
value: 2
timestamp: 1621560514000
statusLed:
value: false
timestamp: 1621560464000
autoNightvision:
value: true
timestamp: 1621560514000
powerWorkingMode:
value: 1
timestamp: 1621560524000
rtspStream:
value: false
timestamp: 1621560514000
microphone:
value: true
timestamp: 1621560514000
audioRecording:
value: true
timestamp: 1621560514000
enabled:
value: true
timestamp: 1621560464000
motionDetectionSensitivity:
value: 86
timestamp: 1621560514000
speaker:
value: true
timestamp: 1621560514000
powerSource:
value: 0
timestamp: 1621560514000
motionDetection:
value: true
timestamp: 1621560464000
antitheftDetection:
value: true
timestamp: 1629694657000
notificationType:
value: 1
timestamp: 1621560514000
motionDetected:
value: false
timestamp: 0
personDetected:
value: false
timestamp: 1638504064389
personName:
value: ''
timestamp: 1638504064389
custom:
is_streaming: false
stream_source_type: ''
stream_source_address: ''
codec: h264
is_rtsp_streaming: false
is_p2p_streaming: false
friendly_name: Front Yard
entity_picture: >-
/api/camera_proxy/camera.front_yard?token=xxx
supported_features: 3

**Comment by bropat** [comment]
@jconn7 

From what I can see above you have a model T8111 and therefore an eufyCam 1.
So far I have not had the pleasure of testing an eufyCam 1. The driver [eufy-security-client](https://github.com/bropat/eufy-security-client) is probably missing some functionalities. To test/implement the missing features in the driver I need access.

Let me know.

**Comment by jconn7** [comment]
Great to know thank you. I bought a package while the form factor is the same, I did not realize they were an older model. Appreciate the insight!

**Comment by bropat** [comment]
This device is not fully implemented yet as I have not been able to test it.
Could you share your device with me on one of the following accounts:

* patrick.broetto+eu2@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

Let me know.

**Comment by bropat** [comment]
Stale
