### ISSUE TITLE
[Question]: Need help first example

### ISSUE THREAD

**Issue by frad80** [bropat/eufy-security-ws#65]
### Ask your question

Hello, i´m a rooki in the wrapper theme. I´ve installed the eufy security ws as a docker. It works. 

Bit what are the first steps? Can you explain a simple example how to access the docker station? 

When i tried: 192.168.178.10:3000 i get the message connection refused

Should came a web frontend? Sorry for the rookie question...

**Comment by guldnerthomas** [comment]
Hi,

You can find some examples with easy python scripts on my post here (in french sorry, maybe you can use google translate) : https://community.jeedom.com/t/integration-de-materiel-eufy/76603/1
