### ISSUE TITLE
[Bug]: unable to arm or disarm the system

### ISSUE THREAD

**Issue by leonardpitzu** [bropat/eufy-security-ws#70]
### Version

0.7.0

### Node version

n.a.

### Operating System type

Docker

### Operating system version

docker

### Describe the bug

i can view the status of the cameras connected over homebase 2 but i can't arm or disarm the system.

### To reproduce

start the container and try to arm the system - it's not happening and after some time you can see "command aged out"

### Screenshots & Logfiles

[eufy.csv](https://github.com/bropat/eufy-security-ws/files/7808447/eufy.csv)

### Additional context

this is a generic setup there the docker container runs unmodified on a synology NAS box.

**Comment by michaeleberhardt** [comment]
Same problem here, also Docker environment.
Log:
```
2022-01-06 07:46:58.307  WARN Station T8010P23211***** - Command aged out from queue 
{
  commandType: 1145,
  nestedCommandType: undefined,
  channel: 3,
  ageing: 205207,
  maxAgeing: 45000
}
```

**Comment by leonardpitzu** [comment]
[eufy.csv](https://github.com/bropat/eufy-security-ws/files/7844411/eufy.csv)
debug logs attached

**Comment by bropat** [comment]
This seems a UDP connectivity issue.
