### ISSUE TITLE
[Bug]: Indoor chime not working

### ISSUE THREAD

**Issue by Zeunas** [bropat/eufy-security-ws#71]
### Version

0.7.0

### Node version

N/A

### Operating System type

Linux

### Operating system version

Home assistant core-2021.12.9

### Describe the bug

Issue #https://github.com/fuatakgun/eufy_security/issues/164 reported on Eufy integration for Home assistant [eufy_secutiry](https://github.com/fuatakgun/eufy_security), however developer has suggested to report the issue here.

Newest versions have introduced an Indoor Chime switch which I assume is to turn on/off the chime ring after the doorbell button is pressed, however it does nothing. It's always off, regardless and switching on or off, doesn't really change the indoor chime on/off option on the app.

As far as I can tell, this Indoor Switch is related to the Ringtone Settings switch on the app that controls the "Wi-Fi Doorbell Chime Alert" and has described above, it does nothing nor synchronizes with the status of the switch on the app. There is also a Snooze option to snooze Motion or Chime for x amount of time, which may be a good plan B to make this option more reliable as it's useful for periods where it's useful not to have the Chime ringing.

### To reproduce

1. Install eufy_repository on Home assistant and set up
2. Try switching Indoor Chime switch on / off
3. Try switching on Eufy app as well

### Screenshots & Logfiles

Image of the switch on Home assistant:
![image](https://user-images.githubusercontent.com/71456261/149597266-1656b0cf-2010-4045-9a66-9f9b0811daaf.png)

**Comment by fuatakgun** [comment]
thanks for sharing a temporary solution, let's wait response on other side, I will just update the library version here.

**Comment by Zeunas** [comment]
Afraid that Chime Volume has not stopped working so the temporary solution no longer works.

![image](https://user-images.githubusercontent.com/71456261/151347560-6f28fd82-a50c-4932-9216-afc036af391e.png)

Changing on the app eventually syncs with Home assistant but not the other way around...

**Comment by bropat** [comment]
I need the debug logs to find the exact cause.

**Comment by Zeunas** [comment]
> I need the debug logs to find the exact cause.

Chime Volume is working again, forgot to mention. 

I will check if I can extract something from the logs re Chime switch.

**Comment by Zeunas** [comment]
Here you go, this is what happens when I switch the Indoor Chime On and Off. Please note that regardless of the status of the switch on the Eufy app, Home Assistant switch always reports Off and if I try to switch it On it always goes back to Off after a few seconds. And as mentioned switching the Indoor Chime switch On and Off has not effect on the Eufy app switch.

```
- 2022-02-03 10:47:58 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - WebSocket message sent. {"messageId": "device_set_property", "command": "device.set_property", "serialNumber": "T8222P6021280739", "name": "chimeIndoor", "value": "True"}
- 2022-02-03 10:47:58 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'result', 'success': True, 'messageId': 'device_set_property', 'result': {}}
- 2022-02-03 10:47:59 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - WebSocket message sent. {"messageId": "device_set_property", "command": "device.set_property", "serialNumber": "T8222P6021280739", "name": "chimeIndoor", "value": "False"}
- 2022-02-03 10:47:59 DEBUG (MainThread) [custom_components.eufy_security] eufy_security - on_message - {'type': 'result', 'success': True, 'messageId': 'device_set_property', 'result': {}}
```

**Comment by bropat** [comment]
@Zeunas 

I need the debug logs from eufy-security-ws and not from another integration...

**Comment by Zeunas** [comment]
Ah yes, that makes sense sorry...However not sure how to do it if not via Home Assistant logger, @fuatakgun are you able to shed some light?

**Comment by fuatakgun** [comment]
Sadly, we can not generate debug logs to share with @bropat inside home assistant. So, you have to run a docker instance manually and redirect your home assistant to the docker instance (not supervisor addon)

**Comment by bropat** [comment]
@fuatakgun 

Since version 0.8.0 there are new commands to control log level and get log messages.

Look [here](https://github.com/bropat/eufy-security-ws/releases/tag/0.8.0) and [here](https://bropat.github.io/eufy-security-ws/#/api_cmds?id=set-log-level).

**Comment by fuatakgun** [comment]
thanks @bropat for the ping, home assistant UI is only showing last 100 lines of docker logs, users should SSH to machine and read the system logs to get the full logs and it would be hard to extract them from there. That is because, I advised to run a separate / temporary docker container to fetch these logs.

**Comment by wimb0** [comment]
I'd like to report the same issue.
The switching works, the chime does turn on and off, but the switch in Home Assistant always shows off.
When switching, the Home Assistant switch turns on for a few seconds and then turns off itself, but the setting in the Eufy app doesnt change again.

Which specific debug log do you need?

**Comment by bropat** [comment]
I need the complete debug logs of eufy-security-ws.

**Comment by bropat** [comment]
Alternatively, I need access to the device with admin rights.

**Comment by bropat** [comment]
stale
