### ISSUE TITLE
[Bug]: No Devices Found

### ISSUE THREAD

**Issue by spaceboy76** [bropat/eufy-security-ws#74]
### Version

0.7

### Node version

?

### Operating System type

Other

### Operating system version

Home Assistant 2021.12.10

### Describe the bug

Everything set up per instructions. Country code used is GB for UK
![image](https://user-images.githubusercontent.com/9905053/151249226-c2657ea1-0f9c-41f7-8ce7-68633794b5ac.png)

### To reproduce

1. Start Eufy Security Addon
2. See errors in log

**Comment by dewoert** [comment]
Exact same problem here.
Country code set to NL

**Comment by bjornhij** [comment]
Same here, country NL.

**Comment by hagepat** [comment]
Also problem exist here. Country code: NL

**Comment by hzoet88** [comment]
same issue here. Country code: NL

**Comment by rhamar** [comment]
same issue here. Country code: NL

**Comment by bropat** [comment]
Eufy has implemented some new features with version 4 of the app, including the creation of custom “houses” for sharing devices.
Those who already use version 4 of the app and share the devices with it will not see them at the moment via the eufy-security-client integrations.
I have already had a quick look at the code and can tell you that it will not be a problem to support this.
I just don’t have much time for hobbies lately, so please be patient.

In the meantime, use a version < 4 of the app (IOS and Android) with eufy-security-client integrations for sharing devices.

**Comment by spaceboy76** [comment]
cheers! I'm not sure how to get hold of a <4 version of the ios app so i'll probably just wait for now. plenty of other home automation stuff for me to be getting on with :)

**Comment by bropat** [comment]
Will be fixed in the next version.

**Comment by Palmke** [comment]
If you _really_ need to share devices or fix the issue _now_, you can always download an Android emulator and sideload an older eufySecurity APK.
I know that is a hassle, but at least you will be able to work around the issue if you have only iOS device with v4 apps.

**Comment by dewoert** [comment]
> If you _really_ need to share devices or fix the issue _now_, you can always download an Android emulator and sideload an older eufySecurity APK. I know that is a hassle, but at least you will be able to work around the issue if you have only iOS device with v4 apps.

@Palmke 
Can you explain these steps a bit more ?
Version of EufySecurity App ?
Do I need to reconfigure the Doorbell and HomeBase ?
Do i have to create new account to use with that older App ?
I would like to try this method, have it running now in Bluestack emulater.

**Comment by bropat** [comment]
If all goes well, I will publish the new version today.

**Comment by Palmke** [comment]
@dewoert you can just login with your existing account I guess.
Bluestacks was also the emulator I was thinking about. Your devices keep working, no need to reconfigure.

**Comment by bropat** [comment]
@Palmke 

According to my tests it shouldn't.

**Comment by bropat** [comment]
Version 0.8.0 released

**Comment by san84** [comment]
Dear @bropat 

Please have a look at https://github.com/fuatakgun/eufy_security/issues/258

Many people are still facing the „no devices / no stations“ issue.

Thank you very much for your advice.

**Comment by rpartapsing** [comment]
yes, indeed @san84 . Same here. Today I upgraded core to 2022.2.3 and the app to 0.8.1. Guess that was too much of updating in one goal.

**Comment by Palmke** [comment]
Has anyone running into the issue now used the 4.0 app, or are you all still on 3.x versions?

**Comment by san84** [comment]
> Has anyone running into the issue now used the 4.0 app, or are you all still on 3.x versions?
> Asking because I logged into the 4.0 once, and I get my stations and devices just fine on `eufy-security-ws` 0.8.1 (and 1.6.3 of the client).

I’m on iOS V4.0.0_867

**Comment by Palmke** [comment]
> I’m on iOS V4.0.0_867

That sucks. As I am not using HA, but only `eufy-security-ws`, maybe it's a HA issue?

**Comment by Beer17HWAM** [comment]
Tried to share devices with an old Eufy app (version 2.4.0) on Android. Same results. No stations found. No devices found.
When can we expect an update??

**Comment by Beer17HWAM** [comment]
How can I fill the country if I run a docker.

docker run -it --privileged -e USERNAME=xx@xxxx.com -e PASSWORD=xxxx -p 3300:3000 bropat/eufy-security-ws:0.8.1

I use local port 3300 because port 3000 is already used on my Raspberry pi4.

**Comment by bropat** [comment]
With the latest version we use the new API from eufy which combines both sharing mechanisms (device and home sharing; same API provides all data).

The selection of the country is very important, it decides on which Eufy Cloud you connect. If you enter the wrong value here, you will not see any devices.

Excerpt from the Eufy Forum regarding Eufy App 4.0 ([source](https://communitysecurity.eufylife.com/t/tips-for-eufy-security-app-v4-0/2420747)):

```
1. Why are all my devices not visible after logging in ？
You cannot access the devices if you choose a new region which is different from the previous one. Please logout and make sure to reselect the actual region.
```
![image](https://user-images.githubusercontent.com/2305255/152790746-c0d0ad3d-3edc-4413-add1-a4cb65374e96.png)

When I look at @fuatakgun's addon, I see the following error (the country was hardcoded with the value US):

https://github.com/fuatakgun/eufy_security_addon/blob/a3de3eee9a142db252f510784a199039a5d72e92/config.json#L30

The Docker container of mine supports the following configuration variables:

https://bropat.github.io/eufy-security-ws/#/docker

**Comment by fuatakgun** [comment]
@bropat , it is a default value and users are required to put their 2-letter country code inside Home Assistant.

**Comment by Beer17HWAM** [comment]
> @bropat , it is a default value and users are required to put their 2-letter country code inside Home Assistant.

I use a docker. Can't fill it in Home Assistant.

docker run -it --privileged -e USERNAME=xx@xxx.com -e PASSWORD=x -e COUNTRY=NL -p 3300:3000 bropat/eufy-security-ws:0.8.1

NL is still not detecting devices. I see "Netherlands" in de Eufy APP on my iPhone and Android. The account is okay because I see the shared HOME with devices.





NL is stil not

**Comment by bropat** [comment]
@fuatakgun 
Okay, thanks. I overlooked that...

**Comment by TEF2one** [comment]
@bropat , I am running Android v3.5.1159(EU) which logs are you referring to?
My addon logs only shows:
`2022-02-07 13:04:30.243  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-07 13:04:32.621  INFO  No stations found. 
2022-02-07 13:04:32.855  INFO  No devices found. 
2022-02-07 13:04:33.338  INFO  Push notification connection successfully established 
2022-02-07 13:04:47.984  INFO  No stations found. 
2022-02-07 13:04:48.225  INFO  No devices found. `

**Comment by rpartapsing** [comment]
Same at @TEF2one. btw the Android app does not show at the top right corner the option to choose country.

**Comment by Beer17HWAM** [comment]
> Same at @TEF2one. btw the Android app does not show at the top right corner the option to choose country.

You can choose country in the app if you login for the first time in the app.

**Comment by Beer17HWAM** [comment]
> I need debug logs. Please send me your complete and uncensored debug log to my mail. So I can do some tests and understand where the problem is. Also please tell me if you are using the IOS or Android app and in which version.
> 
> Today after work I will dedicate myself to the matter.

I need an email address.

**Comment by bropat** [comment]
@TEF2one 

You enable debugging as described [here](https://bropat.github.io/eufy-security-ws/#/docker) by adding the DEBUG parameter to the Docker container's passed parameters.

For example: `DEBUG=y`

**Comment by bropat** [comment]
@Beer17HWAM 

patrick.broetto@gmail.com

**Comment by Beer17HWAM** [comment]
> patrick.broetto@gmail.com

Thx. mailed log.

**Comment by bropat** [comment]
New version released 0.8.2

**Comment by mzelmanovich** [comment]
New version worked for me and the account share with.

**Comment by mzelmanovich** [comment]
Oh i think I have the same issue..... Let me check the doorbell

**Comment by Beer17HWAM** [comment]
> Oh i think I have the same issue..... Let me check the doorbell. I was able to get updates.

Yes, I also have the doorbell and basestation but it's showing information from the moment I started the docker.

How can I refresh something?

**Comment by Palmke** [comment]
> Yes, I also have the doorbell and basestation but it's showing information from the moment I started the docker.
> 
> How can I refresh something?

Change guard mode or poll refresh using: 
https://bropat.github.io/eufy-security-ws/#/api_cmds?id=update-the-station-and-device-informations

**Comment by Beer17HWAM** [comment]
I thought Home Assistant was updating/reading the sensors and other info
automatically.

**Comment by Palmke** [comment]
It either receives it with the periodic polling configured when starting the client or by sending that message.

**Comment by hunt350** [comment]
same issue , i'm on docker , if you have an idea ?

pi@raspberrypi:~ $ docker run -it --privileged -e USERNAME=XXXXXX -e PASSWORD=XXXXXX -e COUNTRY=FR -p 3000:3000 bropat/eufy-security-ws:0.8.2
2022-02-08 17:21:41.432  INFO  Eufy Security server listening on host 0.0.0.0, port 3000
Exception in PromiseRejectCallback:
/usr/src/app/node_modules/eufy-security-client/build/http/api.js:224
        return types_1.AuthResult.OK;

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/usr/src/app/node_modules/eufy-security-client/build/http/api.js:440
            switch (await this.authenticate()) {
                               ^

RangeError: Maximum call stack size exceeded
2022-02-08 17:21:42.385  ERROR Error:
 RangeError  Maximum call stack size exceeded
error stack:
• errors:100 prepareStackTrace
    node:internal/errors:100:21

• CallSitesHelper.ts:81 getCallSites
    node_modules/tslog/src/CallSitesHelper.ts:81:15

• LoggerHelper.ts:50 getCallSites
    node_modules/tslog/src/LoggerHelper.ts:50:35

• LoggerWithoutCallSite.ts:376 _buildLogObject
    node_modules/tslog/src/LoggerWithoutCallSite.ts:376:55

• LoggerWithoutCallSite.ts:333 _handleLog
    node_modules/tslog/src/LoggerWithoutCallSite.ts:333:40

• LoggerWithoutCallSite.ts:258 debug
    node_modules/tslog/src/LoggerWithoutCallSite.ts:258:28

• api.ts:142 authenticate
    node_modules/eufy-security-client/src/http/api.ts:142:18

• api.ts:455 request
    node_modules/eufy-security-client/src/http/api.ts:455:32

• api.ts:112 getApiBaseFromCloud
    node_modules/eufy-security-client/src/http/api.ts:112:41


2022-02-08 17:21:42.395  ERROR Status return code not 200
{
  status: undefined,
  statusText: undefined
}
2022-02-08 17:21:42.420  ERROR Error:
 Error  `input` must not start with a slash when using `prefixUrl`
error stack:
• index.js:484 normalizeArguments
    node_modules/got/dist/source/core/index.js:484:23

• create.js:112 got
    node_modules/got/dist/source/create.js:112:39

• api.ts:492 request
    node_modules/eufy-security-client/src/http/api.ts:492:43

• api.ts:168 authenticate
    node_modules/eufy-security-client/src/http/api.ts:168:58

• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

• api.ts:455 request
    node_modules/eufy-security-client/src/http/api.ts:455:21

• api.ts:112 getApiBaseFromCloud
    node_modules/eufy-security-client/src/http/api.ts:112:30

• api.ts:143 authenticate
    node_modules/eufy-security-client/src/http/api.ts:143:25

• api.ts:455 request
    node_modules/eufy-security-client/src/http/api.ts:455:21

• api.ts:112 getApiBaseFromCloud
    node_modules/eufy-security-client/src/http/api.ts:112:30


2022-02-08 17:21:42.425  ERROR Status return code not 200
{
  status: undefined,
  statusText: undefined
}
2022-02-08 17:21:42.426  ERROR Token error
{
  method: 'get',
  endpoint: '/domain/FR'
}
2022-02-08 17:21:44.162  INFO  No stations found.
2022-02-08 17:21:44.321  INFO  No devices found.
2022-02-08 17:21:44.870  INFO  Push notification connection closed
2022-02-08 17:21:45.084  INFO  Push notification connection successfully established
2022-02-08 17:21:50.175  INFO  Push notification connection successfully established

**Comment by bropat** [comment]
@hunt350 Update to version 0.8.3 (released a few seconds ago)

**Comment by bropat** [comment]
For all who can't find devices please update to the latest version (0.8.3) and start eufy-security-ws in debug mode and send me the logs by mail:

patrick.broetto@gmail.com

**Comment by hunt350** [comment]
> For all who can't find devices please update to the latest version (0.8.3) and start eufy-security-ws in debug mode and send me the logs by mail:
> 
> [patrick.broetto@gmail.com](mailto:patrick.broetto@gmail.com)

it's working :)

![image](https://user-images.githubusercontent.com/99251487/153073756-db931178-d78e-4168-92f8-e4ad3cde9252.png)

**Comment by boudicca99** [comment]
morning. since I upgraded last week inc 0.8.3 still the same.. Country GB No Stations etc. I have noticed requests to Captcha so wonder if security-app-eu.eufylife.com i.e security-app-eu-324925769.eu-central-1.elb.amazonaws.com is the an issue but it authenticates and just doesnt return stations or devices as above. Docker on RPI

**Comment by leonardpitzu** [comment]
@bropat - i have sent you some debug logs over e-mail. My setup consists of a Synology running HA core and eufy-security-ws. I do not see any CAPTCHA pop-up in the HA add-on but i have seen it in the app as i logged in using the guest user in order to accept the share request. My location is Romania (RO).

**Comment by Jo-Jo1987** [comment]
is there already version 0.84 available at the fuatakgun repository? I still have 0.83 with the NL (country) captcha bug.

**Comment by Palmke** [comment]
> is there already version 0.84 available at the fuatakgun repository? I still have 0.83 with the NL (country) captcha bug.

You should really be asking this question at the [fuatakgun](https://github.com/fuatakgun/eufy_security) GitHub page...

**Comment by fuatakgun** [comment]
It is getting hard to catch up with bropat's speed :-) i will publish it hopefully today 

 (i am closely tracking all the issues and discussions happening here)

**Comment by fuatakgun** [comment]
I dont see 0.8.4 version of eufy-security-ws??

**Comment by Jo-Jo1987** [comment]
Ah i see, it's clear now :-) thanks for the effort @fuatakgun

**Comment by bropat** [comment]
This time the error was definitely fixed. Tested by myself.

**Comment by boudicca99** [comment]
cracked it...#74....in the UK :)

**Comment by jem24h** [comment]
Hello everyone !

This thread is getting long and i'm jumping from issues to issues without being able to find the solution so I thought I'd ask.
Has anyone figured out these problems metionned identified in the log of the Eufy Security Add-on : 

- status: 423,  statusText: 'Locked' 
- code: '250999',  msg: 'The request is too fast. Please stop and have a rest'
- No devices found. 

Note: I don't have Home-Base, is it mandatory ?

In the intergration, I don't see the camera stream when I click on the gear, and the person detection don't seem to work.
Your help would be much appreciated, I've tried to find a solution for days but can't figure it out. 


`2022-03-25 16:31:33.161  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-03-25 16:31:36.634  INFO  Push notification connection closed 
2022-03-25 16:31:36.702  INFO  Connected to station T8410P20212436DE on host 192.168.31.226 and port 22430 
2022-03-25 16:31:36.720  INFO  Connected to station T8400P2021030E6B on host 192.168.31.168 and port 11413 
2022-03-25 16:31:36.724  INFO  Connected to station T8400P2021030907 on host 192.168.31.28 and port 11385 
2022-03-25 16:31:36.727  INFO  Connected to station T8441P11213220B0 on host 192.168.31.254 and port 11413 
2022-03-25 16:31:36.730  INFO  Connected to station T8410P202124376B on host 192.168.31.56 and port 11385 
2022-03-25 16:31:36.767  INFO  Connected to station T8441P1121291D61 on host 192.168.31.139 and port 11413 
2022-03-25 16:31:36.954  INFO  Push notification connection successfully established 
2022-03-25 16:31:37.369  ERROR Response code not ok 
{
  code: '250999',
  msg: 'The request is too fast. Please stop and have a rest'
}
2022-03-25 16:31:37.374  INFO  No stations found. 
2022-03-25 16:31:37.381  ERROR Status return code not 200 
{
  status: 423,
  statusText: 'Locked'
}
2022-03-25 16:31:39.261  INFO  No devices found. 
2022-03-25 16:31:42.031  INFO  Push notification connection successfully established `

**Comment by SimonToftegaard** [comment]
I have the exact same issue as @jem24h, i can change guard mode of my cameras, but i dont see the status updates in home assistant.
