### ISSUE TITLE
[Bug]: No devices / No stations found

### ISSUE THREAD

**Issue by hagepat** [bropat/eufy-security-ws#75]
### Version

0.7.0

### Node version

*

### Operating System type

Other

### Operating system version

Home Assistant OS 7.2

### Describe the bug

This is a new installation of Eufy 2K doorbell. In HA after the installation of Eufy Security I can't see any devices attached.
** What I already did **
Installed the APP on the phone created 1 main account with 2FA.
Added the HomeBase 2 and Battery Doorbell T8210 to my account.
After that I created a second account and shared my devices from the main account to the second account with "admin rights"
Send the invitation
Then I logged out the main account in the app and logged in with my second account. Accepted the invitation.
Checked that 2FA is disabled -> OK
Then in HA I installed Eufy Security with HACS (Follow instructions "https://github.com/fuatakgun/eufy_security")
Configured with username and password and country code: NL because I live in The Netherlands. See screenshot "SNAG-0000 27-Jan-22 7 50 41 PM"
I checked the log and you can see the output in "SNAG-0000 27-Jan-22 7 47 31 PM"
No devices or Stations found
Then I installed the RTSP Simple Server Add On
Installed the Eufy repository
Restart HA
Add integration
Entered localhost and port 3000
But of course no devices
![SNAG-0000 27-Jan-22 7 50 41 PM](https://user-images.githubusercontent.com/86970871/151429293-bb5673d3-f7e8-49b0-a89a-d63fd978c6f8.png)
![SNAG-0000 27-Jan-22 7 47 31 PM](https://user-images.githubusercontent.com/86970871/151429303-2274efd9-6aec-42ec-a479-bd67ce1874e9.png)

Checked several post on the HA forum. And found this post "https://community.home-assistant.io/t/eufy-camera-integration/121758/1455" saw that "lvanagteren" has exactly the same problem. 
So I removed everything and started clean. But still the devices are not shown.

### To reproduce

Follow installation: https://github.com/fuatakgun/eufy_security

### Screenshots & Logfiles

![SNAG-0000 27-Jan-22 7 50 41 PM](https://user-images.githubusercontent.com/86970871/151429395-1c203ffc-cffc-4581-b59b-2606a07af18f.png)
![SNAG-0000 27-Jan-22 7 47 31 PM](https://user-images.githubusercontent.com/86970871/151429403-b57e9bda-97b0-42c6-9e72-34329ff8352b.png)

### Additional context

**Hardware Information about Home Assistant
Raspberry Pi4 
HA Core: core-2021.12.10
HA SuperVisor: supervisor-2021.12.2
HA OS: Home Assistant OS 7.2
Eufy Security Add On: Current version: 0.7.0

**Hardware Information about Cameras
- HomeBase 2 and doorbell 2K battery powerd T8210
- Live Streaming Protocol: RTSP

**Comment by ronaldt80** [comment]
Check this out... https://communitysecurity.eufylife.com/t/tips-for-eufy-security-app-v4-0/2420747

@bropat Perhaps related? Eufy changing its setup, users reporting missing notifications and devices.

**Comment by bropat** [comment]
@ronaldt80 

As you rightly point out, Eufy has implemented some new features with version 4 of the app, including the creation of custom “houses” for sharing devices.
Those who already use version 4 of the app and share the devices with it will not see them at the moment via the eufy-security-client integrations.
I have already had a quick look at the code and can tell you that it will not be a problem to support this.
I just don’t have much time for hobbies lately, so please be patient.

In the meantime, use a version < 4 of the app (IOS and Android) with eufy-security-client integrations for sharing devices.

**Comment by bropat** [comment]
Duplicate of #74
