### ISSUE TITLE
[Bug]: Docker image unable to start.

### ISSUE THREAD

**Issue by MikeJMcGuire** [bropat/eufy-security-ws#77]
### Version

0.8.0

### Node version

N/A

### Operating System type

Linux

### Operating system version

Ubuntu 20.04.3 LTS

### Describe the bug

When starting the bropat/eufy-security-ws:latest docker image, the following error is displayed.

/usr/local/bin/docker-entrypoint.sh: exec: line 11: /usr/src/app/run.sh: not found

I'd been using the previous version of the container successfully. I've since tried to start the container on additional Linux systems with the same error.

### To reproduce

docker run -it \
    -e USERNAME=user \
    -e PASSWORD=password \
    -v /tmp:/data \
    -p 3000:3000 \
    bropat/eufy-security-ws:latest

**Comment by bropat** [comment]
Fixed docker images (latest and 0.8.0)

Please pull the latest image with `docker pull bropat/eufy-security-ws:latest`.

**Comment by MikeJMcGuire** [comment]
Thanks very much.
