### ISSUE TITLE
[Bug]: # Fatal error in , line 0 # unreachable code # # # #FailureMessage Object: 0xbea6858c Trace/breakpoint trap (core dumped)

### ISSUE THREAD

**Issue by Beer17HWAM** [bropat/eufy-security-ws#78]
### Version

0.8.0

### Node version

no idea

### Operating System type

Docker

### Operating system version

Raspberry pi buster raspbian 10

### Describe the bug

I did the following on my Raspberry PI 4:

pi@raspberrypi4:~ $ docker run -it -e USERNAME=[xx@debeertjes.com](mailto:xx@debeertjes.com) -e PASSWORD=xxxx -p 3300:3000 bropat/eufy-security-ws:latest
Unable to find image 'bropat/eufy-security-ws:latest' locally
latest: Pulling from bropat/eufy-security-ws
5480d2ca1740: Already exists
00d662877661: Already exists
c234d4aeb7df: Already exists
9a2fd5970489: Already exists
649bdae7192a: Pull complete
95fb95b35ebd: Pull complete
79fdd427caa8: Pull complete
14f4fc71b2ae: Pull complete
6f7cc63d368a: Pull complete
f825059e16f1: Pull complete
Digest: sha256:aacda17a61ac5193029ac53303330525fe4296a4dce58c33a153208c96bab689
Status: Downloaded newer image for bropat/eufy-security-ws:latest

#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbea6858c
Trace/breakpoint trap (core dumped)

Can you tell me what's wrong?

I used port 3300 because port 3000 is used for zwave2mqtt

### To reproduce

I did the following on my Raspberry PI 4:

pi@raspberrypi4:~ $ docker run -it -e USERNAME=[xx@debeertjes.com](mailto:xx@debeertjes.com) -e PASSWORD=xxxx -p 3300:3000 bropat/eufy-security-ws:latest
Unable to find image 'bropat/eufy-security-ws:latest' locally
latest: Pulling from bropat/eufy-security-ws
5480d2ca1740: Already exists
00d662877661: Already exists
c234d4aeb7df: Already exists
9a2fd5970489: Already exists
649bdae7192a: Pull complete
95fb95b35ebd: Pull complete
79fdd427caa8: Pull complete
14f4fc71b2ae: Pull complete
6f7cc63d368a: Pull complete
f825059e16f1: Pull complete
Digest: sha256:aacda17a61ac5193029ac53303330525fe4296a4dce58c33a153208c96bab689
Status: Downloaded newer image for bropat/eufy-security-ws:latest

#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbea6858c
Trace/breakpoint trap (core dumped)

Can you tell me what's wrong?

I used port 3300 because port 3000 is used for zwave2mqtt

### Screenshots & Logfiles

See above

### Additional context

-

**Comment by bropat** [comment]
look here #47

**Comment by Beer17HWAM** [comment]
pi@raspberrypi4:~ $ docker run -it --privileged -e USERNAME=xx@debeertjes.com -e PASSWORD=xxxx -p 3300:3000 bropat/eufy-security-ws:latest
2022-02-06 13:30:13.737  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-06 13:30:16.033  ERROR MQTT Error 
 Error  Connection refused: Not authorized
details:
{
  code: 5
}
error stack:
• client.js:1386 MqttClient._handleConnack
    node_modules/mqtt/lib/client.js:1386:17

• client.js:547 MqttClient._handlePacket
    node_modules/mqtt/lib/client.js:547:12

• client.js:436 work
    node_modules/mqtt/lib/client.js:436:12

• client.js:450 writable._write
    node_modules/mqtt/lib/client.js:450:5

• _stream_writable.js:409 doWrite
    node_modules/readable-stream/lib/_stream_writable.js:409:139

• _stream_writable.js:398 writeOrBuffer
    node_modules/readable-stream/lib/_stream_writable.js:398:5

• _stream_writable.js:307 Writable.write
    node_modules/readable-stream/lib/_stream_writable.js:307:11

• readable:754 ondata
    node:internal/streams/readable:754:22

• node:events:390 emit
    node:events:390:28

• readable:315 addChunk
    node:internal/streams/readable:315:12


2022-02-06 13:30:16.074  INFO  MQTT connection closed 
2022-02-06 13:30:17.174  INFO  No stations found. 
2022-02-06 13:30:17.708  INFO  No devices found. 
2022-02-06 13:30:17.735  INFO  Push notification connection successfully established

**Comment by Beer17HWAM** [comment]
Is this normal:

***@***.***:~ $ docker run -it --privileged -e USERNAME=
***@***.*** -e PASSWORD=xxxx -p 3300:3000
bropat/eufy-security-ws:latest
2022-02-06 13:30:13.737  INFO  Eufy Security server listening on host
0.0.0.0, port 3000
2022-02-06 13:30:16.033  ERROR MQTT Error
 Error  Connection refused: Not authorized
details:
{
  code: 5
}
error stack:
• client.js:1386 MqttClient._handleConnack
    node_modules/mqtt/lib/client.js:1386:17

• client.js:547 MqttClient._handlePacket
    node_modules/mqtt/lib/client.js:547:12

• client.js:436 work
    node_modules/mqtt/lib/client.js:436:12

• client.js:450 writable._write
    node_modules/mqtt/lib/client.js:450:5

• _stream_writable.js:409 doWrite
    node_modules/readable-stream/lib/_stream_writable.js:409:139

• _stream_writable.js:398 writeOrBuffer
    node_modules/readable-stream/lib/_stream_writable.js:398:5

• _stream_writable.js:307 Writable.write
    node_modules/readable-stream/lib/_stream_writable.js:307:11

• readable:754 ondata
    node:internal/streams/readable:754:22

• node:events:390 emit
    node:events:390:28

• readable:315 addChunk
    node:internal/streams/readable:315:12


2022-02-06 13:30:16.074  INFO  MQTT connection closed
2022-02-06 13:30:17.174  INFO  No stations found.
2022-02-06 13:30:17.708  INFO  No devices found.
2022-02-06 13:30:17.735  INFO  Push notification connection successfully
established
