### ISSUE TITLE
After update to version 0.8.0 (0.8.1 too) Eufy Addon is not working wit error "No stations found" and "No devices found"

### ISSUE THREAD

**Issue by emijime** [bropat/eufy-security-ws#82]
### Version

0.8.0 and 0.8.1

### Node version

that came with Homeassistant OS installed at Rasberry PI

### Operating System type

Linux

### Operating system version

Home Assistant OS 2022.2.3

### Describe the bug

After update to version 0.8.0 the Addon is not working and is possible to see following in the logs:

2022-02-07 08:47:02.847  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-02-07 08:47:05.308  INFO  No stations found. 
2022-02-07 08:47:05.555  INFO  No devices found. 
2022-02-07 08:47:06.132  INFO  Push notification connection successfully established 

Then I updated to version 0.8.1 with the same problem.

With version 0.7.0 there was not problems

I tried to uninstall the addon, update homeassistant to latest version 2022.2.3, checked code country, but non of my tests worked.
I also tried to login to Eufy cameras webpage to double check my account was not locked and it was working fine.

### To reproduce

In my case, the update from version 0.7.0 to version 0.8.0 and latter 0.8.1 was enough to see the problem

**Comment by san84** [comment]
+1 
Country: CH
Core 2022.2.3
Eufy Security 0.8.1

**Comment by mrtnbr** [comment]
+1
I think this is related to / a duplicate of https://github.com/bropat/eufy-security-ws/issues/81

**Comment by bropat** [comment]
New version released 0.8.2

**Comment by emijime** [comment]
I just updated to version 0.8.2 and reboot HA but unfortunatelly with no luck :(

**Comment by emijime** [comment]
I have news. Today the Android version for Eufy was updated to version 4 and then, Eufy for homeassistant started to work so I think it was something related with Eufy webpage.

Note: Was necesary to reboot homeassistant

Thank you very much for your time and help
