### ISSUE TITLE
[Bug]: issue with device.start/stop_livestream

### ISSUE THREAD

**Issue by guldnerthomas** [bropat/eufy-security-ws#86]
### Version

1.6.6/0.8.4

### Node version

v12.22.5

### Operating System type

Linux

### Operating system version

Debian 11.1

### Describe the bug

Hello,

I encounter a problem when I want to use the device.start_livestream/device.stop_livestream/device.is_livestreaming command.
I have the error:
`{"type":"result","success":false,"errorCode":"unknown_command"}`
Docker also shows the error:

```
2022-02-16 09:38:26.510  ERROR Message error
 Error
details:
{
  command: 'device.start_livestream',
  errorCode: 'unknown_command'
}
```

I've tried using different versions of the schema but that doesn't solve the problem.
Here is my test script that calls this command:
```
import json
from websocket import create_connection
ws = create_connection("ws://192.168.1.42:3000")
print(ws.recv())
ws.send(json.dumps({"command": "device.start_livestream", "serialNumber": "T8113NXXXXXXXXXXX"}))
print(ws.recv())
ws.close()
```

Thanks in advance for your help.

### To reproduce

Try to use the next script to open livestream : 
import json
from websocket import create_connection
ws = create_connection("ws://192.168.1.42:3000")
print(ws.recv())
ws.send(json.dumps({"command": "device.start_livestream", "serialNumber": "T8113NXXXXXXXXXXX"}))
print(ws.recv())
ws.close()

**Comment by bropat** [comment]
Please read the documentation. [Here](https://bropat.github.io/eufy-security-ws/#/api_introduction) you will find the answer to your problem.

**Comment by guldnerthomas** [comment]
Thanks for your answer and the work performed on the eufy environment.

I have read the documentation and how to set the schema version but sorry I still can't do it.
No matter what schema version I tell the server I get "Success" back but it doesn't seem to apply.
Would it be possible to have a little more explanation?
I make my tests with postman.
![image](https://user-images.githubusercontent.com/64778687/155352750-25ad299c-5c8e-440d-9a19-586ccd8b1ca2.png)

Thanks in advance.
