### ISSUE TITLE
[Question]:  T8420 start livestream "unknown error"

### ISSUE THREAD

**Issue by bricevalenza** [bropat/eufy-security-ws#88]
### Ask your question

Hello,

I'm trying to get eufy-security-ws working, to interact with my cameras.
I had some difficulties to communicate with the WS server, but to do my tests I found a client present on the docker that I could launch with the command "node /usr/src/app/dist/bin/client.js"

![image](https://user-images.githubusercontent.com/799962/155132908-d7501c7b-97b1-4dfd-a3df-ce60a3562a69.png)

With this command I can communicate with my camera (turn on the light for example), but I can't launch the livestream.
![image](https://user-images.githubusercontent.com/799962/155132994-40a6a1f9-72bc-4fb1-bcde-72a2f55ec3ab.png)
![image](https://user-images.githubusercontent.com/799962/155133023-fca3db5d-bf1a-408e-bbda-78c0d82aef05.png)

Can someone help me? I don't know if there is a bug or if I'm not using the web socket correctly.

Thanks.

**Comment by bricevalenza** [comment]
Hi,

I activated the debug logs and here is the result on the server console : 

` RangeError  The argument 'size' is invalid. Received -128 `

![image](https://user-images.githubusercontent.com/799962/157677440-a832b969-a6f1-4bd1-a519-cbc38cd150bc.png)

    device_model: 'T8420X',
    device_channel: 0,
    schedulex: '',
    main_sw_version: '2.0.4.8',
    main_hw_version: 'P1',
    sec_sw_version: '2.0.4.1',
    sec_hw_version: 'P1',


While for a T8410 (Indoor Pan& til) it works: 
![image](https://user-images.githubusercontent.com/799962/157679501-57cb2af5-1b9f-40ff-8c73-f0b3fac01f79.png)


Do you need more information

Thanks.

**Comment by bricevalenza** [comment]
Hi,

I think is the same bug :  
https://github.com/bropat/eufy-security-client/issues/127

**Comment by bropat** [comment]
@bricevalenza 

I have found the error. However, in order to fix it, I need access to the device in this case, because I need to perform a network trace of the P2P protocol.
Let me know if this is possible.

**Comment by bricevalenza** [comment]
> @bricevalenza
> 
> I have found the error. However, in order to fix it, I need access to the device in this case, because I need to perform a network trace of the P2P protocol. Let me know if this is possible.

@bropat yep no problem, but i dont find your adress to share my device with you.

**Comment by bricevalenza** [comment]
@bropat, i found it, i share my device with patrick.broetto+eu2@gmail.com

**Comment by bropat** [comment]
@bricevalenza 

I see the device in the Eufy app, but the app cannot establish a P2P connection to it.
So I can't test anything myself...
Can you reach the camera with the Eufy app?

**Comment by bricevalenza** [comment]
> @bricevalenza
> 
> I see the device in the Eufy app, but the app cannot establish a P2P connection to it. So I can't test anything myself... Can you reach the camera with the Eufy app?

I had forgotten but I have some trouble to access to the cameras behind my 4G router (my only access to the home).
So I use a VPN when I need it.
I'll look for a solution to give you access easily, I might have an idea.

**Comment by bricevalenza** [comment]
hi @bropat,

it should be good now :)

**Comment by bropat** [comment]
@bricevalenza 

It worked for sure 1 time when I tried to find the problem. Unfortunately, I did not have enough time to fix and test the problem. Now I have tried to access it again and it no longer connects (not even with the Eufy app).

**Comment by bricevalenza** [comment]
@bropat 
Weird... it always works for me from the outside. 
Unfortunately I couldn't do better I don't have a more stable internet access :/ 
Is there anything I can try to do so you can debug?
