### ISSUE TITLE
[Bug]: Wrong serialNumber returned in "download video data" event

### ISSUE THREAD

**Issue by ema-dev** [bropat/eufy-security-ws#90]
### Version

0.8.4

### Node version

16.14.0

### Operating System type

Docker

### Operating system version

Docker Desktop for Windows - 20.10.12

### Describe the bug

When I send the command to start a download, the message looks like this:
`{
    "messageId": 1,
    "command": "device.start_download",
    "serialNumber": "serialNumberOfTheTargetDevice",
    "path": "path/to/file.data",
    "cipherId": ###
  }`

The subsequent events appear as:
`{
    "type": "event",
    "event": {
        "source": "device",
        "event": "download video data",
        "serialNumber": "serialNumberOfAnotherDeviceConnectedToHomebase2",
        "buffer": {
            "type": "Buffer",
            "data": [1,0,1]
       },
        "metadata": {
            "videoCodec": "H264",
            "videoFPS": 15,
            "videoHeight": 1080,
            "videoWidth": 1920
        }
    }
}`

### To reproduce

1. Connect to Eufy Security WS (I connected through Postman)
2. Send command to download a clip from a device (in my case a eufyCam 2C connected to a HomeBase2 with other eufyCam 2C's connected)
3. View video data events with incorrect serial number

### Additional context

The incorrect serial number in the "download video data" messages is the first device listed for the "devices" in the result from the "start_listening" command. The incorrect serial number is also the first device in the "devices" for the HomeBase in the response from a call to "/api/v1/app/get_hub_list".

**Comment by bropat** [comment]
@ema-dev

I need the debug logs to find the cause.
