### ISSUE TITLE
[Question]: Changed IP of HA Now Eufy Security won't connect

### ISSUE THREAD

**Issue by tlman12** [bropat/eufy-security-ws#93]
### Ask your question

I Changed the IP address of my Home assistant device but the Eufy Security Addon keeps trying to connect to the old IP. 

`Logger: homeassistant.config_entries
Source: config_entries.py:335
First occurred: 4:54:09 PM (1 occurrences)
Last logged: 4:54:09 PM

Config entry 'localhost' for eufy_security integration not ready yet: Exception: Host/port is not reachable 192.168.1.11 3000!; Retrying in background`

The IP address is now 192.168.1.12 and I can't find any configs anywhere that reference the old IP. I've tried uninstalling both the Eufy Security Integrations and reset all the settings but it still tries to connect to the old IP. 

Where can I find this reference?

**Comment by bropat** [comment]
Wrong repo. This isn't the integration repo.
